telefonicaid/fiware-orion

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/2553_wrong_metadata_type_in_prev_value_in_notification/wrong_metadata_type_in_prev_value_in_notification.test

Twin on PR #2578 (by cherry-picking the squashed commit)

Bug/2553 wrong metadata type in prev value in notification (master)

---

CHANGES_NEXT_RELEASE
docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h

You can compare looking to this similar PR https://github.com/telefonicaid/fiware-orion/pull/2576

Step: 1.4.0 -> 1.4.1

---

test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_metadata.feature
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
----------------------------------------------------------------------------------------------------------------------------------
|                                   name                                       | passed | failed | skipped |  total  | duration(s) |
----------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\subscriptions\notifications\notifications_metadata.feature |     43 |      0 |      25 |      68 |      63.796 |
----------------------------------------------------------------------------------------------------------------------------------
|  Date: Monday, October 10, 2016 17:56:33
1 feature passed, 0 failed, 0 …
```

[REVIEW] tests associated to DM-1919

---

test/functionalTest/cases/2596_retrieve_entity_without_attrs/retrieve_entity_without_attrs.test

This .test covers the case described in #2596

ADD .test to cover the case of issue #2596 (false alarm)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoUpdateSubscription.cpp
src/lib/mongoBackend/safeMongo.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp

Fixes #2597 for the master branch

FIX over-logging of Runtime Error traces not representing actual error

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoUpdateSubscription.cpp
src/lib/mongoBackend/safeMongo.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp

Mirror for PR #2599  (using cherry-pick)

FIX over-logging of Runtime Error traces not representing actual error (release/1.4.0)

---

scripts/build/release.sh

A "missing piece" related with PR #2608 (issue #2607)
@cesarjorgemartinez @AlvaroVega

FIX release.sh script to take into account master as branch for dockerfile

---

scripts/build/fiwarelab/build-fiwarelab-image.sh

Update build-fiwarelab-image.sh with new Cygnus RPM pacakage name

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/rest/StringFilter.cpp
test/functionalTest/cases/0876_attribute_dates/filter_attr_datecreated_sub.test
test/functionalTest/cases/0876_attribute_dates/filter_attr_datemodified_sub.test
test/functionalTest/cases/0876_attribute_dates/filter_attr_dates.test
test/functionalTest/cases/0876_attribute_dates/notify_attr_dates_with_metadata.test
test/functionalTest/cases/0876_entity_dates/filter_datecreated_sub.test
test/functionalTest/cases/0876_entity_dates/filter_datemodified_sub.test

Last work items related with #876 
This PR also include some adjustment in the "siblinb" .test for entity dates cases.

Filtering by attr dateCreated/dateModified

---

src/lib/mongoBackend/mongoGetSubscriptions.cpp

A small follow-up of #2597. Already mentioned in CNR

Fix new overlloging case

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
doc/manuals/admin/install.md
doc/manuals/admin/upgrading_crossing_1-5-0.md
mkdocs.yml
scripts/managedb/change_attr_id_separator.py
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/dbFieldEncoding.h
test/functionalTest/cases/2453_attrs_with_double_underscore/attrs_with_double_underscore.test

Mirror PR for https://github.com/telefonicaid/fiware-orion/pull/2616

FIX support attributes with double underscore as part of the name (for master)

---

test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

Recently introduced in a past PR

FIX unit test

---

test/loadTest/README.md
test/loadTest/orion_soak_test_ngsiv1_ngsiv2.jmx

[FEATURE] soak test script to used V1 and V2 versions

---

CHANGES_NEXT_RELEASE
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueNotifier.h

Mirrors PR #2623 into release/1.4.0

Bug/use pool (release/1.4.0)

---

test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

Mirrors PR https://github.com/telefonicaid/fiware-orion/pull/2620 into release/1.4.0

FIX unit test (release/1.4.0)

---

CHANGES_NEXT_RELEASE
src/lib/ngsi/ContextElementResponseVector.cpp
src/lib/ngsi/ContextElementResponseVector.h
src/lib/ngsiNotify/Notifier.cpp
src/lib/ngsiNotify/Notifier.h
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueNotifier.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/QueueWorkers.h
src/lib/ngsiNotify/senderThread.cpp
src/lib/ngsiNotify/senderThread.h
test/functionalTest/harnessFunctions.sh
test/functionalTest/testHarness.sh
test/valgrind/valgrindTestSuite.sh

Bug/2622 pool custom part2 (release/1.4.0)

---

CHANGES_NEXT_RELEASE
etc/config/contextBroker
etc/init.d/contextBroker.centos

Fix https://github.com/telefonicaid/fiware-orion/issues/2637 for master branch

add logAppend option and fix launch script

---

CHANGES_NEXT_RELEASE
docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h

Should be similar to PR https://github.com/telefonicaid/fiware-orion/pull/2592

Step: 1.4.1 -> 1.4.2

---

test/functionalTest/cases/1048_subscription_cache/cache_population_at_init.test
test/functionalTest/cases/1308_subscription_cache/subCacheMixedSubscriptionsWithUpdatesAndDeletes.test

Add --cache option to test

---

src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueStatistics.cpp
src/lib/ngsiNotify/QueueStatistics.h
test/functionalTest/cases/2015_notification_templates/notification_templates_many_queue_statistics.test

Fix queue stats for custom notif with multiple

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/2647_patch_subscription_bugfix/patch_subscription_bugfix_to_attrs.test
test/functionalTest/cases/2647_patch_subscription_bugfix/patch_subscription_bugfix_to_except_attr.test

FIX subscription PATCH not working for notification.attrs and notification.exceptAttrs subfields

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/all_steps.py
test/acceptance/behave/components/common_steps/batch_operations/__init__.py
test/acceptance/behave/components/common_steps/batch_operations/update_query_steps.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/__init__.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_headers.feature
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/environment.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/steps/__init__.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/steps/step.py

```
SUMMARY:
----------------------------------------------------------------------------------------------------------------------------------------
|                                      name                                          | passed | failed | skipped |  total  | duration(s) |
----------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_headers.feature |     55 |      0 |       0 |      55 |     166.013 |
----------------------------------------------------------------------------------------------------------------------------------------
|  Date: Thursday, November 10, 2016 15:08:51
1 …
```

[FEATURE] headers in update batch operations

---

test/functionalTest/cases/2588_missing_prevval_on_changed_type/2588_missing_prevval_on_changed_type.test

Missing prevValue when only type changes

---

test/functionalTest/cases/2587_attr_update_to_null/attr_update_to_null.test

Add .test covering the no-bug :) described in #2587

ADD .test to cover the case attr update to null

---

test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_part3.feature

```
SUMMARY:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                       name                                                           | passed | failed | skipped |  total  | duration(s) |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attributes.feature               |    111 |      0 |       1 |     112 |      34.470 |
| components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attributes_pa …
```

[REVIEW] tests to bug 1788

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature

```
SUMMARY:
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature |      9 |      0 |      15 |      24 |       3.688 |
|  Date: Friday, November 11, 2016 10:41:18 …
```

[FEATURE]actionType field in update batch operation

---

test/acceptance/behave/components/common_steps/batch_operations/update_query_steps.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_headers.feature

```
SUMMARY:
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature |      9 |      0 |      15 |      24 |       2.899 |
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_headers.feature     |     54 |      0 |       1 |      55 |      10.975 |
---------------------------------------------------------------------------- …
```

[REFACTOR] entities properties to update batch operation

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_entities_id_type.feature

```
SUMMARY:
-------------------------------------------------------------------------------------------------------------------------------------------------
|                                          name                                               | passed | failed | skipped |  total  | duration(s) |
-------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_entities_id_type.feature |     62 |      0 |      28 |      90 |     242.139 |
-------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: Monday, November 14, 2016 12:22:27 …
```

[FEATURE] entities.id and entities types in update batch op

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/batch_operations/update_query_steps.py
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_headers.feature
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
-------------------------------------------------------------------------------------------------------------------------------------------------
|                                          name                                               | passed | failed | skipped |  total  | duration(s) |
-------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature      |     11 |      0 |      15 |      26 |       2.466 |
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_entities_id_type.feature |     62 |      0 |      28 |      90 |     238.959 |
| …
```

[APPEND] functionabilities to update batch op (raw mode)

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_entities_id_type.feature

```
SUMMARY:
-------------------------------------------------------------------------------------------------------------------------------------------------
|                                          name                                               | passed | failed | skipped |  total  | duration(s) |
-------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_entities_id_type.feature |     64 |      0 |      30 |      94 |     210.570 |
-------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: Tuesday, November 15, 2016 16:23:13 …
```

[ADD] new tests in entities id/type for update batch op

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_type.feature

```
SUMMARY:
-----------------------------------------------------------------------------------------------------------------------------------------------
|                                         name                                              | passed | failed | skipped |  total  | duration(s) |
-----------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_attribute_type.feature |     26 |      0 |      15 |      41 |       8.420 |
-----------------------------------------------------------------------------------------------------------------------------------------------
|  Date: Wednesday, November 16, 2016 11:45:01 …
```

[FEATURE] attribute type using update batch op

---

CHANGES_NEXT_RELEASE
test/functionalTest/cases/2676_bugfix_op_update_md_type_checks/bugfix_op_update_md_type_checks.test
test/functionalTest/cases/2681_bugfix_op_update_attr_value_checks/bugfix_op_update_attr_value_checks.test
test/functionalTest/cases/2682_bugfix_op_update_md_value_checks/bugfix_op_update_md_value_checks.test

Functional tests for #2681 and #2682

Functional tests for #2681 and #2682

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_metadata_name.feature

```
`                    SUMMARY:
--------------------------------------------------------------------------------------------------------------------------------------------------------
|                                              name                                                  | passed | failed | skipped |  total  | duration(s) |
--------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_attribute_metadata_name.feature |     46 |      0 |       0 |      46 |      11.116 |
------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

[FEATURE] attribute metadata name using update batch operation

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_metadata_value.feature

```
SUMMARY:
---------------------------------------------------------------------------------------------------------------------------------------------------------
|                                              name                                                   | passed | failed | skipped |  total  | duration(s) |
---------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_attribute_metadata_value.feature |    112 |      0 |       0 |     112 |      31.172 |
---------------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: …
```

[FEATURE] metadata value tests using update batch op

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_metadata_type.feature

```
`                    SUMMARY:
--------------------------------------------------------------------------------------------------------------------------------------------------------
|                                              name                                                  | passed | failed | skipped |  total  | duration(s) |
--------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_attribute_metadata_type.feature |     41 |      0 |       0 |      41 |       6.388 |
------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

[FEATURE] attr metadata type using update batch op

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_metadata_value.feature
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_attribute_value.feature

This PR have new tests for actionType (APPEND, APPEND_STRICT, UPDATE and REPLACE) with several values (compound and special) in attribute value and metadata value

[FEATURE] new tests for actionTypes using several values (attr_value and metadata_value)

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature

```
SUMMARY:
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature |     21 |      0 |      13 |      34 |       7.792 |
|  Date: Friday, November 18, 2016 10:52:04 …
```

[FEATURE] new tests for actionTypes

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/common/globals.cpp
src/lib/common/globals.h
test/functionalTest/cases/2631_partial_datetimes/partial_datetime_creation.test
test/functionalTest/cases/2631_partial_datetimes/partial_datetime_filter.test
test/functionalTest/cases/2632_timezones/timezones.test
test/functionalTest/cases/2632_timezones/timezones_filters.test

Timezone and partial date times support

---

src/lib/ngsi/UpdateActionType.cpp
test/functionalTest/cases/2653_bugfix_op_update_wrong_actiontype/bugfix_op_update_wrong_actiontype.test

Change err msg for wrong axn type

---

test/unittests/ngsi/UpdateActionType_test.cpp

"urgent" fix to unit test breaking build
related to #2700
@kzangeli 
@fgalan

Update unit test to new err msg

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature

```
SUMMARY:
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature |     34 |      0 |       0 |      34 |       7.124 |
|  Date: Tuesday, November 22, 2016 17:40:27 …
```

[REVIEW] bug 2653

---

doc/manuals/user/v1_v2_coexistence.md

Adding a new topic (section) and putting a bit of order (index + top) in the others.

ADD clarifications regarding DateTime in NGSIv2 and NGSIv1

---

src/lib/rest/rest.cpp

Hotfix about being less strict on Accept header in release 1.4.0

Hotfix about being less strict on Accept header

---

docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h

Step: 1.4.2 -> 1.4.3

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_q_and_mq.feature

```
SUMMARY:
------------------------------------------------------------------------------------------------------------------------------------------------
|                                          name                                              | passed | failed | skipped |  total  | duration(s) |
------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\entities\list_entities\list_entities_queries_parameters_q_and_mq.feature |     18 |      0 |     132 |     150 |      12.368 |
------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: Thursday, November 24, 2016 15:31:19 …
```

[FEATURE] DateTime processing

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Entity.cpp
test/functionalTest/cases/2685_batch_op_empty_type/2685_batch_op_empty_type.test

Fixes #2685 
@fgalan 
@kzangeli 
FYI: @iariasleon

Fix op/update, omitted type

---

src/lib/jsonParseV2/parseBatchUpdate.cpp

Using the same branch name as previous PR ... sorry about that

Removed an extra std::string r that cleared out the error description

---

CHANGES_NEXT_RELEASE
src/lib/common/errorMessages.h
src/lib/serviceRoutinesV2/postBatchUpdate.cpp
test/functionalTest/cases/2720_op_update_crash/op_update_crash.test

Fixes https://github.com/telefonicaid/fiware-orion/issues/2720

FIX POST /v2/op/update with empty entities vector makes the broker crash

---

CHANGES_NEXT_RELEASE
src/lib/ngsi/EntityId.cpp
src/lib/rest/rest.cpp
test/functionalTest/cases/0000_content_related_headers/in_out_formats.test
test/functionalTest/cases/2723_entity_type_wrongly_as_pattern/enity_type_wrongly_as_pattern.test

This PR is a manual port (automatic porting was not possible this time, as the origin PRs weren't clean enough to allow this posibility) of some hotfixes done in release/1.4.0 branch
* PR #2709 and PR #2715, related with issue #2722 
* PR #2711, related with issue #2723

FIX backporting of recent hotfixes in release/1.4.0 branch

---

CHANGES_NEXT_RELEASE
src/lib/logMsg/logMsg.cpp

FIX improving performance avoiding unneeded calls to gettid in log library

---

src/lib/serviceRoutinesV2/postBatchUpdate.cpp
test/functionalTest/cases/2720_op_update_crash/op_update_crash.test

Fixes #2720 
Unit test 100%
Test harness 100% (except 2 ones that I hthink are due to local setup)

Last attempt (I hope) to fix #2720

---

test/acceptance/behave/components/ngsiv2/batch_operations/batch_op_update/batch_op_update_action_type.feature

```
SUMMARY:
| components\ngsiv2\batch_operations\batch_op_update\batch_op_update_action_type.feature |     36 |      0 |       0 |      36 |       7.197 |
|  Date: Tuesday, November 29, 2016 09:41:22 …
```

[REVIEW] tests to bug 2720

---

test/acceptance/behave/requirements.txt

@iariasleon @XavierVal please merge when the adjustement in the iotqaUtils repo takes place

acceptance test: change from develop to master in iotqaUtils requirements.txt

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/walkthrough_apiv1.md
doc/manuals/user/walkthrough_apiv2.md

Doc improvements

---

src/lib/cache/subCache.cpp

Sub-cache semaphore was not taken before updating lastSuccess+lastFailure in the sub cache items ...
Stupid mistake, lots of time wasted ... I apologize :-(

using sub-cache semaphore in subCacheItemNotificationErrorStatus

---

CHANGES_NEXT_RELEASE
src/lib/common/errorMessages.h
src/lib/serviceRoutinesV2/postBatchUpdate.cpp
test/functionalTest/cases/2720_op_update_crash/op_update_crash.test

This is a backport of the same fix for #2720 in master branch. It has been done as a sequence of cherry-picks:
* From PR #2731
* 7f834d5 (some conflict in CNR and errorMessages.h occurred) 
* From PR #2733 
* fb6a8ad
* From PR #2736
* 44adcea
* d74d317

Update cause crash (for 1.4.0)

---

src/lib/serviceRoutinesV2/postBatchUpdate.cpp

Fixed a lapsus

---

test/loadTest/cache_refresh/README.md
test/loadTest/cache_refresh/reqs_x_secs.sh

@fgalan @kzangeli @crbrox 
```
Show requests x seconds (TPS)... [CTRL+C] to stop!
----------------------------------------------------------------------------
reqs       requests      tps from first    notifQueue
seconds    each sec      total        to last request      size
-----------------------------------------------------------------------------
--- [ 1 ] ----- [ 34 ] ----- [ 34 ] ----- [ 34.0/s ] ------- [ 793 ]
--- [ 2 ] ----- [ 24 ] ----- [ 58 ] ----- [ 29.0/s ] ------- [ 824 ]
```

[FEATURE] notiQueue size append in the report

---

doc/manuals/admin/README.md
doc/manuals/admin/metrics_api.md
mkdocs.yml

Documentation for #2750 functionality

ADD documentation for the metrics API

---

src/lib/rest/ConnectionInfo.h
src/lib/rest/rest.cpp
src/lib/serviceRoutinesV2/postEntities.cpp
test/unittests/rest/rest_test.cpp

Service path cleanup
Fixes #2786.
This PR contains only internal changes, so no entry in CNR.

service path cleanup

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp
test/functionalTest/cases/2750_common_metrics/2750_incoming_errors.test

Fixes https://github.com/telefonicaid/fiware-orion/issues/2765
(I didn't plan to fix this, but I needed for https://github.com/telefonicaid/fiware-orion/issues/2760)

FIX Accept headers errors in NGSIv2 request were incorrectly rendered using "OrionError" element

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/location.cpp
test/functionalTest/cases/2770_v1_append_not_updates_geo_point/v1_append_not_updates_geo_point.test

FIX NGSIv1 updateContext APPEND on existing geo:point attributes

---

scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Similar changes to PR https://github.com/telefonicaid/fiware-orion/pull/1663

Happy New Year 2017

---

test/functionalTest/harnessFunctions.sh

I need this in master to ease the work in #2760

FIX CB_START_CMD_PREFIX at harnessFunctions.sh

---

test/functionalTest/cases/2805_quotes_in_lhs_of_string_filter/quotes_in_lhs_compound_of_string_filter.test

Second and last part of #2805.
'mega' functest for string filters on compound keys containing dots.

functest for string filters on compound keys containing dots

---

test/functionalTest/cases/2807_quotes_to_stringify_in_string_filter/quotes_to_stringify_in_string_filter.test

Assures that #2807 works correctly.
I added a test with int/string-int, but did not add a test for false ('true' is present).
Seems enough as it is, if anybody wants changes, it is very easy.

Functest for #2807

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_http.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature

Test reviewed: 2796, 2279, 2280, 2303, 2009, 1994
@Ken

[REVIEW] some tests

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature

[ADD] new scenario

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature

[REVIEW] test to bug 1985

---

src/lib/logMsg/logMsg.cpp

Just changing a few tabs for spaces after merging PR by @pekkanikander, to pass our style guide checks

tabs to spaces for style guide

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_http.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature

[FIX] tests modified

---

test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_q_and_mq.feature

Reviewed q and mq parameters
```
SUMMARY:
------------------------------------------------------------------------------------------------------------------------------------------------
|                                          name                                              | passed | failed | skipped |  total  | duration(s) |
------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\entities\list_entities\list_entities_queries_parameters_q_and_mq.feature |     10 |      0 |     150 |     160 |       3.391 |
------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: Monday, January 30, …
```

[REVIEW] and new tests to bug 2226

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_http.feature

```
SUMMARY:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                   name                                                       | passed | failed | skipped |  total  | duration(s) |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_notification_http.feature |    196 |     22 |       0 |     218 |      27.304 |
-------------------------------------------------------------------------------------------------------------------------------- …
```

[REVIEW] and new tests to the bug 2280

---

test/acceptance/behave/components/ngsiv2/admin/metrics/get_metrics/get_metrics_incoming_transactions_part_1.feature
test/acceptance/behave/components/ngsiv2/admin/metrics/get_metrics/get_metrics_incoming_transactions_part_2.feature
test/loadTest/csubs_cache_tests/README.md

```
SUMMARY:
--------------------------------------------------------------------------------------------------------------------------------------------------
|                                           name                                               | passed | failed | skipped |  total  | duration(s) |
--------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\admin\metrics\get_metrics\get_metrics_incoming_transactions_part_1.feature |     16 |      0 |       0 |      16 |      11.553 |
| components\ngsiv2\admin\metrics\get_metrics\get_metrics_incoming_transactions_part_2.feature |     12 |      0 |       0 |      12 |       5.674 | …
```

[REVIEW] bug 2846 and the PR 2841

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib
doc/apiary/v2/fiware-ngsiv2-rc-2016_10_31.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

Fix some http error codes containing letters

Fix some typos in the API documentation

---

doc/manuals/code_contributions.md

SmartSDK team developed and [SDK Client](https://github.com/smartsdk/ngsi-sdk-javascript) compatible with NSGIv2. 
It allows to develop both NodeJS applicaitions and JavaScript applications.

Added SmartSDK NodeJS/JavaScript SDK for NGSIv2 to code_contributions.md

---

test/functionalTest/cases/1964_not_ascii_type_subs/1964_not_ascii_type_subs.test
test/functionalTest/cases/1965_max_len_type_subs/1965_max_len_type_subs.test
test/functionalTest/cases/1967_invalid_chars_type_subs/1967_invalid_chars_type_subs.test

Functests taken from the branch `bug/1964_validation_type_subs`

Incorporated (with some necessary modifications) three older functests

---

test/functionalTest/cases/2163_bug_attrs_format_not_stored/bug_attrs_format_not_stored.test

Changed the year 2017 for 2057 in a functest

Changed the year 2017 for 2057 in a functest

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonSubscription.cpp
src/lib/mongoBackend/MongoCommonSubscription.h
src/lib/mongoBackend/mongoCreateSubscription.cpp

Made `setNewSubscriptionId()` not return a copy of `std::string` on the stack

setNewSubscriptionId

---

test/functionalTest/testHarness.sh

Twin PR: https://github.com/apinf/fiware-orion/pull/4

Fixed an error in disabled functests in valgrind test suite

---

scripts/build/release.sh

FIX release.sh script to adjust Readthedocs documentation link for GET /version

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/rest/rest.cpp
test/valgrind/valgrindTestSuite.sh

Reverts telefonicaid/fiware-orion#2996

Revert "Hardening/valgrind errors 02"

---

test/functionalTest/cases/1080_batch_query_context/batch_query_context_error_conditions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_errors.test
test/functionalTest/cases/1607_query_with_q_and_ranges_but_invalid_operator/query_with_q_and_ranges_but_invalid_operator.test
test/functionalTest/cases/1678_geosubscriptions/geosubscriptions_errors.test
test/functionalTest/cases/1705_csub_cache_objects/csub_cache_objects_errors.test

Twin PR: https://github.com/apinf/fiware-orion/pull/9

Fixed a few functests that failed after a recent PR

---

src/lib/apiTypesV2/CMakeLists.txt
src/lib/apiTypesV2/EntID.cpp
src/lib/apiTypesV2/EntID.h
src/lib/apiTypesV2/Registration.cpp
src/lib/apiTypesV2/Registration.h
src/lib/apiTypesV2/Subscription.cpp
src/lib/apiTypesV2/Subscription.h
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoBackend/mongoGetRegistrations.cpp
src/lib/mongoBackend/mongoGetRegistrations.h

Note base branch is not master, but feature/ngsiv2_registrations

ADD Registration.[h|cpp] and mongoGetRegistrations.[h|cpp] modules

---

doc/manuals/user/walkthrough_apiv2.md

duplicate word in the documentation "the"

duplicate word in the documentation

---

src/lib/common/globals.h
src/lib/common/string.cpp
src/lib/common/string.h
src/lib/mongoBackend/dbFieldEncoding.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextElement.cpp
src/lib/ngsi/Metadata.cpp
src/lib/ngsi/MetadataVector.cpp

As discussed in https://github.com/apinf/fiware-orion/pull/10#discussion_r148488739

PR #3031 follow up

---

src/lib/serviceRoutinesV2/badVerbAllNotDelete.cpp
src/lib/serviceRoutinesV2/badVerbGetDeletePatchOnly.cpp
src/lib/serviceRoutinesV2/badVerbGetPutOnly.cpp

Twin PR: https://github.com/apinf/fiware-orion/pull/12

Added three spaces :-D

---

test/functionalTest/cases/2587_attr_update_to_null/attr_update_to_no_value.test

New .test for #2587. A copy of the existing .test but using no value instead of JSON `null`.

ADD additional test for 2587 case

---

README.md

Fixed Issue Typo errors #2957

---

scripts/accumulator-server.py

[error description](https://ask.fiware.org/question/878/failed-to-execute-accumulator-server-in-orion/l)

FIX accumulator server failes if cert n key are not specified

---

doc/manuals/admin/build_source.md

ADD doc section for "Building MongoDB driver with SASL and SSL support"

---

doc/manuals/contribution_guidelines.md

As recently discussed in PR https://github.com/apinf/fiware-orion/pull/13
@kzangeli

ADD S15 rule and more infor in S2 rule

---

doc/manuals/user/service_path.md

Documentation associated to #3051 
@kzangeli

ADD section regarding reg/subs and service paths to documentation

---

scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Happy New Year 2018

---

src/lib/serviceRoutinesV2/postBatchQuery.cpp
test/functionalTest/cases/1080_batch_query_context/batch_query_context_error_conditions.test

This PR supposely fixes the problems described here https://github.com/telefonicaid/fiware-orion/pull/3056#issuecomment-356576168
CC: @arigliano

Fix 3 funcional test fails introduced by PR #3056

---

doc/manuals/user/context_providers.md

Some doc typo fixing related with #3079

FIX typo in documentation

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/2934_order_by_id_and_type/order_by_id_and_type.test
test/functionalTest/cases/2934_order_by_id_and_type/order_by_id_and_type_combined.test

Partial implementation of #2934

ADD orderBy for id and type

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/cli.md
doc/manuals/user/README.md
doc/manuals/user/ngsiv1autocast.md
doc/manuals/user/v1_v2_coexistence.md
docker/Dockerfile
mkdocs.yml
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
test/functionalTest/cases/0000_cli/bool_option_with_value.test
test/functionalTest/cases/0000_cli/command_line_options.test
test/functionalTest/cases/0000_cli/tracelevel_without_logLevel_as_DEBUG.test
test/functionalTest/cases/3112_ngsiv1_autocast/create_attributes_with_autocast.test
test/functionalTest/cases/3112_ngsiv1_autocast/filters_in_autocasted_attributes.test
test/functionalTest/cases/3112_ngsiv1_autocast/update_attributes_with_autocast.test
test/functionalTest/cases/3112_ngsiv1_autocast/update_only_value_with_autocast.test
test/unittests/main_UnitTest.cpp

NGSIv1 autocast feature

---

README.md
docker/DOCKERSWARM.md
docker/docker_swarm.md

this pull request add to the documentation a short introduction on deploying orion in ha on top of a docker swarm cluster

orion in ha on docker swarm

---

test/functionalTest/cases/3119_qc_nullcharacter_payload/3119_qc_nullcharacter_payload.test

Updating content length 136 ---> 105.

Updating content length for in FT file for PR #3131

---

test/functionalTest/cases/3119_qc_nullcharacter_payload/3119_qc_nullcharacter_payload.test

Adding few more tests in this file to check issue #3119.

Update 3119_qc_nullcharacter_payload.test for Issue #3119

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/orionRestServices.cpp
src/lib/serviceRoutines/CMakeLists.txt
src/lib/serviceRoutines/optionsVersionRequest.cpp
src/lib/serviceRoutines/optionsVersionRequest.h
src/lib/serviceRoutines/versionTreat.cpp
test/functionalTest/cases/0501_cors/version_request.test

Adds CORS support for /version

ISSUE: 3066. CORS support for /version

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
test/functionalTest/cases/0501_cors/registration_cors.test

Adds CORS support for `v2/registrations` and `v2/registrations/<registration-id>`

3049: CORS support for v2 Registration

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoBackend/mongoRegistrationDelete.cpp
src/lib/mongoBackend/mongoRegistrationDelete.h
src/lib/serviceRoutinesV2/CMakeLists.txt
src/lib/serviceRoutinesV2/deleteRegistration.cpp
src/lib/serviceRoutinesV2/deleteRegistration.h
test/functionalTest/cases/3006_delete_registrations/delete_reg_using_v2_created_using_v2.test

Adds: DELETE /v2/registrations/<registration-id>
I have a question:
What should be the proper HTTP response code for successful DELETE requests? When I check, I see that for some cases we send `204 No Content` and for some cases it is `200 OK`. 
For this PR, I left it as `200 OK`. Please let me know if I should change it to `204 No Content`.

3006: Delete Registrations

---

src/lib/apiTypesV2/Attribute.cpp
src/lib/apiTypesV2/Attribute.h
src/lib/apiTypesV2/Entities.cpp
src/lib/apiTypesV2/Entities.h
src/lib/apiTypesV2/Entity.cpp
src/lib/apiTypesV2/Entity.h
src/lib/apiTypesV2/EntityVector.cpp
src/lib/apiTypesV2/EntityVector.h
src/lib/jsonParseV2/jsonRequestTreat.cpp
src/lib/jsonParseV2/parseEntityObject.cpp
src/lib/serviceRoutinesV2/getEntityAttribute.cpp
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp

Just a little and quick simplification...

REMOVE apiVersion in check() and render() methods in lib/apiTypesV2

---

src/lib/apiTypesV2/Entity.cpp
test/unittests/apiTypesV2/Entities_test.cpp
test/unittests/apiTypesV2/EntityVector_test.cpp
test/unittests/apiTypesV2/Entity_test.cpp

Fix a breakage in utest introduced by PR https://github.com/telefonicaid/fiware-orion/pull/3191

FIX broken utest

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3177_updateContext_APPEND_CPr_Registration/updateContext_APPEND_CPr_Reg.test

Fix for issue **actionType is not checked before calling searchContextProviders() in updateEntity() function #2874**  [https://github.com/telefonicaid/fiware-orion/issues/2874]

Fix for issue actionType is not checked before calling searchContextProviders() in updateEntity() function #2874

---

doc/manuals/admin/management_api.md

ADD documentation for tracelevels related with input/output payloads

---

test/functionalTest/cases/2871_fwd_update_ok_but_not_found_response/fwd_update_ok_but_not_found_response.test

We missed an attribute update variante in the .test include for #2871. This PR completes the .test with the missing case.

ADD missing case in #2871 test case

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3000_allow_creation_transient_entities/filter_by_date_expires.test

A new test related with #3000. In addition, the PR includes some fixes related with code style.
@arigliano could you have a look and provide LGTM if you find it ok, please? Thanks!

ADD 3000_allow_creation_transient_entities/filter_by_date_expires.test

---

doc/manuals/user/federation.md
doc/manuals/user/ngsiv2_implementation_notes.md

Documentation pieces related with #2986 
This PR has to be merged together with https://github.com/telefonicaid/fiware-orion/pull/3185. I mean, once we have LGTM *on both* then both can be merged.

ADD documentation regarding NGSIv2 federation

---

doc/manuals/user/walkthrough_apiv2.md

There was an error in walkthrough manual file. Updated the file in "update" batch operations section.

Updated walkthrough_apiv2.md

---

README.md

I updated links to Orion Japanese presentations in main README.md.

Update links to Orion Japanese presentations in main README.md

---

CHANGES_NEXT_RELEASE
README.md
docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h
src/lib/apiTypesV2/Subscription.cpp
src/lib/common/defaultValues.h

The same fix than PR #3257 (for master) + bump version to 1.15.1

Fix for bug 3256 segfauls get all subscriptions (release/1.5.0 branch)

---

test/functionalTest/cases/1029_get_many_entity_types/get_many_entity_types.test

This adds an extra test with more than 101 type, to test mongo 3.6 aggregate queries.

add test with many types to test mongo 3.6 aggregate

---

scripts/utils/populate_500bytes_entities_and_subs.py

ADD populate_500bytes_entities_and_subs.py script

---

README.md

@fisuda please have a look to this PR.
If you think that links should be added in more places, let me know. Otherwise, please provide aproval on the PR so we can merge it. Thanks!

ADD links to jp manuals from root README

---

README.md

@fisuda please have a look and approve if you find it correct. Thx!

ADD link to Japanese Devel Manual in toplevel README

---

doc/manuals/user/forbidden_characters.md

This PR addresses the documentation changes discussed in issue https://github.com/telefonicaid/fiware-orion/issues/3238
@dcalvoalonso could you have a look and provide feedback/LGTM? Thanks!

FIX improved forbidden chars documentation

---

doc/manuals.jp/user/forbidden_characters.md

* FIX improved forbidden chars Japanese documentation
* Fix typo

(JP) FIX improved forbidden chars Japanese documentation (#3278)

---

.travis.yml
ci/rpm7/build.sh
ci/rpm7/makefile

1) Allow executing functional test more than 3 times (parameter in build.sh)
2) Stop functional test if an error occurred
3) Build commits to master branch as well

changes to ci

---

doc/manuals.jp/admin/extra/ha.md
doc/manuals.jp/user/docker.md
docker/README.jp.md
docker/docker_swarm.jp.md

* add docker Japanese Documents into /docker.
* update links to docker jp doc in manuals.jp.

(JP) Add docker Japanese Documents.

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoSubCache.h
src/lib/mongoBackend/mongoUpdateSubscription.cpp
test/functionalTest/cases/3290_filtering_out_all_metadata_sub/filtering_out_all_metadata_sub.test

FIX metadata filter was lost during csub cache refresh

---

test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_equals_null.test
test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_equals_subs.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_equals_null.test
test/functionalTest/testHarness.sh

I recencly spoted some issues in cases/1156, which this PR solves.
More detail in inline comments.

FIX some issues in case/1156 .test

---

src/lib/apiTypesV2/Attribute.cpp
src/lib/apiTypesV2/Attribute.h
src/lib/apiTypesV2/Entities.cpp
src/lib/apiTypesV2/Entities.h
src/lib/apiTypesV2/Entity.cpp
src/lib/apiTypesV2/Entity.h
src/lib/common/macroSubstitute.cpp
src/lib/convenience/UpdateContextAttributeRequest.cpp
src/lib/jsonParseV2/badInput.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/Metadata.cpp
src/lib/parse/CompoundValueNode.cpp
src/lib/parse/CompoundValueNode.h
src/lib/serviceRoutinesV2/getEntities.cpp
src/lib/serviceRoutinesV2/getEntity.cpp
src/lib/serviceRoutinesV2/getEntityAttribute.cpp
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp
src/lib/serviceRoutinesV2/postBatchQuery.cpp
test/unittests/parse/CompoundValueNode_test.cpp

+ CompoundValueNode::toJson() simplified
Implementes issue #3338

REFACTOR OrionError outside apiTypeV2 library

---

doc/manuals/user/multitenancy.md

Updated multitenancy.md

---

doc/manuals/user/security.md

Updated security.md

---

doc/manuals/user/forbidden_characters.md

Updated forbidden_characters.md

---

doc/manuals/deprecated.md

Updated deprecated.md

---

doc/manuals/admin/perf_tuning.md

Related with https://stackoverflow.com/questions/52814894/erron-on-quering-fiware-orion-with-orderby-custom-attribute/52834026#52834026
@fisuda please take this PR into account in order to update Japanese translation.

Improve perf tunning documentation

---

src/lib/mongoBackend/mongoQueryTypes.cpp

Little follow up of PR https://github.com/telefonicaid/fiware-orion/pull/3251, to avoid over logging at ERRROR level.

FIX void logging error in zero results case

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Registration.cpp
src/lib/mongoBackend/mongoRegistrationGet.cpp

Fixes #3375 
The fix has been checked manually. No need of .test for it (the bug is very minor and check logs from .test is hard)

FIX overlogging wrong Runtime Error

---

CHANGES_NEXT_RELEASE
doc/manuals/user/context_providers.md
src/lib/ngsi/ContextAttributeVector.cpp
src/lib/ngsi/ContextAttributeVector.h
src/lib/orionTypes/QueryContextResponseVector.cpp
test/functionalTest/cases/3162_context_providers_legacy_non_primitive/blanked_out_attr.test
test/functionalTest/cases/3162_context_providers_legacy_non_primitive/query_for_arrays.test
test/functionalTest/cases/3162_context_providers_legacy_non_primitive/registration_without_provider.test
test/functionalTest/cases/3282_compound_not_render_in_not_matching_registration/compound_not_render_in_not_matching_registration.test

This PR is a kind of continuation of PR https://github.com/telefonicaid/fiware-orion/pull/3379 and completes the solution for issue #3162 
Remember we have already a solution in place in branch https://github.com/telefonicaid/fiware-orion/tree/bugfixing/3162_fix_but_potential_leak but we suspect about memory leaks on it. This PR provides the same fix but (suppossely) without introducing any leak.
In fact, I have downloaded the .test in that branch and included them in this one in order to ensure the fix is equivalent from a functional point of view, in particular:
* blanked_out_attr.test
* registration_without_provider.test
* query_for_arrays.test (This is special. We already have a query_for_arrays.test.DISABLED file in master branch which seems to be an early and not fully working …

Fix Non-Primitive Values from a Registered Content Provider are not showing a value

---

README.md
scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3067

Happy New Year 2019

---

doc/manuals/admin/perf_tuning.md

A little fix in the performance tunning documentation.
CC: @fisuda in order to sync in Japanese translation once this PR gets merged.

FIX perf tunning documentation

---

README.md

Addresses issue #3400 
CC: @ilarimikkonen

FIX define context information in main README.md

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md
doc/manuals/user/ngsiv2_implementation_notes.md

https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html#forcedupdate-option

Fix list formatting in ngsiv2_implementation_notes.md

---

README.md

Add AGPL disclaimer

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/compoundValueBson.cpp
src/lib/mongoBackend/compoundValueBson.h
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geobox_create_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geobox_update_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geojson_create_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geojson_update_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geoline_create_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geoline_update_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geopoint_create_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geopoint_update_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geopolygon_create_does_not_break_location.test
test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ngsiv1_geopolygon_update_does_not_break_location.test

Fixes https://github.com/telefonicaid/fiware-orion/issues/3442

FIX NGSIv1 updates with geo:line|box|polygon|json removes location DB field of NGSIv2-located entities

---

rpm/SPECS/contextBroker.spec

Update Orion description in .spec, to align with the one in README.md

FIX update Orion description in .spec file

---

doc/apiary/v2/fiware-ngsiv2-2.0.1-wip.apib

@fgalan ,
Please review this PR. It is not necessary to update Japanese document due to this correction (including #3469).
Thanks

Correct typos in fiware-ngsiv2-2.0.1-wip.apib (#3469)

---

test/functionalTest/harnessFunctions.sh
test/valgrind/valgrindTestSuite.sh

Shorter waiting times in test suite

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoUpdateSubscription.cpp

FIX incorrectly loging update subscription traces in ERROR log level

---

doc/manuals/user/ngsiv2_implementation_notes.md

Extra documentation related with #3190
@SourabhChourasiya-NEC if would be great if you could have a look and provide feedback/LGTM
CC: @fisuda the changes in this PR should be synched in the Japanese translation. Of course, any feedback from your side is also welcome. Thanks!

FIX documentation about Notify only attributes that change

---

scripts/utils/delete_attribute_by_query.py

Delete attribute script

---

scripts/accumulator-server.py
src/lib/jsonParseV2/parseEntitiesResponse.cpp
src/lib/serviceRoutinesV2/postBatchQuery.cpp
test/functionalTest/cases/3068_ngsi_v2_based_forwarding/query_cpr_fail_but_local_results.test

No need of CNR modifications (#3068 is already mentioned in it)

FIX NGSIv2 forwarding minor bug

---

src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/ngsi/StringList.cpp
src/lib/ngsi/StringList.h
src/lib/ngsi10/QueryContextRequest.cpp
src/lib/ngsi10/QueryContextRequest.h
test/functionalTest/cases/3068_ngsi_v2_based_forwarding/check_no_overquerying.test

This is a bugfix for #3068 (which is already mentioned in CNR)

FIX over-querying bug in NGSIv2 forwarding

---

src/lib/mongoBackend/mongoConnectionPool.cpp

Fix error message when connection to database fails.

---

src/lib/jsonParseV2/parseEntitiesResponse.cpp
src/lib/logMsg/traceLevels.h
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutines/postUpdateContext.cpp

Now that release 2.3 is close to be released, it's time to remove debug traces.

Cleanup of debug log traces

---

README.md

I have just updated slideshare introductory presentations for Japanese. It would be great if you could review this PR.

(JP) FIX update slideshare introductoroy presentations (#3563)

---

doc/manuals.jp/admin/cli.md

I have just updated cli.md in doc/manuals.jp/admin. It would be great if you could review this PR.

(JP) FIX typo in doc (#3565)

---

doc/manuals/user/walkthrough_apiv2.md
test/functionalTest/README.md

Feedback from @WyRe is welcome.

FIX accumulator-server.py python requirements

---

doc/manuals.jp/user/walkthrough_apiv2.md

Hi @fgalan,
I have just updated  walkthrough_apiv2.md in manuals.jp. It would be great if you could review this PR.
Thank you.

(JP) FIX accumulator-server.py python requirements (#3572)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp

FIX avoid crash in the unrare case MongoDB get databases operations fails in csubs cache refresh logic

---

README.md
scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3393

Happy New Year 2020

---

doc/manuals/user/ngsiv2_implementation_notes.md

Related issue #3586
It would be great @gboege could have a look to this PR provide feedback or "LGTM" in the case you find it ok and ready to be merged. Thanks!

FIX implementation notes regarding supported geo:json types

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR updates ngsiv2_implementation_notes.md in doc/manuals.jp.

(JP) FIX implementation notes regarding supported geo:json types #3587

---

CHANGES_NEXT_RELEASE
doc/manuals/user/forbidden_characters.md
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/common/globals.h
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/3550_text_unrestricted/text_unrestricted.test

ADD TextUnrestricted attribute type to avoid forbidden chars checking

---

doc/manuals.jp/admin/database_admin.md
doc/manuals.jp/deprecated.md
doc/manuals.jp/devel/flowsIndex.md
doc/manuals.jp/devel/mongoBackend.md
doc/manuals.jp/user/multitenancy.md

This PR updates some Japanese documents about `casubs`.

(JP) Update Japanese Documentation

---

docker/README.jp.md

This PR updates docker/README.jp.md.

(JP) Add database index optimization statement. #3594

---

src/lib/rest/HttpHeaders.h
src/lib/rest/rest.cpp

This PR removes some headers processing logic that after the analysis/discussion with @ArqumFarooqui-NEC in PR https://github.com/telefonicaid/fiware-orion/pull/3576
Please, @ArqumFarooqui-NEC have a look to check if the removal is fine. Provide LGTM in positive case or feedback comment if you find something wrong. Thanks

REMOVE unnedeed header processing logic

---

test/functionalTest/cases/0000_large_requests/notification_different_sizes.test

This PR updates REGEX value about message 2 and 3.

Update REGEX value about message 2 and 3

---

test/functionalTest/cases/0000_large_requests/notification_different_sizes.test

Related with https://github.com/telefonicaid/fiware-orion/issues/3623, just testing
CC: @fisuda

FIX more precise REGEX() in .test

---

doc/roadmap.md

Roadmap upgrade

---

doc/manuals.jp/user/known_limitations.md

This PR adds documentation of Maximum nesting level in doc/manuals.jp/user/known_limitations.md.

(JP) Add documentation of Maximum nesting level. (#3615)

---

README.md

This PR updates links to new presentations.

(JP) FIX new presentations preparing Orion 2.4.0 (#3644)

---

doc/manuals/admin/cli.md

The docs part for PR https://github.com/telefonicaid/fiware-orion/pull/3658

ADD doc for env vars

---

doc/manuals.jp/admin/cli.md

This PR adds documentation for env vars in doc/manuals.jp/admin/cli.md.

(JP) ADD doc for env vars (#3659)

---

doc/apiary/v2/fiware-ngsiv2-2.0-2018_09_15.apib
doc/apiary/v2/fiware-ngsiv2-2.0.1-wip.apib

Included the section for Special Metadata Types for issue #3434

Special Metadata Types section is added

---

rpm/SOURCES/etc/tmpfiles.d/contextBroker.conf

We missed this in PR #3669 ...

ADD missing licence header

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp

Fixed for WARN about insecureNotifications mode

---

doc/manuals.jp/contribution_guidelines.md

This PR updates contribution_guidelines.md in doc/manuals.jp.

(JP) Updated document for issue #2791 #3685

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseStringVector.cpp
test/functionalTest/cases/3468_v2_registrations_attribute_name_with_forbidden_character/attribute_name_with_forbidden_character.test

fix Issue3468

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/location.cpp
test/functionalTest/cases/3706_incorrect_location_processing/incorrect_location_processing.test

FIX wrong 413 error when passing from 0 locations to 1 in entity update

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

Last step preparing the releasing of Orion 2.5.0

Update links to docs and version references to 2.5.0

---

doc/manuals.jp/admin/sanity_check.md
doc/manuals/admin/sanity_check.md
docker/docker_swarm.jp.md
docker/docker_swarm.md
src/lib/serviceRoutines/versionTreat.cpp
test/functionalTest/cases/0000_ipv6_support/ipv4_ipv6_both.test
test/functionalTest/cases/0000_large_requests/notification_different_sizes.test
test/functionalTest/cases/0000_version_operation/version_via_rest.test
test/functionalTest/cases/0501_cors/version_request.test
test/functionalTest/cases/1916_fiware_correlator/fiware_correlator.test
test/unittests/serviceRoutines/versionTreat_test.cpp

Continues and finished the work started by @Anjali-NEC in PR https://github.com/telefonicaid/fiware-orion/pull/3709/

ADD mongodriver version to GET /version info and some other minor fixes

---

README.md

This PR updates links to new presentations.

(JP) Update links to docs (#3712)

---

doc/manuals/admin/cli.md
doc/manuals/admin/perf_tuning.md

Fix for the documentation showing a wrong mode for the notificationMode parameter. #3716

Fix for the issue #3716

---

CHANGES_NEXT_RELEASE
ci/rpm7/Dockerfile
docker/Dockerfile

Based on feedback by FIWARE Foundation
CC: @flopezag

FIX upgrade Dockefiles base image to centos7.9.2009

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp

FIX crash on MHD_REQUEST_TERMINATED_CLIENT_ABORT situations

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp

Twin PR of #3739 for release/2.5.0

FIX crash on MHD_REQUEST_TERMINATED_CLIENT_ABORT situations (for release/2.5.0)

---

src/lib/rest/rest.cpp

REFACTOR requestCompleted() logic

---

README.md
scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3585

Happy New Year 2021

---

.github/workflows/ciimage.yml
.github/workflows/publishimage.yml
ci/rpm7/Dockerfile

Fixes the error from https://github.com/telefonicaid/fiware-orion/pull/3747 by setting the correct build context.

fix failing ci-image build

---

doc/manuals.jp/admin/database_model.md
doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR adds Japanease documentation about supportedForwardingMode.

(JP) Add documentation about supportedForwardingMode (#3753)

---

.github/workflows/publishimage.yml
.github/workflows/unit.yml
ci/README.md
ci/rpm7/build.sh
scripts/check_files_compliance.py
test/functionalTest/cases/3658_env_vars/env_vars.test

Improve comment to make clearer which builds are out of the scope of publishimage.yml
@wistefan what do you think?

FIX comment in publishimage.yml

---

doc/manuals.jp/deprecated.md
doc/manuals.jp/devel/mongoBackend.md

This PR fixes Japanese devel manual fixes related with casubs removal.

(JP) FIX devel manual fixes related with casubs removal

---

README.md
doc/manuals/admin/install.md
doc/manuals/admin/perf_tuning.md

We got feedback from the community about low performance of orion. After further enquire, we found out that most of them did not know about the performance tuning and ha section of the documentation. In order to get it more visible, I would propose those changes in the documentation.
In additon, we found out that setting an index to _id.id improves the performance of updates by multiples. Therefore I would also like to add it into the performance tuning section.

Improve documentation

---

doc/manuals/contribution_guidelines.md

Update contribution_guidelines.md file

---

README.md

Added CII badge to README file

Update README.md with CII Best Practices badge

---

src/lib/apiTypesV2/EntityVector.cpp
test/functionalTest/cases/2596_retrieve_entity_without_attrs/retrieve_entity_without_attrs.test
test/functionalTest/cases/2604_op_query_attrs/op_query_attrs.test
test/functionalTest/cases/3777_right_attr_filter_and_project/right_attr_filter_and_project.test

FIX spurious entities rendering removal

---

docker/Dockerfile

Dockerfile modified
- Updated CentOS image tag to `centos8.3.2011`
- Removed Scons installation
- Using C mongo driver

Dockerfile modified supporting Centos8

---

.github/workflows/functional.yml
.github/workflows/unit.yml
ci/rpm8/mongodb.repo
doc/manuals/admin/build_source.md
doc/manuals/admin/install.md
doc/manuals/admin/perf_tuning.md
docker/README.jp.md
docker/README.md
docker/docker-compose.yml
docker/docker_swarm.jp.md
docker/docker_swarm.md
docker/raspberry_pi.jp.md
docker/raspberry_pi.md

(This PR is one of the stages of the bigger PR #3622)
Migrated from PR https://github.com/telefonicaid/fiware-orion/pull/3732

UPGRADE MongoDB recomendation from 3.6 to 4.4

---

src/app/contextBroker/contextBroker.cpp
src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/senderThread.cpp
src/lib/rest/httpRequestSend.cpp
test/functionalTest/cases/1156_mq_as_uri_param_for_metadata/mq_as_uri_param_for_metadata_nocache.test
test/functionalTest/cases/1960_failure_stats_in_db_and_notifications/failure_stats_in_db_and_notifications_stop_start_accumulator.test

A couple of hardening fixes. Details in inline comments in the PR.

Hardening ftest

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/3712

FIX update links to docs and version references

---

README.md

This PR updates links to new Japanese presentations.

(JP) Update links to docs (#3800)

---

doc/manuals.jp/contribution_guidelines.md
doc/manuals/contribution_guidelines.md

Updated contribution_guidelines.md and  japanese version of contribution_guidelines.md file

Update FIWARE Contribution Requirements broken link

---

test/functionalTest/cases/1697_more_than_one_bad_input/more_than_one_bad_input.test

Issue https://github.com/telefonicaid/fiware-orion/issues/3828

FIX make more_than_one_bad_input.test stronger

---

CHANGES_NEXT_RELEASE
README.md
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h
src/lib/common/defaultValues.h

Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3744

Step: 2.6.0 -> 2.6.1

---

src/lib/apiTypesV2/Entity.cpp

Due to this it seems that valgrind regression is reporting some errors.

FIX avoid unitialized creDate and modDate

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp

This PR is pending on PR #3622 . Once that PR gets merged, this PR will be rebased to master.
Fixes #3821

FIX createEntity logic to take into account duplication and upsert

---

README.md

This PR updates links to new Japanese presentations. It would be great if you could review the PR.

(JP) Update links to docs (#3835)

---

.github/workflows/publishimage.yml

See https://github.com/wistefan/fiware-orion/runs/2330445868?check_suite_focus=true#step:6:14 for a successful run. The incrementation needs to be prefix in cases of 0.

Fix version increment for minor==0

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Entity.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/compoundResponses.cpp
src/lib/mongoBackend/compoundValueBson.cpp
src/lib/mongoBackend/dbFieldEncoding.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/Metadata.cpp
src/lib/ngsi/MetadataVector.cpp
src/lib/rest/StringFilter.cpp
test/functionalTest/cases/3841_attributes_and_metadata_starting_with_dollar/attributes_and_metadata_starting_with_dollar.test
test/functionalTest/cases/3841_attributes_and_metadata_starting_with_dollar/attributes_and_metadata_starting_with_dollar_subscriptions.test

FIX support attributes and metadata starting with dollar sign

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/jsonParseV2/parseMetadata.cpp
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/1920_geojson/errors_geojson.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_attr.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_attr_ignored_by_filters.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_attr_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_md.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_md_ignored_by_filters.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_md_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_box.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_box_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_json.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_json_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_line.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_line_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_more_than_one.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_point.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_point_subs.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_polygon.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_polygon_subs.test

Issue https://github.com/telefonicaid/fiware-orion/issues/3533
Test cases / tasks:

ADD null support to DateTime attrs and mds and geo:xxxx attrs

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR adds Japanese documentation about supporting to DateTime attrs and mds and geo:xxxx attrs.

(JP) Update documentation (#3846)

---

doc/manuals/admin/statistics.md

Doc modification corresponding to #3805

FIX counters example in doc

---

doc/manuals.jp/admin/statistics.md

This PR updates Japanese documentation about counters example.

(JP) FIX counters example in doc (#3856)

---

src/lib/serviceRoutines/postQueryContext.cpp

Mem leak recently introduced in PR https://github.com/telefonicaid/fiware-orion/pull/3852

FIX mem leak in CPr forwarding logic

---

README.md

This PR updates links to new Japanese presentations for Orion 3.1.0. It would be great if you could review the PR.

(JP) Update links to docs (#3871)

---

src/app/contextBroker/contextBroker.cpp
src/lib/mongoDriver/mongoConnectionPool.cpp
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueWorkers.cpp
test/functionalTest/cases/3843_per_service_notif_queue/default_service_notif_queue.test
test/functionalTest/cases/3843_per_service_notif_queue/per_service_notif_queue.test
test/functionalTest/cases/3843_per_service_notif_queue/per_service_notif_queue_full_queues.test

Fixes in how the release logic for service queues works. Additional tests added to improve coverage of #3843 feature

FIX issues in service queues implementation after valgrind testing

---

ci/rpm8/build-dep.sh

Same as PR #3878 but for the CI Docker image

FIX CI image

---

CHANGES_NEXT_RELEASE
src/lib/common/SyncQOverflow.h
src/lib/logMsg/traceLevels.h
src/lib/ngsiNotify/Notifier.cpp
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/senderThread.h

FIX Improve notification pool worker thread termination logic

---

doc/manuals/user/ngsiv2_implementation_notes.md

fix typo ngsiv2_implementation_notes.md

---

doc/manuals/admin/database_model.md

Attempting to fix this rendering problem in RTD:

FIX typo in docu

---

doc/manuals/admin/logs.md
scripts/accumulator-server.py
src/lib/common/logTracing.cpp
src/lib/common/logTracing.h
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/logMsg/traceLevels.h
src/lib/mqtt/mqtt.cpp
src/lib/mqtt/mqtt.h
src/lib/ngsiNotify/Notifier.cpp
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/senderThread.cpp
src/lib/ngsiNotify/senderThread.h
src/lib/rest/httpRequestSend.cpp
test/functionalTest/cases/3001_mqtt/mqtt_notification.test
test/functionalTest/cases/3001_mqtt/mqtt_notification_custom.test
test/functionalTest/cases/3001_mqtt/mqtt_notification_qos.test

Part of PR #3888
MQTT notification finished (both custom and non-custom) in mono-MQTTbroker case

MQTT notificationss mono-MQTTbroker

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp
test/functionalTest/cases/0117_convop_using_standard_ops/deleteIndividualContextEntityAttribute.test
test/functionalTest/cases/3071_DELETE_with_wrong_servicepath/3071_DELETE_operation_with_wrong_servicepath.test

Fix status code for DELETE operation when 'multiple ServicePath' or 'ServicePath with wildcard #' is used (issue #3071).

Fix status code for DELETE operation when 'multiple ServicePath' or 'ServicePath with wildcard #' is used

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoSubCache.cpp
test/functionalTest/cases/3906_onlychangedattrs_not_working_with_csub_cache/onlychangedattrs_not_working_with_csub_cache.test

FIX onlyChangedAttrs set to true not working after csubs cache refresh

---

src/lib/jsonParseV2/parseSubscription.cpp
src/lib/parse/forbiddenChars.cpp
src/lib/parse/forbiddenChars.h
test/functionalTest/cases/3001_mqtt/mqtt_subscription_parsing_errors.test

FIX mqtt topic parsing logic

---

CHANGES_NEXT_RELEASE
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/3867_textUnrestricted_should_be_recursively_applied_to_JSON_objects_and_array/textUnrestricted_should_be_recursively_applied_to_JSON_objects_and_array.test

FIX TextUnrestricted recursively applies to JSON objects and array

---

src/app/contextBroker/contextBroker.cpp
src/lib/serviceRoutines/exitTreat.cpp
test/functionalTest/harnessFunctions.sh

FIX avoid valgrind false positives in modern OS

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/3871

FIX links and version numbers to prepare 3.2.0

---

README.md

This PR updates links to new Japanese presentations for Orion 3.2.0.
It would be great if you could review the PR.

(JP) Update links to docs

---

CHANGES_NEXT_RELEASE
ci/rpm8/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/Dockerfile

@fisuda I have touched some files belonging to the Japanese translation, but only numbers, so I think they are fine.

FIX upgrade libmosquitto to 2.0.12

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Registration.cpp
src/lib/mongoBackend/mongoRegistrationGet.cpp
test/functionalTest/cases/3106_supported_forwarding_mode/supported_forwarding_mode_basic_crud.test
test/functionalTest/cases/3944_legacy_forwarding_rendering/legacy_forwarding_rendering.test

Fix legacyForwarding rendering in GET /v2/registrations and GET /v2/registrations/{regId} calls

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoGetSubscriptions.h
src/lib/mongoBackend/mongoRegistrationGet.cpp
src/lib/serviceRoutinesV2/getSubscription.cpp
test/functionalTest/cases/3945_servicepath_ignored_in_get_regs/servicepath_ignored_in_get_regs.test
test/functionalTest/cases/3945_servicepath_ignored_in_get_subs/servicepath_ignored_in_get_subs.test

FIX service path ignored in regs and subs

---

CHANGES_NEXT_RELEASE
src/lib/common/errorMessages.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoCommonUpdate.h
test/functionalTest/cases/3949_upsert_with_wrong_geojson/upsert_with_wrong_geojson.test

FIX upsert with wrong geojson

---

src/lib/jsonParseV2/badInput.cpp
src/lib/jsonParseV2/parseAttributeValue.cpp
src/lib/jsonParseV2/parseBatchQuery.cpp
src/lib/jsonParseV2/parseBatchUpdate.cpp
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/jsonParseV2/parseEntity.cpp
src/lib/jsonParseV2/parseNotification.cpp
src/lib/jsonParseV2/parseRegistration.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/dateExpiration.cpp
src/lib/mongoBackend/location.cpp
src/lib/mongoBackend/mongoUnsubscribeContext.cpp
src/lib/mongoBackend/mongoUpdateContext.cpp
src/lib/rest/RestService.cpp
src/lib/serviceRoutinesV2/getEntities.cpp
src/lib/serviceRoutinesV2/getSubscription.cpp
src/lib/serviceRoutinesV2/postEntities.cpp
src/lib/serviceRoutinesV2/putEntityAttributeValue.cpp

Not all of them has been fixed, but a lot of them.

FIX avoid usage of magic strings

---

test/functionalTest/README.md

Add how to use paths to execute an specific tests and some env var usage examples for `testHarness.sh` file

Update funtionalTest Readme

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3956_delete_attribute_notif_fail/delete_attribute_notif_fail.test

FIX deleted attributes incorrectly included in notifications 

---

CHANGES_NEXT_RELEASE
doc/manuals/user/update_operators.md
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoDriver/connectionOperations.cpp
src/lib/mongoDriver/connectionOperations.h
test/functionalTest/cases/3814_attribute_update_operators/addtoset_operator.test
test/functionalTest/cases/3814_attribute_update_operators/creating_entity_with_operators.test
test/functionalTest/cases/3814_attribute_update_operators/inc_operator.test
test/functionalTest/cases/3814_attribute_update_operators/max_operator.test
test/functionalTest/cases/3814_attribute_update_operators/min_operator.test
test/functionalTest/cases/3814_attribute_update_operators/mul_operator.test
test/functionalTest/cases/3814_attribute_update_operators/pull_operator.test
test/functionalTest/cases/3814_attribute_update_operators/pullall_operator.test
test/functionalTest/cases/3814_attribute_update_operators/push_operator.test
test/functionalTest/cases/3814_attribute_update_operators/replace_entity_with_operators.test
test/functionalTest/cases/3814_attribute_update_operators/several_operators_same_update.test

FIX update operators notification support

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3995_empty_object_and_array_crash/empty_array_crash.test
test/functionalTest/cases/3995_empty_object_and_array_crash/empty_object_crash.test

Fix issue #3995 for master branch

FIX crash when updating attribute with empty JSON Object

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3995_empty_object_and_array_crash/empty_array_crash.test
test/functionalTest/cases/3995_empty_object_and_array_crash/empty_object_crash.test

Fix issue #3995 for release/3.3.0 branch

FIX crash when updating attribute with empty JSON Object (release/3.3.0)

---

doc/manuals/admin/database_model.md
doc/manuals/user/ngsiv2_implementation_notes.md

FIX documentation related with failsCounter and maxFailsLimit

---

CHANGES_NEXT_RELEASE
README.md
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h
src/lib/common/defaultValues.h

Mimics commit https://github.com/telefonicaid/fiware-orion/commit/c0c59507beb76b6afd8d2aec4f5e268675ace113

Step: 3.3.0 -> 3.3.1

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
doc/manuals/user/mqtt_notifications.md
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/apiTypesV2/Subscription.cpp
test/functionalTest/cases/1048_subscription_cache/get_subscription_before_and_after_cache_refresh.test
test/functionalTest/cases/1048_subscription_cache/get_subscription_before_and_after_cache_refresh_status_in_db_older.test
test/functionalTest/cases/1048_subscription_cache/refresh_cache_wins_notif_fail.test
test/functionalTest/cases/1048_subscription_cache/refresh_cache_wins_notif_fail_with_update_in_the_middle.test
test/functionalTest/cases/1048_subscription_cache/refresh_db_wins_notif_disabled.test
test/functionalTest/cases/1048_subscription_cache/refresh_db_wins_notif_disabled_with_update_in_the_middle.test
test/functionalTest/cases/1048_subscription_cache/refresh_db_wins_notif_fail.test
test/functionalTest/cases/1048_subscription_cache/refresh_db_wins_notif_fail_with_update_in_the_middle.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test
test/functionalTest/cases/1126_GET_v2_subscriptions/lastsuccesscode_and_lastfailurereason.test
test/functionalTest/cases/1126_GET_v2_subscriptions/sub_from_active_to_fail.test
test/functionalTest/cases/1126_GET_v2_subscriptions/sub_from_fail_to_active.test
test/functionalTest/cases/1960_failure_stats_in_db_and_notifications/failure_stats_in_db_and_notifications.test
test/functionalTest/cases/1960_failure_stats_in_db_and_notifications/failure_stats_in_db_and_notifications_stop_start_accumulator.test
test/functionalTest/cases/3001_mqtt_alarms/mqtt_alarms_raise_and_release.test
test/functionalTest/cases/3001_mqtt_alarms/mqtt_alarms_raise_repeat_and_release.test
test/functionalTest/cases/3541_subscription_max_fails_limit/failsCounter_keeps_after_cache_refresh_cycles.test
test/functionalTest/cases/3541_subscription_max_fails_limit/maxfailslimit_failing_from_the_beginning.test
test/functionalTest/cases/3541_subscription_max_fails_limit/maxfailslimit_full_lifecycle.test
test/functionalTest/cases/3541_subscription_max_fails_limit/subscription_passes_to_inactive_state_after_limit_of_failed_connection_attemps.test
test/functionalTest/cases/3541_subscription_max_fails_limit/subscription_status_set_to_active_state_after_a_failsCounter_reset.test
test/functionalTest/cases/3541_subscription_max_fails_limit/subscription_without_maxfailslimit_and_failscounter.test
test/functionalTest/cases/3842_per_sub_httpTimeout/per_sub_httpTimeout_notification.test
test/functionalTest/cases/3842_per_sub_httpTimeout/per_sub_httpTimeout_notification_custom.test

REMOVE status failed in csubs

---

.github/workflows/functional.yml

This PR is bases in the solution provided at https://stackoverflow.com/a/70184677/1485926

Short names for GitActions functional jobs

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Fixes some errors detected by vavlgrind:
```
2 test cases show valgrind errors:
1231: set_and_unset_same_time shows 12 valgrind errors
1237: set_operator_non_object shows 6 valgrind errors
```

FIX update operators logic

---

test/functionalTest/cases/4012_https_cert_size/4012_https_cert_size.test
test/functionalTest/httpsPrepare.sh

Modified the httpsPrepare script to accept the size of the cert file as a parameter AND added a functest with a cert size of 2350

fixes for issue 4012

---

README.md
scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Happy New Year 2022

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR adds Japanese documentation about header removal in custom notifications.

(JP) Add doc about header removal in custom notifications (#4031)

---

src/lib/common/limits.h
src/lib/common/logTracing.cpp
src/lib/logMsg/logMsg.h
test/functionalTest/cases/3884_ip_len_in_logs/ip_len_in_logs.test

Fixed the <none> issue in the log file. Possibly fixing the real problem at the same time.
I say "possibly", as I was unable to reproduce the crash.
Supposedly the crash was due to the issue that I just fixed, so, I'm gonna need some help to test this, in some env where the crash occurs, using this branch, and see if the crash goes away.
@jason-fox , you are able to reproduce, right?
Also, the entry in CNR is missing. Not sure this fixes the problem yet so ...
Don't think any docs need update for this.

Possibly fixed the issue #3884

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4018

FIX links to reference presentations and version numbers

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/common/errorMessages.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/Metadata.h
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_general.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geobox.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geoline.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geopoint.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geopolygon.test
test/functionalTest/cases/1920_geojson/errors_geojson.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_more_than_one.test
test/functionalTest/cases/4032_extra_locs/extra_locs.test

ADD ignoreType (for extra locs) metadata feature

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md
doc/manuals/user/ngsiv2_implementation_notes.md

This PR adds Japanese documentation about ignoreType metadata feature.
Thanks

(JP) Add doc about ignoreType metadata feature (#4051)

---

doc/manuals.jp/admin/build_source.md
doc/manuals.jp/user/walkthrough_apiv2.md
docker/README.jp.md

This PR updates Japanese documentation about accumulator-server.py.
Thanks.

(JP) Update docs about accumulator-server.py (#4059)

---

doc/manuals.jp/user/metadata.md
doc/manuals.jp/user/ngsiv2_implementation_notes.md
doc/manuals/user/metadata.md
doc/manuals/user/ngsiv2_implementation_notes.md

This PR updates Japanese documentation about updating metadata.
Thanks.

(JP) Update docs about updating metadata (#4055)

---

CHANGES_NEXT_RELEASE
doc/manuals/user/forbidden_characters.md
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4071_custom_notif_header_decode/custom_notif_header_decode.test

ADD URL decode in header values in custom notification

---

doc/manuals.jp/user/walkthrough_apiv2.md
test/functionalTest/README.jp.md

This PR adds Japanese documentation about dockerized accumulator server.
Thanks!

(JP) ADD documentation about dockerized accumulator server (#4081)

---

doc/roadmap.md

This PR updates the Roadmap, deleting completed features, moving some of them and adding new ones.
After merging this PR, the idea is to add a list containing all the features merged in the past in the component.

Update roadmap March 2022

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
doc/manuals/user/subscriptions_alttype.md
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
test/functionalTest/cases/1494_subscription_alteration_types/alterationType_ignored_in_queries.test
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_change.test
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_create.test
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_delete.test
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_update.test

ADD alterationType build-in implementation

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md
doc/manuals.jp/user/subscriptions_alttype.md

This PR adds Japanese documentation about alterationType. It would be great if you could review this PR. Thanks.

(JP) Add documentation about alterationType (#4091)

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Introduced in PR https://github.com/telefonicaid/fiware-orion/pull/4084

REMOVE leftover debug trace

---

test/functionalTest/cases/1492_limit_zero/count_out_of_offset.test

Arisen while working in PR #4104

ADD cases/1492_limit_zero/count_out_of_offset.test

---

.github/workflows/functional.yml
.github/workflows/unit.yml

To avoid wasting time when new commits arrive in existing PR

ADD concurrencly group to CI

---

CHANGES_NEXT_RELEASE
src/lib/rest/StringFilter.cpp
src/lib/rest/StringFilter.h
test/functionalTest/cases/4120_string_and_null_mixed_filter/string_and_null_mixed_filter.test
test/functionalTest/cases/4120_string_and_null_mixed_filter/sub_string_and_null_mixed_filter.test

ADD support to null element in string list filters

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md
doc/manuals/user/ngsiv2_implementation_notes.md

This PR adds Japanese documentation about Feature and Feature Collection support. It would be great if you could review this PR. Thanks.

(JP) Add doc about Feature and FeatureCollection support (#4126)

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR adds Japanese documentation  about ignoreType for Feature and FeatureCollection. It would be great if you could review this PR. Thanks.

(JP) Add doc about ignoreType for Feature and FeatureCollection (#4129)

---

CHANGES_NEXT_RELEASE
docker/Dockerfile

add docker healthcheck based on API /version

---

doc/manuals/orion-api.md

This PR is intended to reorder the sections inside each API operation, having the following sections inside each request:
- Request Query Parameters
- Request URL Parameters
- Request Payload
- Response

Reorder operations sections + some capitalization and rendering fixes

---

CHANGES_NEXT_RELEASE

It was misssed in PR https://github.com/telefonicaid/fiware-orion/pull/4030

ADD misssing entry to CNR

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/common/macroSubstitute.cpp
src/lib/common/macroSubstitute.h
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_http_json.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_http_json_attr_override.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_http_text.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_http_text_attr_override.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_json.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_json_attr_override.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_text.test
test/functionalTest/cases/4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_text_attr_override.test
test/unittests/common/commonMacroSubstitute_test.cpp

ADD service, servicePath and authToken macros to custom notifications

---

doc/manuals.jp/admin/perf_tuning.md

This PR adds additional index recommendations. It would be great if you could review this PR. Thanks.

(JP) ADD additional index recommendations (#4170)

---

doc/manuals/orion-api.md

 Review all the request sections (except batch operations) 

---

doc/manuals/orion-api.md

This PR is part of a bigger series #4141

Rework batch operations

---

doc/manuals/orion-api.md

This PR is part of a bigger series #4141

Fix links between sections (II)

---

doc/manuals/user/ngsiv2_implementation_notes.md
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_update_forced.test

Comes from: https://github.com/telefonicaid/fiware-orion/pull/4172#issuecomment-1184580276

ADD sub_alteration_type_entity_update_forced.test and side documentation

---

CHANGES_NEXT_RELEASE
src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_update2.test

Comes from https://github.com/telefonicaid/fiware-orion/issues/1494#issuecomment-1181656637
CC: @djs0109

ADD sub_alteration_type_entity_update2.test extra case

---

doc/manuals/orion-api.md

FIX update operator examples

---

doc/manuals/orion-api.md

Fixes issue https://github.com/telefonicaid/fiware-orion/issues/4178

FIX forcedUpdate right reference to alteration type

---

doc/manuals/orion-api.md

FIX get types documentation

---

test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_update2.test
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_update_forced.test

Small fix. Surprisingly, with no effect...

FIX payload in tests

---

doc/manuals/admin/database_model.md
doc/manuals/orion-api.md

* Changes in the API route titles
* Sub-divide Custom Notification section (it was pretty large)

orion-api.md final? fixes

---

mkdocs.yml

Little syntax error introduced by PR #4141 just merged

FIX mkdocs.yml sintax error

---

doc/manuals/orion-api.md

Fix link (they were not correct in PR #4141)

FIX links doc/manuals/orion-api.md

---

doc/manuals.jp/orion-api.md

This PR updates doc/manuals.jp/orion-api.md. It would be great if you could review this PR. Thanks.

(JP) FIX docu examples (#4220)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp

Replacing the $where operator by $expr

---

src/lib/apiTypesV2/Entity.cpp
src/lib/apiTypesV2/Entity.h
src/lib/apiTypesV2/EntityVector.cpp
src/lib/apiTypesV2/EntityVector.h
src/lib/ngsi10/UpdateContextRequest.cpp
src/lib/serviceRoutines/postUpdateContext.cpp

CHANGES_NEXT_RELEASE entry doesn't needed (it's a small refactor with no impact on functionality)
I plan to use some of these new toJson() in the conext of issue #4085

FIX add some simpler toJson() renders

---

doc/manuals.jp/orion-api.md

This PR fixes missing information in Japanese documentation about json field in subs. It would be great if you could review this PR. Thanks.

(JP) FIX missing information in documentation about json field in subs (#4231)

---

test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_change_attr_type.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_change_attr_type.test

ADD ngsi test cases for change attr type

---

src/lib/common/JsonHelper.h
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoGetSubscriptions.h
src/lib/serviceRoutinesV2/getAllSubscriptions.cpp
test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_basic_crud.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_basic_crud.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_basic_crud.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_basic_crud.test

Fix a crash introduce by PR #4085 implementation

  FIX crash in get all subscriptions operation 

---

CHANGES_NEXT_RELEASE
src/lib/common/statistics.cpp
src/lib/serviceRoutines/statisticsTreat.cpp

FIX statistics API

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/getRegistration.cpp
test/functionalTest/cases/3008_get_registration/get_reg_using_v2_created_using_v2.test
test/functionalTest/cases/3945_servicepath_ignored_in_get_regs/servicepath_ignored_in_get_regs.test
test/functionalTest/cases/4235_wrong_response_code_not_found_reg/wrong_response_code_not_found_reg.test

FIX wrong responde code for not found registration

---

README.md

This PR updates links to new Japanese presentations for Orion 3.8.0. It would be great if you could review this PR.
Thanks.

(JP) Update links to docs (#4255)

---

doc/manuals.jp/admin/statistics.md

This PR add Japanese documentation about statistics API. It would be great if you could review this PR. Thanks.

(JP) ADD doc about statistics API (#4254)

---

src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4263_json_value_lost_in_custom_sub/json_value_lost_in_custom_sub.test

Fixes #4263
No need of CNR entry, given that the bug doesn't exist in Orion 3.7.0

FIX compound attribute stealing in custom notifications 

---

README.md
scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4036

Happy New Year 2023

---

CHANGES_NEXT_RELEASE
CMakeLists.txt
ci/deb/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/Dockerfile
docker/Dockerfile.alpine
src/lib/rest/rest.cpp

Try a naïve upgrade just before 3.8.0 CB releasing.

FIX upgrade libmicrotthpd, libmosquitto and libmongoc libraries to newest versions

---

test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_trigger_after_update.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_trigger_after_update.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_unbalanced_macros_does_not_work.test

Discovered upon releasing 3.8.0

FIX user-agent headers in ftest

---

CHANGES_NEXT_RELEASE
Changelog
README.md
src/app/contextBroker/version.h
src/lib/common/defaultValues.h

Mimics (showhow) PR https://github.com/telefonicaid/fiware-orion/pull/4002

Step: 3.8.0 -> 3.8.1

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation  about Ngsiv2-AttrsFormat header in NGSI patching custom notification. It would be great, if you could review the PR. Thanks!

(JP) ADD doc about Ngsiv2-AttrsFormat header in NGSI patching custom notification (#4277)

---

doc/manuals.jp/admin/cli.md
doc/manuals.jp/admin/diagnosis.md
doc/manuals/admin/diagnosis.md

This PR adds Japanese documentation about MQTT timeout. It would be great if you could review the PR. Thanks.

(JP) ADD doc about MQTT timeout (#4278)

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
test/functionalTest/cases/3658_env_vars/env_vars.test

Fix allowing ports while starting Orion issue #3875

Fix allowing ports while starting Orion issue#3875

---

doc/manuals.jp/admin/cli.md
doc/manuals.jp/admin/management_api.md

This PR add Japanese documentation about LogConfig. It would be great if you could review the PR. Thanks.

(JP) ADD documentation about LogConfig (#4289)

---

.github/workflows/compliance.yml
.github/workflows/functional.yml
.github/workflows/unit.yml
README.md

FIX change just for testing

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp

Fix to add check for db name too long at subCacheRefresh issue #2848

Fix db name too long at subCacheRefresh issue#2848

---

ci/README.jp.md
ci/README.md

This PR adds Japanese documentation about how to use the image locally. It would be great if you could review this PR. Thanks.

(JP) Add doc about how to use the image locally

---

test/functionalTest/cases/2064_attrs_blacklist_subs/blacklist_error.test

Comes from https://github.com/telefonicaid/fiware-orion/pull/4310#pullrequestreview-1400284823

ADD blacklist_error.test on case 2064

---

src/lib/ngsi10/NotifyContextRequest.cpp
src/lib/ngsiNotify/Notifier.cpp

Simplification upon PR https://github.com/telefonicaid/fiware-orion/pull/4298
CC: @Anjali-NEC

FIX simplify logic

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/4315_update_operators_with_dot/set_operator_with_dot.test
test/functionalTest/cases/4315_update_operators_with_dot/unset_operator_with_dot.test

FIX $set update operator not working properly with keys with dots

---

CHANGES_NEXT_RELEASE
doc/manuals.jp/orion-api.md
doc/manuals/orion-api.md
src/lib/cache/subCache.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/4325_entity_delete_alt_type_ignores_condition_attrs/4325_entity_delete_alt_type_ignores_condition_attrs.test

FIX alterationType with entityDelete not working if condition.attrs is empty

---

doc/manuals.jp/orion-api.md

This PR updates Japanese documentation about operator usage in create entity cases. It would be great if you could review the PR. Thanks.

(JP) Update doc about operator usage in create entity cases

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp
test/functionalTest/cases/4346_ensure_rounding_is_done_correctly/ensure_rounding_done_correctly.test

FIX decimal rounding in some cases was generating wrong JSON in query responses and notifications

---

doc/manuals.jp/deprecated.md

This PR updates Japanese documentation about NGSIv1 deprecated requests. It would be great if you could review the PR. Thanks.

(JP) Update doc about NGSIv1 deprecated requests (#4345)

---

src/lib/ngsi/ContextAttribute.cpp

Leftover recently introduced, in PR https://github.com/telefonicaid/fiware-orion/pull/4336

FIX lefover removal

---

src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/1041_GET_v2_entities_options_count/get_entities_option_count_multitenant.test

No CNR needed (this is a fix over PR https://github.com/telefonicaid/fiware-orion/pull/4355)

FIX count in multitenant cases

---

doc/manuals.jp/admin/cli.md
doc/manuals.jp/admin/logs.md
doc/manuals.jp/admin/management_api.md
doc/manuals.jp/deprecated.md
doc/manuals/admin/logs.md
doc/manuals/deprecated.md

This PR adds Japanese documentation about log deprecate configuration to management API. It would be great if you could review this PR. Thanks.

(JP) ADD doc about log deprecate configuration to management API (#4364)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/location.cpp

Backport of PR https://github.com/telefonicaid/fiware-orion/pull/4371 (for master)

FIX logDeprecate not working correctly (release/3.10.0)

---

CHANGES_NEXT_RELEASE
Changelog
README.md
src/app/contextBroker/version.h
src/lib/common/defaultValues.h

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4283

Step: 3.10.0 -> 3.10.1

---

doc/manuals/orion-api.md

Documentation corresponding to the PR #4329 
CC: @chetan-NEC

ADD servicePath builtin attr to orion-api.md

---

CHANGES_NEXT_RELEASE

Related with PR https://github.com/telefonicaid/fiware-orion/pull/4385
I'd say this fix is aligned with code/documentation. @ctc-nakatsuka could you confirm, please?

FIX CHANGES_NEXT_RELEASE

---

doc/manuals.jp/orion-api.md
doc/manuals/orion-api.md

This PR improves ordering results Japanese documentation in orion-api.md. It would be great if you could review this PR.
Thanks.

(JP) FIX improve ordering results documentation in orion-api.md (#4405)

---

test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_constant_attribute_compound.test

This may be causing some glitches (pe. https://github.com/telefonicaid/fiware-orion/actions/runs/6170605225/job/16747197999)

FIX missplace delay in test file

---

ci/deb/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
doc/manuals/user/walkthrough_apiv2.md
test/functionalTest/README.jp.md
test/functionalTest/README.md

Fix a problem that started to happen when Werkzeug 3.0.0 was released (September 30th, 2023). Explanation here: https://stackoverflow.com/a/77214086/1485926

FIX Flask dependency in CI

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about actionType delete. It would be great if you could review the PR.
Thanks.

(JP) ADD documentation about actionType delete (#4445)

---

doc/manuals/devel/cookbook.md

Fixes #3506 
Cookbook: The section "Adding a REST service" is updated

Cookbook: The section "Adding a REST service" is updated

---

doc/manuals.jp/devel/cookbook.md

This PR update the cookbook.md file in doc/manuals.jp/devel. It woud be great if you could review the PR.
Thanks.

(JP) Cookbook: The section "Adding a REST service" is updated

---

CHANGES_NEXT_RELEASE
src/lib/common/logTracing.cpp
test/functionalTest/cases/4454_false_positive_in_log_deprecation_logic/false_positive_in_log_deprecation_logic.test

FIX false positive in log deprecation logic when entity name (or other literal) includes the token v1

---

doc/manuals.jp/admin/logs.md

This PR updates the logs.md file in doc/manuals.jp/admin. It would be great if you could review the PR.
Thanks.

(JP) ADD notification payload in INFO log traces (#4456)

---

README.md
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4265

Happy New Year 2024

---

doc/manuals.jp/orion-api.md
doc/manuals/orion-api.md

This PR adds Japanese  documentation about PartialUpdates reporting in error responses. 
Thanks.

(JP) ADD doc about PartialUpdates reporting in error responses (#4447)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoQueryTypes.cpp
test/functionalTest/cases/4451_do_not_show_date_expires_in_get_types/do_not_show_date_expires_in_get_types.test

FIX do not show dateExpires built-in attribute in GET /v2/types and GET /v2/types/{type} operations

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4462_ngsi_patching_id_type_macro_always_stringfly/ngsi_patching_id_type_macro_always_stringfly.test

FIX NGSI patching macro subscription covering completely the string always cast to string for id/type

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about NGSI patching macro subscription. It would be great if you could review the PR. Thanks.

(JP) Add doc about NGSI patching macro subscription (#4468)

---

doc/manuals.jp/admin/diagnosis.md
doc/manuals.jp/orion-api.md
doc/manuals.jp/user/known_limitations.md

This PR adds Japanese documentation about OrionError field names. It would be great if you could review the PR. Thanks.

(JP) ADD doc about OrionError field names (#4465)

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3499_partial_update_response/batch_delete_removing_attrs_and_entity_in_same_request.test

Follow up of PR https://github.com/telefonicaid/fiware-orion/pull/4447

FIX batch delete logic

---

doc/manuals.jp/admin/logs.md
doc/manuals.jp/admin/statistics.md

This PR adds Japanese documentation about deprecatedFeatures counters. It would be great if you could review the PR. Thanks.

(JP) ADD deprecatedFeatures counters (#4476)

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/4499_subs_without_entities_return_error/sub_without_entities_return_error.test

Issue https://github.com/telefonicaid/fiware-orion/issues/4499

FIX return 400 Bad Request when subject.entities exists but it is an empty array

---

CHANGES_NEXT_RELEASE
scripts/utils/delete_attribute_by_query.py

updated attribute deleting script with python3 ( Issue #4509)

updated attribute deleting script with python3

---

CHANGES_NEXT_RELEASE
scripts/utils/delete_entities_by_list.py
scripts/utils/delete_entities_by_query.py

updated entity deleting script to python3 ( Issue #4507 )

updated entity deleting script to python3

---

scripts/notification_errors_tester.py
scripts/utils/check_entity_existence_by_list.py
scripts/utils/dump_entities_by_list.py
scripts/utils/get_coordinates.py
scripts/utils/populate_500bytes_entities_and_subs.py
scripts/utils/sth_periodic_update.py

updated below python scripts ( #4512 )
1. fiware-orion/scripts/notification_errors_tester.py
2. fiware-orion/scripts/utils/check_entity_existence_by_list.py
3. fiware-orion/scripts/utils/get_coordinates.py
4. fiware-orion/scripts/utils/sth_periodic_update.py
5. fiware-orion/scripts/utils/populate_500bytes_entities_and_subs.py
6. fiware-orion/scripts/utils/dump_entities_by_list.py

updated python utility scripts

---

doc/manuals/user/walkthrough_apiv2.md

Issue #4519 
CC: @ArqamFarooqui110719

FIX add comment about Python interpreter in walkthrough_apiv2.md

---

doc/manuals.jp/deprecated.md

This PR updates Japanese documentation in deprecated.md. It would be great if you could review the PR. Thanks.

(JP) REMOVE deprecated db related CLIs (#4527)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoDriver/mongoConnectionPool.cpp

Issue https://github.com/telefonicaid/fiware-orion/issues/4517
CC: @rg2011

ADD nameOnly to listDatabase command on MongoDB

---

doc/manuals.jp/admin/build_source.md
doc/manuals.jp/admin/statistics.md
doc/manuals.jp/devel/sourceCode.md
doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about JEXL expressions in custom notifications. It would be great if you could review this PR.
Thanks.

(JP) ADD documentation about JEXL expressions in custom notifications

---

CHANGES_NEXT_RELEASE
ci/deb/build.sh
doc/manuals/orion-api.md
docker/Dockerfile
docker/Dockerfile.alpine
test/functionalTest/cases/4004_jexl_expressions_in_subs/jexl_transformation_binary_map_accum.test
test/functionalTest/cases/4004_jexl_expressions_in_subs/jexl_transformation_full.test

ADD new transformations

---

README.md

This PR fixes to reference Japanese presentation. It would be great if you could review the PR.
Thanks.

(JP) FIX to reference presentation (#4566)

---

.github/workflows/publishimage-master.yml
.github/workflows/publishimage-tag.yml

Continues PR https://github.com/telefonicaid/fiware-orion/pull/4592

FIX image build gitactions

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/ngsi/Metadata.cpp
src/lib/ngsi/Metadata.h
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4594_metadata_in_jexl_context/metadata_in_jexl_context_basic.test
test/functionalTest/cases/4594_metadata_in_jexl_context/metadata_in_jexl_context_builtin.test
test/functionalTest/cases/4594_metadata_in_jexl_context/metadata_in_jexl_context_collision.test

ADD metadata in JEXL context

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4566

FIX to reference presentation and version numbers

---

README.md

This PR updates links to new Japanese presentation for Orion 4.1.0.
It would be great if you could review the PR.
Thanks.

(JP) Update links to presentation

---

CHANGES_NEXT_RELEASE
src/lib/common/globals.cpp

fix the typo in globals.cpp file at line#673 (Issue #4621 )

corrected the typo in globals.cpp file

---

doc/manuals.jp/orion-api.md

This PR adds new push cases in Japanese documentation. It would be great if you could review the PR.
Thanks.

(JP) FIX add new push cases in doc (#4627)

---

CHANGES_NEXT_RELEASE
CMakeLists.txt
ci/deb/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/Dockerfile
docker/Dockerfile.alpine

FIX upgrade dependencies

---

README.md
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Mimics PR https://github.com/telefonicaid/fiware-orion/pull/4464

Happy New Year 2025

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp
test/functionalTest/cases/4642_large_float_numbers/large_float_numbers.test

Issue https://github.com/telefonicaid/fiware-orion/issues/4642

FIX improve double2string function to cope with very large float numbers

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about unique mode in attrsFormat. It would be great if you could review the PR. Thanks.

(JP) Add documentation about unique mode

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about subscriptions based in alteration type. It would be great if you could review the PR. Thanks.

(JP) Add doc about subscriptions based in alteration type (#4648)

---

.github/workflows/functional.yml
.github/workflows/unit.yml
.github/workflows/valgrind-nocache.yml
.github/workflows/valgrind.yml
CHANGES_NEXT_RELEASE
ci/deb/build-dep.sh
doc/manuals/admin/build_source.md
doc/manuals/admin/install.md
doc/manuals/admin/perf_tuning.md
docker/README.md
docker/docker-compose.yml
docker/docker_swarm.md
docker/raspberry_pi.md

Similar to PR ~https://github.com/telefonicaid/fiware-orion/pull/4414~ https://github.com/telefonicaid/fiware-orion/pull/4332

MongoDB 8.0

---

CMakeLists.txt
src/lib/alarmMgr/CMakeLists.txt
src/lib/apiTypesV2/CMakeLists.txt
src/lib/cache/CMakeLists.txt
src/lib/common/CMakeLists.txt
src/lib/convenience/CMakeLists.txt
src/lib/expressions/CMakeLists.txt
src/lib/jsonParse/CMakeLists.txt
src/lib/jsonParseV2/CMakeLists.txt
src/lib/logMsg/CMakeLists.txt
src/lib/logSummary/CMakeLists.txt
src/lib/metricsMgr/CMakeLists.txt
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoDriver/CMakeLists.txt
src/lib/mqtt/CMakeLists.txt
src/lib/ngsi/CMakeLists.txt
src/lib/ngsi10/CMakeLists.txt
src/lib/ngsi9/CMakeLists.txt
src/lib/ngsiNotify/CMakeLists.txt
src/lib/orionTypes/CMakeLists.txt
src/lib/parse/CMakeLists.txt
src/lib/rest/CMakeLists.txt
src/lib/serviceRoutines/CMakeLists.txt
src/lib/serviceRoutinesV2/CMakeLists.txt

Due to this fail https://github.com/telefonicaid/fiware-orion/actions/runs/14195920214/job/39770907516?pr=4662

FIX incresase cmake minimum required version from 3.0 to 3.5

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/common/errorMessages.h
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/serviceRoutinesV2/getEntities.cpp
src/lib/serviceRoutinesV2/postBatchQuery.cpp
test/functionalTest/cases/4664_orderby_dup_attr/orderby_dup_attr.test
test/functionalTest/cases/4664_orderby_dup_attr/orderby_dup_attr_get.test
test/functionalTest/cases/4664_orderby_dup_attr/orderby_dup_attr_op_query.test

ADD ftest for the 4664 case

---

src/lib/rest/rest.cpp

Supposedly solves security alert https://github.com/telefonicaid/fiware-orion/security/code-scanning/8

FIX redundant NULL check

---

CHANGES_NEXT_RELEASE
ci/deb/build.sh
doc/manuals/orion-api.md
docker/Dockerfile
docker/Dockerfile.alpine

Mimics (somehow) PR https://github.com/telefonicaid/fiware-orion/pull/4654

FIX upgrade cjexl to 0.6.0

---

test/functionalTest/cases/4004_jexl_expressions_in_subs/jexl_transformation_mapper_cases.test
test/functionalTest/cases/4004_jexl_expressions_in_subs/jexl_transformation_n_mapper_cases.test

Requires cjexl 0.6.0, so the test is going to fail first time.

ADD jexl_transformation_mapper_cases.test

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4556_eval_priority_in_expressions/eval_priority_in_expressions.test
test/functionalTest/cases/4556_eval_priority_in_expressions/eval_priority_with_id_type.test

First commit in this PR includes the .test that raises the problem

FIX expression in id and type

---

src/lib/ngsiNotify/Notifier.cpp

Unintentionally added in PR https://github.com/telefonicaid/fiware-orion/pull/4690

FIX remove unwanted log traces
