scripts/build/release.sh

FIX alignment with REL procedures

---

.gitignore

Small PR inclding a little fix

ADD new entries under rpm/ to .gittignore

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/673_xauth_token/auth_token_three_steps.test
test/functionalTest/cases/725_multiservice_ignore/service_ignore_without_multiservice.test

Bug/725 multiservice arg ignore (in develop)

---

scripts/build/sonarProperties.sh

To be considered by the Metrics team, not for Developers ;)
@frarape

Changing sonar key

---

src/lib/mongoBackend/mongoQueryContext.cpp

Fixed the leak in 'forward query'

Fixed a leak

---

scripts/check_files_compliance.py
test/acceptance/__init__.py
test/acceptance/integration/__init__.py
test/acceptance/integration/steps_lib/__init__.py
test/acceptance/integration/steps_lib/general.py
test/acceptance/integration/steps_lib/mock_utils.py
test/acceptance/integration/steps_lib/ngsi_request.py
test/acceptance/integration/steps_lib/payload_objects.py
test/acceptance/integration/terrain.py
test/acceptance/integration/tools/__init__.py
test/acceptance/integration/tools/general_utils.py
test/acceptance/integration/tools/mock_cb_utils.py

Add new rule to "check_files_compilance" to not check the requirements.txt and json configuration of the texts in the acceptance folder

Fixed header

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutines/postIndividualContextEntityAttribute.cpp
test/functionalTest/cases/772_bad_json_response_in_convop/post_v1_contextEntities_ID_attributes_ATTR.test

Fixed a bug of rendering a StatusCode as complete response

Fixed a bug with rendering response containing jsut StatusCode

---

test/acceptance/integration/ISSUE-715 CPr-propagate X-Auth-Token header in forwarded requests/__init__.py
test/acceptance/integration/ISSUE-715 CPr-propagate X-Auth-Token header in forwarded requests/issue-715.feature
test/acceptance/integration/steps_lib/general.py
test/acceptance/integration/steps_lib/mock_utils.py
test/acceptance/integration/steps_lib/ngsi_request.py

Refactor the steps and the mock. Now, the lettuce_tools mock version is used to simulate the Context Provider funtionality

Implemented tests for issue 715

---

scripts/managedb/check_db_sanity.py
scripts/managedb/fix_default_sp.py
scripts/managedb/merge_default_sp_dups.py

This PR consolidates into repository a couple of scripts only present at gist at the present moment (https://gist.github.com/fgalan/a048bf48b4d4cd148d76 and https://gist.github.com/fgalan/1922df50f35ab3529b91)
After merging this PR the following actions need to be done:
* Merge the same changes into release/0.19.0 in a new PR (either with a diff or cherry picks)
* Update the 0.19.0-FIWARE-4.2.2 tag to the HEAD of release/0.19.0
* Change the wiki links, from gist to the files at 0.19.0-FIWARE-4.2.2 tag
@jcalderin @iariasleon (as you use Python in your code)

Hardening/migration 0.19.0 script

---

CHANGES_NEXT_RELEASE
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/ContextElement.cpp
src/lib/ngsi/ContextElement.h
test/unittests/mongoBackend/mongoContextProvidersQuery_test.cpp
test/unittests/mongoBackend/mongoContextProvidersUpdate_test.cpp

This PR is mainly to "agree" in the internal interface between mongoBackend and serviceRoutines. Have a in-deep look to the unit test, in order to check if everything is ok from your point of view or you foresee some problem (of course, not foreseeing a problem not doesn't mean we face it once implementation start, but try to catch them at design time :)

mongoBackend unit test draft for CPr full functionality

---

test/acceptance/README.md
test/acceptance/integration/ISSUE-322 Service support for registries (NGSI9)/issue-322.feature
test/acceptance/integration/ISSUE-713 CPr-propagate Fiware-Service header in forwarded requests/issue-713.feature
test/acceptance/integration/ISSUE-714 CPr-propagate Fiware-Servicepath header in forwarded requests/issue-714.feature
test/acceptance/integration/ISSUE-715 CPr-propagate X-Auth-Token header in forwarded requests/issue-715.feature
test/acceptance/integration/ISSUE-716 ContextProvicer forwarding for attributes not existing in existing entities/issue-716.feature
test/acceptance/integration/ISSUE-719 ServicePath for registrations (NGSI9) (not recursive)/issue-719.feature
test/acceptance/integration/steps_lib/background.py
test/acceptance/integration/terrain.py
test/acceptance/integration/tools/general_utils.py
test/acceptance/properties.json
test/acceptance/requirements.txt

Add Background to all features to start the CB before the tests
Add properties to set the context broker bin configuration

Add context broker executable management (local and remote)

---

src/lib/ngsi/StatusCode.cpp
src/lib/ngsi/StatusCode.h
src/lib/ngsi10/UpdateContextRequest.cpp
src/lib/ngsi10/UpdateContextRequest.h
src/lib/serviceRoutines/deleteIndividualContextEntity.cpp
test/functionalTest/cases/117_convop_using_standard_ops/deleteIndividualContextEntity_v1_contextEntities_EID.test

One more convop moved to use std-op service routine.

DELETE /v1/contextEntities/EID now uses sdt-op and not conv-map

---

makefile

Fix correct job name for coverage publication.

Fix correct job name

---

test/acceptance/README.md
test/acceptance/__init__.py
test/acceptance/integration/steps_lib/general.py
test/acceptance/integration/steps_lib/mock_utils.py
test/acceptance/integration/terrain.py
test/acceptance/integration/tools/general_utils.py
test/acceptance/properties_base.json

Use better logger
Add configuration to set the pid file and contextbroker log

Change the way to kill ContextBroker

---

src/lib/common/statistics.cpp
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/ContextElementResponse.h
src/lib/ngsi/Request.cpp
src/lib/ngsi/Request.h
src/lib/serviceRoutines/getAllEntitiesWithTypeAndId.cpp
test/functionalTest/cases/117_convop_using_standard_ops/getAllEntitiesWithTypeAndId.test

One more convop converted to using std-op

GET /v1/contextEntities/type/{entity::type}/id/{entity::id} 

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/mongoSubscribeContextAvailability.cpp
src/lib/mongoBackend/mongoSubscribeContextAvailability.h
src/lib/ngsi9/SubscribeContextAvailabilityRequest.cpp
src/lib/ngsi9/SubscribeContextAvailabilityRequest.h
src/lib/serviceRoutines/CMakeLists.txt
src/lib/serviceRoutines/postSubscribeContextAvailability.cpp
src/lib/serviceRoutines/postSubscribeContextAvailabilityConvOp.cpp
src/lib/serviceRoutines/postSubscribeContextAvailabilityConvOp.h
test/functionalTest/cases/117_convop_using_standard_ops/postSubscribeContextAvailabilityConvOp.test
test/functionalTest/cases/117_convop_using_standard_ops/postSubscribeContextConvOp.test
test/unittests/mongoBackend/mongoSubscribeContextAvailability_test.cpp

postSubscribeContextAvailabilityConvOp

---

test/functionalTest/cases/117_convop_using_standard_ops/putAvailabilitySubscriptionConvOp.test
test/functionalTest/cases/789_notifyFormat/notifyFormat_ngsi10.test
test/functionalTest/cases/789_notifyFormat/notifyFormat_ngsi9.test

Modified 117_convop_using_standard_ops/putAvailabilitySubscriptionConvOp.test to include accumulator. (solves issue #789)
Added two new functests to verify the correct function of default notification formats and the URI parameter 'notifyFormat=XML/JSON' (somehow also issue #789, even though not really ...)

Two new functests and one modified

---

scripts/build/release.sh

Small fix in argument number checking.
In addition, recovering some commented lines to align with current releasing procedure (which includes merging to master).

FIX small issues in release.sh script

---

CHANGES_NEXT_RELEASE
scripts/managedb/check_db_sanity.py
scripts/managedb/fix_location_gjson.py
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/690_geoquery_crash/invalid_polygon_geoscope.test
test/unittests/mongoBackend/mongoUpdateContextGeo_test.cpp

Fixes #415 
Unfortunatelly, I cannot base this PR in develop branch, but in feature/787_cprs_full_functional, due to it touches some parts in the mongoBackend that may involve merging conflict in the former case.
This has been tested with MongoDB 2.6 in the following way:
* Unit test: all them working (except the 7 ones we know already are failing in feature/787_cprs_full_functional)
* Harness test: all the test related with "geo" functionality are working (difficult to do a complete make ft pass, as many test are not working due to feature/787_cprs_full_functional):
```
fermin@debvm:~/src/fiware-orion$ test/functionalTest/testHarness.sh --match geo
001/10: 000_ngsi10_geolocation_query/geolocalization_area.test ....................................................... 02 seconds
002/10: …
```

MongoDB 2.6 support

---

test/functionalTest/cases/000_ngsi10_subscriptions/subscription_sequence_ontimeinterval_expiration.test
test/xmlCheck/xmlExtractor.py

This PR fixes the problem we have found recently in Jenkins

FIX xml checker problem

---

doc/apiary/orioncontextbroker.apib
test/functionalTest/harnessFunctions.sh

LGTM from @kzangeli and @raconte needed

FIX some small issues

---

CHANGES_NEXT_RELEASE
src/lib/orionTypes/QueryContextResponseVector.cpp
src/lib/orionTypes/QueryContextResponseVector.h
src/lib/serviceRoutines/postQueryContext.cpp
test/functionalTest/cases/945_pagination_with_cprs/pagination_with_cprs.test

Twin PR (in develop): https://github.com/telefonicaid/fiware-orion/pull/948
Fixes #945

bug/945_pagination_with_cprs (release 0.22.0)

---

src/lib/common/tag.h

A few macros for JSON rendering

ADD a set of macros for JSON rendering

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/common/statistics.cpp
src/lib/ngsi/Request.cpp
src/lib/ngsi/Request.h
src/lib/serviceRoutinesV2/entryPointsTreat.cpp
src/lib/serviceRoutinesV2/entryPointsTreat.h
test/functionalTest/cases/956_v2_list_entry_points/GET_v2_list_entry_points.test

This is a Work in progress. Please do not review yet.
Thanks!

Feature/956 : API v2:  List all the entry points

---

src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/1005_GET_v2_entities_string/1005_GET_v2_entities_string.test

FIX Issue 1005 API v2: Strings are not properly rendered

---

src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/serviceRoutines/leakTreat.cpp
test/unittests/CMakeLists.txt
test/unittests/mongoBackend/mongoContextProvidersQuery_test.cpp
test/unittests/mongoBackend/mongoContextProvidersUpdate_test.cpp
test/unittests/mongoBackend/mongoDiscoverContextAvailability_test.cpp
test/unittests/mongoBackend/mongoNotifyContextAvailability_test.cpp
test/unittests/mongoBackend/mongoNotifyContext_test.cpp
test/unittests/mongoBackend/mongoQueryContextFilterExistEntity_test.cpp
test/unittests/mongoBackend/mongoQueryContextGeo_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoQueryTypes_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_update_test.cpp
test/unittests/mongoBackend/mongoSubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextAvailabilitySubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContextGeo_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptions_test.cpp
test/unittests/testInit.cpp

Removed mongoDisconnect () function

Remove mongoDisconnect () function

---

test/functionalTest/cases/0000_statistics_operation/statistics_with_semaphores.test

Add missing elements for "curlContextMutextWaitingTime"
@fgalan

Include data from curl-context statistics

---

doc/apiary/v2/fiware-ngsiv2-cookbook.apib

Bootstrap version of the cookbook. It is intended to evolve and to group operations diferently once we further develop the spec

ADD v2 API Cookbook as Apiary document

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoQueryContext.cpp
test/functionalTest/cases/945_pagination_with_cprs/pagination_with_cprs_mix_entities.test
test/functionalTest/cases/945_pagination_with_cprs/pagination_with_cprs_mix_entities2.test

This PR cover an unkwown aspect of #945, detected by @anabelengp team.
This PR will remain open while ensure that it mets all the requirements from the Portal team. Once merged, it has to be ported to develop (conflicts may occur due to code style cheks recently implemented in develop for mongoBackend).

Fixes related with paginatinon and CPrs

---

test/functionalTest/cases/0000_bad_requests/exit.test.DISABLED
test/functionalTest/cases/0117_convop_using_standard_ops/getAllContextEntities.test
test/functionalTest/cases/0322_multitenancy/tenant_name_error.test
test/functionalTest/cases/0691_empty_type_and_subscriptions/simple_ngsi10_subscriptions_with_no_type_and_service_path.test
test/functionalTest/cases/0722_unhardwire_format_cpr/query_forward_in_xml.test
test/functionalTest/cases/0787_cprs_full_functional/query_forward_query_not_found.test
test/functionalTest/cases/0787_cprs_full_functional/query_two_attributes_in_cpr_one_local.test

Fixes #651 
It has been added the pair functions dbInit/dbDrop.

DB Cleanup in functional tests

---

doc/apiary/v2/fiware-ngsiv2-cookbook.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

This PR concludes the specification of the entities management part of the APIv2 in apiary.
Note that the operation to get all types ("GET /v2/types") has been added.

APIv2 apiary: specification for attribute, attribute value and entity types resourced

---

src/lib/common/sem.cpp
src/lib/common/sem.h

Modified a leakfix so that it doesn't make the broker die ...

modified a leak fix so that the broker doesn't crash ... :-)

---

rpm/SPECS/contextBroker.spec
scripts/check_files_compliance.py

FIX spec file

---

doc/manuals/admin/build_source.md
src/lib/jsonParseV2/CMakeLists.txt

Added a missing file to last PR (#1071)

Added the CMakeLists.txt to jsonParseV2

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/jsonParseV2/parseContextAttribute.h
src/lib/jsonParseV2/parseEntity.cpp
test/functionalTest/cases/0970_create_entity/empty_attribute_value.test.DISABLED
test/functionalTest/cases/0970_create_entity/errors_at_creation.test

Added some error handling to "POST /v2/entities".

Some error handling for 'POST /v2/entities'

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

This is the first standard operation that we include in the specification.
FYI @kzangeli @iariasleon @mrutid

ADD queryContext spec in NGSIv2 .apib document

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/jsonParseV2/parseEntity.cpp
src/lib/rest/ConnectionInfo.h
src/lib/rest/OrionError.cpp
src/lib/rest/OrionError.h
src/lib/rest/RestService.cpp
src/lib/rest/rest.cpp
src/lib/rest/restReply.cpp
src/lib/serviceRoutines/exitTreat.cpp
src/lib/serviceRoutines/leakTreat.cpp
src/lib/serviceRoutines/logTraceTreat.cpp
src/lib/serviceRoutinesV2/postEntities.cpp
test/functionalTest/cases/1087_error_handling/error_messages_for_invalid_service_path_in_v2.test
test/unittests/convenience/Convenience_test.cpp
test/unittests/jsonParse/jsonRequest_test.cpp
test/unittests/rest/OrionError_test.cpp
test/unittests/rest/rest_test.cpp
test/unittests/serviceRoutines/badNgsi10Request_test.cpp
test/unittests/serviceRoutines/badNgsi9Request_test.cpp
test/unittests/serviceRoutines/badRequest_test.cpp
test/unittests/serviceRoutines/badVerbAllFour_test.cpp
test/unittests/serviceRoutines/exitTreat_test.cpp
test/unittests/serviceRoutines/leakTreat_test.cpp
test/unittests/serviceRoutines/logTraceTreat_test.cpp
test/unittests/xmlParse/xmlRequest_test.cpp

Fixed a bug about error handling for API version 2

---

test/functionalTest/harnessFunctions.sh

fixed a typo in harnessFunctions.sh that made a lot of functests fail

---

src/lib/serviceRoutinesV2/postEntities.cpp

Setting httpStatusCode and Location HTTP header only if all is OK, avoiding to overwrite any error in httpStatusCode.

Setting httpStatusCode to 201 Created only if not set

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Some fixes that weren't actually included in PR #1082 (I commited a version of the file with pending changes to save in my IDE, sorry...).

FIX issues not actually included in PR #1081

---

docker/README.md

Adapted to both github and dockerhub, some more explanations added, a warning about losing data, etc.

Docker README fix

---

src/lib/serviceRoutinesV2/getEntity.cpp
test/functionalTest/cases/0971_GET_v2_entity_param_attrs/GET_v2_entity_all_attrs.test
test/functionalTest/cases/0971_GET_v2_entity_param_attrs/GET_v2_entity_one_attr.test

Implements #971 
@fgalan 
@kzangeli

971 get entity param

---

doc/manuals/user/walkthrough_apiv1.md

Included an index for the file: /doc/manuals/user/walkthrough_apiv1.md

Added an index in file walkthrough_apiv1.md

---

README.md
doc/manuals/admin/database_admin.md
doc/manuals/admin/database_model.md
doc/manuals/admin/diagnosis.md
doc/manuals/admin/logs.md
doc/manuals/admin/upgrading_crossing_0-14-1.md
doc/manuals/admin/upgrading_crossing_0-19-0.md
doc/manuals/admin/upgrading_crossing_0-21-0.md
doc/manuals/user/filtering.md
doc/manuals/user/multitenancy.md

Added a table of contents, for those files:
-database_model.md,database_admin.md,logs.md,filtering.md and diagnosis.md.

Hardening/1136 Add Table of Contents

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/serviceRoutinesV2/postEntity.cpp

FIX RESTful subscriptions and registrations to allow list of entities

ADD /op/query, /op/update /op/discover, /op/register

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1113_bug_metadata_not_updated/metadata_not_updated.test

FIX metadata not update bug

---

src/lib/serviceRoutinesV2/getEntities.cpp
test/functionalTest/cases/0967_v2_query_op/q_in_uri_param_to_scope.test

GET /v2/entities?q=XXX,   XXX moved to 'scope in payload for postQueryContext'

URI param 'q' to Scope for GET /v2/entities

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/serviceRoutinesV2/deleteEntity.cpp
test/functionalTest/cases/0993_DELETE_v2_entity_attr/delete_not_exist.test
test/functionalTest/cases/0993_DELETE_v2_entity_attr/delete_not_exist_attr.test
test/functionalTest/cases/0993_DELETE_v2_entity_attr/delete_ok.test

Implements #993 
Delete entity attr v2
@fgalan 
@kzangeli 

Delete entity attr v2

---

src/lib/cache/EntityInfo.cpp
src/lib/cache/Subscription.cpp
src/lib/cache/SubscriptionCache.cpp
src/lib/jsonParseV2/parseContextAttributeCompoundValue.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/xmlParse/xmlUpdateContextRequest.cpp

Removed all LM_Ms from the source code.
Also, a function stgringValue was removed as it was used only for the LM_Ms.
A few indentations was made as well

Removed LM_Ms

---

docker/Dockerfile

This dockerfile generates an image about 270MB in size, about the same as the one created from an RPM installation -> Success!

New dockerfile

---

doc/manuals/quick_start_guide.md

Fixed whitespace after / in quick_start_guide.md file

Fix whitespace after /

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoCommonUpdate.h
src/lib/mongoBackend/mongoUpdateContext.cpp
src/lib/mongoBackend/mongoUpdateContext.h
src/lib/rest/HttpStatusCode.cpp
src/lib/rest/OrionError.cpp
src/lib/serviceRoutines/postUpdateContext.cpp
test/functionalTest/cases/1198_v2_update_entities_too_many_results/too_many_results.test
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

Fix for #1198 
1 new functional test added.
2 new unit tests added
100% pass in unit test and functional tests

ADD checking for entities number in NGSIv2 updates

---

test/functionalTest/cleanFiles.sh

A little script that may be useful to clean up the directory after failing testHarness.
It is deliverately simple. Please, don't look for `-v` or `-u` options ;)

ADD cleanFiles.sh script

---

src/lib/orionTypes/EntityTypeResponse.cpp
src/lib/orionTypes/EntityTypeVectorResponse.cpp

renamed xml tags to their original names

---

test/acceptance/behave/README.md
test/acceptance/behave/__init__.py
test/acceptance/behave/components/common_steps/initial_steps.py
test/acceptance/behave/components/common_steps/requests.py
test/acceptance/behave/components/ngsiv2/entities/create_entities.feature
test/acceptance/behave/components/ngsiv2/entities/update_append_attribute_by_id.feature
test/acceptance/behave/configuration.json
test/acceptance/behave/environment.py
test/acceptance/behave/properties.json.base
test/acceptance/behave/requirements.txt
test/acceptance/behave/tools/NGSI_v2.py
test/acceptance/behave/tools/properties_config.py

@fgalan @XavierVal @mcarracedo

[FEATURE] RPM vs CLI to acceptance tests

---

doc/manuals/user/v1_v2_coexistence.md

Changed GET /v1/entities?q=<query> --> GET /v2/entities?q=<query> in v1_v2_coexistence.md file

Changed file v1_v2_coexistence.md

---

docker/README.md

Changed http for https, in file README.md in docker/.

Corrected error of README.md file

---

src/lib/common/JsonHelper.cpp

Corrected error on file /src/lib/common/JsonHelper.cpp

Correct error when compiling files_compilance+

---

test/functionalTest/cases/1310_suspect_200OK/suspect_200OK.test.DISABLED

Add test case for reproducing issue

---

doc/manuals/user/walkthrough_apiv1.md

Ortography in the first lines (which got me into it) and eventually format and grammar. Didn't do it through since I didn't know your policy for accepting PRs

A few corrections

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/common/statistics.cpp
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoBackend/mongoGetSubscription.cpp
src/lib/mongoBackend/mongoGetSubscription.h
src/lib/ngsi/Request.cpp
src/lib/ngsi/Request.h
src/lib/serviceRoutinesV2/CMakeLists.txt
src/lib/serviceRoutinesV2/getSubscription.cpp
src/lib/serviceRoutinesV2/getSubscription.h
test/functionalTest/cases/1317_GET_v2_subscription/get_subscription.test

Add get subscription w/o BE

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutines/getAllEntitiesWithTypeAndId.cpp
test/functionalTest/cases/1322_using_patt_conv_op/get_ce_type_id.test

Pass isPattern "false" in getAllEntitiesWithTypeAndId

---

src/lib/mongoBackend/mongoListSubscriptions.cpp
src/lib/mongoBackend/mongoListSubscriptions.h
src/lib/serviceRoutinesV2/getAllSubscriptions.cpp

Refactor passing pointer to vector

---

src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoCommonUpdate.h
src/lib/mongoBackend/mongoUpdateContext.cpp
src/lib/mongoBackend/mongoUpdateContext.h
src/lib/serviceRoutines/postUpdateContext.cpp
src/lib/serviceRoutines/postUpdateContext.h
src/lib/serviceRoutinesV2/postEntities.cpp
test/functionalTest/cases/1158_v2_entity_already_exists/create_already_exists.test
test/functionalTest/cases/1187_empty_attribute_in_create/empty_attribute_in_create.test
test/unittests/serviceRoutines/postUpdateContext_test.cpp

Fix Bug #1158

---

test/unittests/mongoBackend/mongoListSubscriptions_test.cpp

FIX broken unit test

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/requests.py
test/acceptance/behave/components/ngsiv2/entities/replace_attributes_by_id.feature
test/acceptance/behave/tools/NGSI_v2.py

[FEATURE] replace attributes by id (PUT)

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/harnessFunctions.sh

Some .test are failing, but they seem to be things under control (take into account this is not a "regular" PR, but a hotfix).

FIX hotfix to recover $where

---

src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoSubCache.h

cache created, emptied and recreated.
Not used, still a lot missing ...

subcache filled and emptied but not used

---

scripts/bootstrap/ubuntu1404.sh

Also clean leftovers from other times

Remove proxyCoap and add rapidjson to ubuntu bootstrap script

---

scripts/testEnv.sh
src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/TriggeredSubscription.cpp
src/lib/mongoBackend/TriggeredSubscription.h
src/lib/mongoBackend/mongoSubCache.cpp
test/functionalTest/cases/0000_cli/command_line_options.test
test/functionalTest/cases/0000_statistics_operation/statistics_with_semaphores.test
test/functionalTest/cases/0563_ngsi10_get_list_of_all_entities/all_entities_no_filter.test
test/functionalTest/cases/1048_subscription_cache/cache_population_at_init.test
test/functionalTest/cases/1048_subscription_cache/three_subscriptions.test
test/functionalTest/cases/1308_subscription_cache/cache_reset_from_db.test
test/functionalTest/cases/1308_subscription_cache/cache_reset_from_db0_24_0.test
test/functionalTest/cases/1308_subscription_cache/cache_traces.test
test/functionalTest/harnessFunctions.sh
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptions_test.cpp

Unit tests and func tests now work with the new sub-cache implementation.
The functests implemented for 1308 included in this PR - I still haven't seen what exactly they do.
Next PR, the last one for this issue, will be functests especially tailored for the new subcache.

tests work

---

CHANGES_NEXT_RELEASE
src/lib/jsonParse/jsonAppendContextElementRequest.cpp
src/lib/jsonParse/jsonNotifyContextRequest.cpp
src/lib/jsonParse/jsonQueryContextResponse.cpp
src/lib/jsonParse/jsonUpdateContextElementRequest.cpp
src/lib/jsonParse/jsonUpdateContextRequest.cpp
src/lib/jsonParse/jsonUpdateContextResponse.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/xmlParse/xmlAppendContextElementRequest.cpp
src/lib/xmlParse/xmlNotifyContextRequest.cpp
src/lib/xmlParse/xmlQueryContextResponse.cpp
src/lib/xmlParse/xmlUpdateContextElementRequest.cpp
src/lib/xmlParse/xmlUpdateContextRequest.cpp
src/lib/xmlParse/xmlUpdateContextResponse.cpp
test/functionalTest/cases/0000_ngsi10_update/empty_attribute_value.test
test/functionalTest/cases/0000_ngsi10_update/update_sequence.test
test/functionalTest/cases/0000_ngsi10_update/update_sequence_empty_value_in_context_value.test
test/functionalTest/cases/1358_v1_empty_attribute_values/empty_attribute_values.test
test/functionalTest/cases/1358_v1_empty_attribute_values/empty_attribute_values_notification.test
test/functionalTest/runFailing.sh
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

ADD empty attribute support in NGSIv1

---

test/functionalTest/cases/0000_ngsi9_subscriptions/notify_format_in_ngsi9_subscriptions.test
test/functionalTest/cases/0117_convop_using_standard_ops/putAvailabilitySubscriptionConvOp.test
test/functionalTest/cases/0719_servicepath_for_registrations/register_and_discovery_with_many_servicepaths.test
test/functionalTest/cases/0719_servicepath_for_registrations/register_and_discovery_with_servicepath.test
test/functionalTest/cases/0789_notifyFormat/notifyFormat_ngsi9.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test
test/functionalTest/cases/1317_GET_v2_subscription/get_subscription.test

Implements #1371 
Changed from 999* to the corresponding variable LISTENER_PORT

Correct environment variables of test harnnes

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/common/sem.cpp
src/lib/common/statistics.cpp
src/lib/common/statistics.h
src/lib/logMsg/traceLevels.h
src/lib/ngsiNotify/senderThread.cpp
src/lib/serviceRoutines/statisticsTreat.cpp
test/functionalTest/cases/0000_cli/command_line_options.test

Add CLI arg for notification mode

---

test/unittests/main_UnitTest.cpp

Fix problems with unit test of previous PR
@fgalan 
@kzangeli

Add global var for unit tests (notification mode)

---

doc/manuals/user/walkthrough_apiv1.md

Came across these minor inconsistencies/bugs while trying out the examples.

Minor improvements to walkthrough user manual (v1).

---

test/functionalTest/cases/0000_ngsi9_subscriptions/notify_format_in_ngsi9_subscriptions.test
test/functionalTest/cases/0117_convop_using_standard_ops/putAvailabilitySubscriptionConvOp.test
test/functionalTest/cases/0719_servicepath_for_registrations/register_and_discovery_with_many_servicepaths.test
test/functionalTest/cases/0719_servicepath_for_registrations/register_and_discovery_with_servicepath.test
test/functionalTest/cases/0789_notifyFormat/notifyFormat_ngsi9.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test
test/functionalTest/cases/1317_GET_v2_subscription/get_subscription.test

Resolved problem with the harness implemented in PR 1376

Correct errors

---

test/LoadTest/cache_refresh/README.md
test/LoadTest/cache_refresh/append_entities_long_time_v1.0.jmx
test/LoadTest/cache_refresh/drop_database_mongo.sh
test/LoadTest/cache_refresh/reqs_x_secs.sh
test/LoadTest/cache_refresh/requests_listener.py
test/LoadTest/cache_refresh/subs_create_delete.sh

[FEATURE] cache refresh tests

---

src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoGetSubscriptions.h
src/lib/serviceRoutinesV2/getAllSubscriptions.cpp
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subs_pagination.test

Final part of the implementation of #1126

Add pagination for v2 subscriptions

---

test/unittests/mongoBackend/mongoGetSubscriptions_test.cpp

@fgalan 
@kzangeli 
fix broken unit test for mongoListSubscriptions

Fix unit_test get subs list pagination

---

docker/docker-compose.yml

Remove comment in --smallfiles flag and change from building the image to downloading from the official repositories.

FIX Remove comment in smallfiles and build.

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

ADD githash to --version text

---

doc/apiary/orioncontextbroker.apib
doc/apiary/v2/fiware-ngsiv2-cookbook.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

FIX essential patents -> implicit patents

---

docker/README.md

The docker readme file has undergone substantial changes in structure. Hopefully is more clear how to use the different methods now.
Comments welcome, especially for section names :)

New docker readme

---

test/xmlCheck/xmlExtractor.py

This PR is supposed to fix the problems we are having at jenkins with the payload check job.

FIX xmlExtractor script to replace REGEX() in providingApplication lines

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoGetSubscriptions.h
src/lib/serviceRoutinesV2/getAllSubscriptions.cpp
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subs_pagination.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test

Fix #1340 GET subscription list count not working

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp

FIX next() -> nextSafe() in MongoDB cursor processing

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutines/postUpdateContext.cpp
test/functionalTest/cases/1440_cpr_update_compounds/cpr_update_compounds.test

FIX compound attributes value supported in CPr update forwarding

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp

FIX the '&quot rendering problem'

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data.feature

[FEATURE] update attribute data acceptance tests

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/cli.md
src/app/contextBroker/contextBroker.cpp
src/lib/common/CMakeLists.txt
src/lib/common/SyncQOverflow.h
src/lib/ngsiNotify/CMakeLists.txt
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueNotifier.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/QueueWorkers.h
src/lib/rest/httpRequestSend.cpp
src/lib/rest/httpRequestSend.h

Add queue and threads for notifications
Close #1449

Add queue and threads for notifications

---

src/lib/ngsiNotify/QueueNotifier.h

@fgalan 
@kzangeli 
Missing copyright header breaking build

Add missing copyright header

---

test/functionalTest/cases/0616_len_of_FiwareService_string/dbname_max_chars.test
test/unittests/cache/SubscriptionCache_test.cpp
test/unittests/mongoBackend/mongoQueryContextGeo_test.cpp

Small fixes in unittest and functional tests

---

src/lib/ngsiNotify/CMakeLists.txt
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueStatistics.cpp
src/lib/ngsiNotify/QueueStatistics.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/serviceRoutines/statisticsTreat.cpp

Partially implements #1485 
(In a following PR for part B, with time measures, we can refactor and choose better names for variables etc)

Add statistics for notif queue (part A, w/o time)

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/__init__.py
test/acceptance/behave/components/ngsiv2/attributes_values/environment.py
test/acceptance/behave/components/ngsiv2/attributes_values/steps/__init__.py
test/acceptance/behave/components/ngsiv2/attributes_values/steps/step.py
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes.feature

[FEATURE] update attribute value acceptance tests

---

test/unittests/CMakeLists.txt

Fix unit test building
@fgalan 
@kzangeli

Change link order unit test

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/delete_steps.py
test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity.feature
test/acceptance/behave/tools/NGSI_v2.py

[FEATURE] remove a single attribute acceptance tests

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/common/statistics.cpp
src/lib/common/statistics.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/ngsiNotify/senderThread.cpp
src/lib/serviceRoutines/statisticsTreat.cpp
test/functionalTest/cases/0000_cli/command_line_options.test
test/unittests/main_UnitTest.cpp

Implements #1505 
Make notification simulation "orthogonal" to notificationMode

Make notification simulation "orthogonal" to notificationMode 

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/rest/httpRequestSend.cpp
src/lib/serviceRoutines/deleteAttributeValueInstance.cpp
src/lib/serviceRoutines/deleteAttributeValueInstanceWithTypeAndId.cpp
src/lib/serviceRoutines/deleteIndividualContextEntityAttribute.cpp
src/lib/serviceRoutines/postAllEntitiesWithTypeAndId.cpp
src/lib/serviceRoutines/postIndividualContextEntity.cpp
src/lib/serviceRoutines/postIndividualContextEntityAttribute.cpp
src/lib/serviceRoutines/putAllEntitiesWithTypeAndId.cpp

Related with https://github.com/telefonicaid/fiware-orion/issues/1368
Fix cppcheck performance warnings

Fix cppcheck performance

---

src/lib/common/string.cpp
src/lib/jsonParse/jsonParse.cpp
src/lib/jsonParseV2/parseContextAttributeCompoundValue.cpp
src/lib/logMsg/logMsg.h
src/lib/ngsi/ContextRegistrationAttribute.cpp
src/lib/rest/RestService.cpp
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutines/postUpdateContext.cpp
src/lib/xmlParse/xmlUpdateContextSubscriptionRequest.cpp
test/functionalTest/cases/0322_multitenancy/http_tenant_name_error.test
test/functionalTest/cases/0322_multitenancy/tenant_name_error.test
test/functionalTest/cases/1087_error_handling/error_messages_for_invalid_tenant_in_v2.test

Related with https://github.com/telefonicaid/fiware-orion/issues/1368

More cppcheck fixes

---

test/loadTest/README.md
test/loadTest/orion_updates_ngsiv2.jmx

[FEATURE] random timeInstant properties

---

scripts/managedb/csubs_control/README.md
scripts/managedb/csubs_control/csub_dups_checker.py
scripts/managedb/csubs_control/csub_dups_test.sh
scripts/managedb/csubs_control/csub_localhost_reference_checker.py
scripts/managedb/csubs_control/csub_reference_limit_per_ip_checker.py

Tested with a copy of the orion.lab DB except some functionality (i.e. the one related with CB restart) that will be deferred to real testing on the orion.lab testbed.

ADD csubs control scripts

---

doc/manuals/quick_start_guide.md

FIX ngsi10 -> v1 prefix in quick guide documentation

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

FIX more compact alternative for if

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/ngsi/EntityIdVector.cpp
src/lib/ngsi/EntityIdVector.h
src/lib/ngsi/ScopeVector.cpp
src/lib/ngsi/ScopeVector.h
src/lib/orionTypes/areas.cpp
src/lib/orionTypes/areas.h

Refactor to const references

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

FIX issue 1464 - Empty callback and metadata for registrations

---

scripts/managedb/csubs_control/csub_dups_checker.py
scripts/managedb/csubs_control/csub_localhost_reference_checker.py
scripts/managedb/csubs_control/csub_reference_limit_per_ip_checker.py

Found after testing  `--with-restart` at orion.lab.

Small fixes in csub control script

---

src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoQueryContext.cpp

Refactor use const & for EntityIDVector

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/0908_update_duplicated_attributes/dup_attrs_avoid_db_error.test

FIX dup attributes updates problem

---

src/app/contextBroker/contextBroker.cpp
src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueNotifier.h

Refactor notifier-queue-workers. Exit leak

---

src/lib/common/limits.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/rest/RestService.cpp
src/lib/rest/rest.cpp
test/functionalTest/cases/1403_length_of_tenant/long_tenant_name.test

Moved constants for service (tenant) and service path to new file - common/limits.h
Fixes issue #1403

Moved constants to common/limits.h

---

src/lib/apiTypesV2/Entity.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/Metadata.cpp
src/lib/ngsi/Scope.cpp
src/lib/parse/forbiddenChars.cpp
src/lib/rest/rest.cpp
src/lib/xmlParse/xmlParse.cpp

Changed a few LM_E to LM_W for forbidden chars, added a lot  ...
Nothing in CNR ... 
Fixes issue #1567

LM_W for forbidden characters

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoGetSubscriptions.h
src/lib/serviceRoutinesV2/getAllSubscriptions.cpp
test/functionalTest/cases/1577_servicepath_get_subs/get_subs_with_servicepath.test
test/unittests/mongoBackend/mongoGetSubscriptions_test.cpp

Use service/servicepath to get subs

---

CHANGES_NEXT_RELEASE
src/lib/rest/httpRequestSend.cpp

Backport of issue #1016 extracted (manually) from PR #1021 
@crbrox

Backport of the #1016 fix to 0.22.0

---

test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/api_entry_point/retrieve_api_resource.feature
test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes.feature

[CHANGE] error message to wrong service header

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/version.h

This PR leaves develop in good shape for post-0.26.1 development cycles. Just adjusting number and remove from CNR things already covered in the .spec.

Step: 0.26.0-next -> 0.26.1-next

---

makefile
rpm/SPECS/contextBroker.spec
test/unittests/orionTypes/EntityTypeVectorResponse_test.cpp
test/unittests/orionTypes/UpdateContextRequestVector_test.cpp

Minor issues on the changes introduced in PR https://github.com/telefonicaid/fiware-orion/pull/1609 and PR https://github.com/telefonicaid/fiware-orion/pull/1603.

Some minor fixes

---

src/lib/logMsg/traceLevels.h
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutines/postUpdateContext.cpp
test/unittests/CMakeLists.txt
test/unittests/apiTypesV2/Entities_test.cpp
test/unittests/apiTypesV2/EntityVector_test.cpp
test/unittests/apiTypesV2/Entity_test.cpp
test/unittests/orionTypes/EntityTypeResponse_test.cpp
test/unittests/orionTypes/EntityTypeVectorResponse_test.cpp
test/unittests/orionTypes/EntityTypeVector_test.cpp
test/unittests/orionTypes/EntityType_test.cpp

Along with traceveles for CPr forwarded request/response payload.

Unit test improvements for apiTypesV2

---

CHANGES_NEXT_RELEASE
CMakeLists.txt

In addition, -g has been removed from release build.

Adjusting CMakeList.txt for coverage targets

---

test/functionalTest/testHarness.sh

Three tries for failing func tests

---

CHANGES_NEXT_RELEASE
src/lib/common/JsonHelper.cpp
src/lib/common/tag.cpp
src/lib/common/tag.h
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subs_pagination.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test
test/functionalTest/cases/1172_bug_json_invalid_render/invalid_json_render.test
test/functionalTest/cases/1317_GET_v2_subscription/get_subscription.test
test/functionalTest/cases/1577_servicepath_get_subs/get_subs_with_servicepath.test

**DO NOT DELETE BRANCH AFTER MERGE** (note that this PR uses release/0.26.1 as base, we need the branch to merge also in develop at the end).
As a side fix, also avoid escaping / in callback field in GET /v2/subscriptions and GET /v2/subscriptions/<subId> operations.
All unit and harness test passing.
@kzangeli @crbrox

Avoid rendering invalid JSON characters in response payloads

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/get_steps.py
test/acceptance/behave/components/ngsiv2/entities/list_entities.feature
test/acceptance/behave/properties.json.base
test/acceptance/behave/tools/NGSI_v2.py

@fgalan @kzangeli 
```
SUMMARY:
- components/ngsiv2/entities/create_entity.feature >> passed: 447, failed: 0, skipped: 136 and total: 583 with duration: 68.806 seconds.
- components/ngsiv2/entities/list_entities.feature >> passed: 386, failed: 0, skipped: 111 and total: 497 with duration: 148.424 seconds.
- components/ngsiv2/entities/remove_entity.feature >> passed: 58, failed: 0, skipped: 10 and total: 68 with duration: 10.094 seconds.
- components/ngsiv2/entities/replace_all_entity_attributes.feature >> passed: 248, failed: 0, skipped: 315 and total: 563 with duration: 67.028 seconds.
- components/ngsiv2/entities/retrieve_entity.feature >> passed: 135, failed: 0, skipped: 77 and total: 212 with duration: 26.494 seconds.
- …
```

[FEATURE] list entities with q query parameter

---

CMakeLists.txt
README.md
doc/manuals/admin/database_admin.md
doc/manuals/admin/perf_tuning.md
doc/manuals/user/federation.md
doc/manuals/user/metadata.md
doc/manuals/user/walkthrough_apiv1.md

In some sense, implements #1554 (and more)

FIX CMakeList.txt to avoid over-flaging

---

test/acceptance/behave/README.md

Including a quick-guide to set up the thing.

Improve behave documentation

---

src/lib/rest/ConnectionInfo.cpp
src/lib/serviceRoutinesV2/postEntity.cpp
test/functionalTest/cases/0981_POST_v2_attributes/append_and_append_only_combinations.test
test/functionalTest/cases/0981_POST_v2_attributes/append_only_attribute_already_there.test
test/functionalTest/cases/0981_POST_v2_attributes/append_only_error_if_exists.test

op=append no longer in use. options=append is used in its place

op=append no longer in use. options=append is used in its place

---

CHANGES_NEXT_RELEASE
src/lib/jsonParse/jsonParse.cpp
src/lib/ngsi/ContextElementResponse.cpp
test/functionalTest/cases/1308_subscription_cache/sub_expired_and_updated_then_cache_refresh.test
test/functionalTest/cases/1642_empty_string_in_nested_object/empty_string_in_nested_object.test

fixed issue 1642 - bug in empty strings in compounds

---

scripts/check_files_compliance.py
src/lib/parseArgs/paConfig.h
test/functionalTest/cases/0000_cli/version.test

Happy New Year 2016

---

src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1316_create_subscription/post_subscriptions.test

Fix bug create subs v2

---

doc/manuals/admin/database_model.md
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/ngsi/NotifyCondition.h
src/lib/ngsi10/SubscribeContextRequest.h
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp

expression in subcription subject, not in conditions

---

src/lib/mongoBackend/mongoUpdateContextSubscription.cpp

Restore building in CI
@fgalan 
@kzangeli

Remove PRId64

---

src/lib/rest/rest.cpp

Add PATCH method

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv1.test
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv2.test

FIX lost sp in update context subscription

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv1.test
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv2.test
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp

Twin of PR https://github.com/telefonicaid/fiware-orion/pull/1694 + cherry pick to fix a unit test

FIX lost sp in update context subscription (into 0.26.1)

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

To be checked by:
@mrutid
@joser
@antoniojoseln

Syntax for id fields in NGSIv2 specification

---

src/lib/mongoBackend/MongoGlobal.cpp

Fix some valgrind tests

---

src/app/contextBroker/contextBroker.cpp
src/lib/logSummary/logSummary.cpp
src/lib/logSummary/logSummary.h

Fix warning int to void* conversion

---

test/unittests/main_UnitTest.cpp

Use global var for lsPeriod in unit test

---

src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoCommonUpdate.h
src/lib/mongoBackend/mongoUpdateContext.cpp
src/lib/mongoBackend/mongoUpdateContext.h
src/lib/serviceRoutines/postUpdateContext.cpp
src/lib/serviceRoutines/postUpdateContext.h
src/lib/serviceRoutinesV2/postEntities.cpp
src/lib/serviceRoutinesV2/postEntity.cpp
test/functionalTest/cases/0981_POST_v2_attributes/append_only_attribute_already_there.test
test/functionalTest/cases/0981_POST_v2_attributes/append_only_error_if_exists.test
test/functionalTest/cases/0985_DELETE_v2_entity/delete_ok.test
test/functionalTest/cases/0987_put_attributes/put_entity_complete_replace_attributes.test
test/functionalTest/cases/0987_put_attributes/put_entity_error.test
test/functionalTest/cases/0987_put_attributes/put_entity_partially_replace_attributes.test
test/functionalTest/cases/1259_new_json_for_v2/get_attribute_value.test
test/functionalTest/cases/1259_new_json_for_v2/get_attribute_value_small.test
test/functionalTest/cases/1259_new_json_for_v2/putPostPatch_v2_entities_eid.test
test/functionalTest/cases/1259_new_json_for_v2/put_attribute_value.test
test/functionalTest/cases/1259_new_json_for_v2/v2_render_modes.test
test/functionalTest/cases/1323_put_replacing_dot_in_attrnames/put_replacing_dot_in_attrnames.test

FIX POST /v1/entities/{id} not allowed to create entities

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/ngsiv2/entities/create_entity.feature
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
- components/ngsiv2/entities/create_entity.feature >> passed: 559, failed: 0, skipped: 120 and total: 679 with duration: 100.922 seconds.
Date: Tuesday, January 26, 2016 12:28:38
559 scenarios passed, 0 failed, 120 skipped
2751 steps passed, 0 failed, 659 skipped, 0 undefined
Took 1m40.922s
```

[FEATURE] refactor in create_entity feature (1259)

---

docker/Dockerfile

This was missed in PR https://github.com/telefonicaid/fiware-orion/pull/1707 ...
@LeandroGuillen

Upgrade mongo driver 1.0.2 -> 1.0.7 in Dockerfile

---

src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/common/string.cpp
src/lib/jsonParseV2/jsonRequestTreat.cpp
src/lib/jsonParseV2/jsonRequestTreat.h
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/jsonParseV2/parseSubscription.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/TriggeredSubscription.cpp
src/lib/mongoBackend/TriggeredSubscription.h
src/lib/ngsi/NotifyConditionVector.cpp
src/lib/ngsi/NotifyConditionVector.h
src/lib/rest/RestService.cpp
src/lib/serviceRoutines/exitTreat.cpp
test/functionalTest/cases/1316_create_subscription/post_subs_errors.test
test/functionalTest/cases/1658_v2_patch_subscription/patch_subscriptions.test

valgrind test suite without leaks for 0.70 release.
As I was inside parseSubscription.cpp fixing leaks, I fixed style guide also.
I know ... sorry.
Only three important changes there, I will mark them for the reviewers

Fixed leaks

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Fixed some errors with the JSON format in fiware-ngsiv2-reference.apib file

Fixed some minor errors with bad format JSON

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Reverts telefonicaid/fiware-orion#1723

Revert "Fixed some minor errors with bad format JSON"

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Almost the same than https://github.com/telefonicaid/fiware-orion/pull/1723, this time checking with local apiary client that the final result renders.

FIX JSON payloads in NGSIv2

---

doc/manuals/admin/cli.md
doc/manuals/user/forbidden_characters.md
doc/manuals/user/v1_v2_coexistence.md

Doc pieces corresponding to issue #1601

FIX doc regarding -strictNgsiv1Ids

---

src/lib/parse/forbiddenChars.cpp
test/functionalTest/cases/1728_bug_forbidden_chars/restrict_chars_attr.test
test/functionalTest/cases/1728_bug_forbidden_chars/restrict_chars_entity.test
test/functionalTest/cases/1728_bug_forbidden_chars/restrict_chars_metadata.test

@fgalan 
@kzangeli 
fixes #1728

Include old set in forbidden chars for ids

---

test/acceptance/behave/components/ngsiv2/entities/create_entity.feature

``` 
SUMMARY:
- components/ngsiv2/entities/create_entity.feature >> passed: 677, failed: 0, skipped: 16 and total: 693 with duration: 114.396 seconds.
Date: Thursday, January 28, 2016 13:24:26
677 scenarios passed, 0 failed, 16 skipped
3416 steps passed, 0 failed, 64 skipped, 0 undefined
Took 1m54.396s
```

[RE-TEST] bugs: 1713, 1716, 1601, 1351

---

src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/1594_query_with_q_and_equals_true/query_with_q_and_equals_true.test
test/functionalTest/cases/1595_query_with_q_and_string_values/query_with_q_and_string_values.test

Issue 1595 fixed

---

src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/1592_query_with_q_op_greater_or_equal/query_with_all_q_ops_without_right_hand_side.test

Fixes issue #1592   (for not 3 but for 8 operators, all ops that we support :-))
Checking ALL operations for missing right-hand-value.

Fixed all of issue 1592

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1433_update_metadata_duplicated/update_meta.test

@fgalan 
@kzangeli 
fixes #1433

Update metadata changing type

---

src/lib/mongoBackend/MongoGlobal.cpp

Stupid mistake made during my last PR. Now fixed

fixed error in addBsonFilter 'right-hand-value-empty-check

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/logs.md
src/lib/logMsg/logMsg.h
src/lib/mongoBackend/MongoCommonUpdate.cpp

FIX error level traces ignoring -logLevel NONE
FIX wrong over-logging at error level updating attributes having metadata without type
@kzangeli 
@crbrox

Some issues related with logging

---

test/functionalTest/cases/1490_compound_values_with_dot_in_key/compound_values_with_dot_in_key.test

New functest top prove that 1490 can be closed

---

test/functionalTest/cases/1587_q_query_has_type/q_query_has_type.test
test/functionalTest/cases/1589_query_entities_with_specific_attributes/query_entities_with_specific_attributes.test

Two functests about entity type exists or not enabled and fixed.
This PR finishes the issue #1751 ?

Fixed two disables functests

---

CHANGES_NEXT_RELEASE
test/functionalTest/cases/1675_entity_with_plus_symbol/entity_with_plus_symbol.test
test/functionalTest/cases/1675_entity_with_plus_symbol/entity_with_plus_symbol_v2.test

Provides the .test to cover #1675 
@crbrox 
@kzangeli

ADD functional test for entities id with +

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/getEntity.cpp
src/lib/serviceRoutinesV2/getEntityAttribute.cpp
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp
test/functionalTest/cases/0951_get_v2_param_type/get_v2_param_type.test

Add type query parameter for GET entity/entities (with attribute / attribute value)
#951 #972 #990  #998
@fgalan 
@kzangeli

Add type param for getting entities in v2

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/deleteEntity.cpp
test/functionalTest/cases/0986_delete_with_type_param/delete_with_type_param.test

Add type param for DELETE entity in v2 
#986, #994
@kzangeli 
@fgalan

type param for DELETE entity in v2

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/patchEntity.cpp
test/functionalTest/cases/0980_patch_entity_v2_wihth_param_type/patch_entity_with_param_type.test

Add type param for PATCH entity. Implements #980
@kzangeli 
@fgalan

Add type param for PATCH entity

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

FIX doc for the POST /v2/entities/<id> operation.

FIX doc for the POST /v2/entities/<id> operation

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/postEntity.cpp
test/functionalTest/cases/0982_post_entity_with_type_param/982_post_entity_with_type_param.test

Add param type for POST entity in v2
@fgalan 
@kzangeli 
#982 #984

Add param type for POST entity in v2

---

CHANGES_NEXT_RELEASE
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/dbConstants.h
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/mongoBackend/mongoQueryContext.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/ContextElementResponse.h
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutinesV2/postEntities.cpp
src/lib/serviceRoutinesV2/postEntity.cpp
test/functionalTest/cases/1038_geo_point_support/geo_errors.test
test/functionalTest/cases/1038_geo_point_support/geoquery_circle_geopoint.test
test/functionalTest/cases/1038_geo_point_support/geoquery_polygon_geopoint.test
test/functionalTest/cases/1177_geometry_and_coords/geometry_and_coords.test
test/unittests/mongoBackend/mongoUpdateContextGeo_test.cpp

Implements #1038 
@crbrox 
@kzangeli

ADD geo:point support for NGSIv2 keeping compatibility with NGSIv1 geo-location approach

---

CHANGES_NEXT_RELEASE
src/lib/ngsi10/UpdateContextRequest.cpp
src/lib/ngsi10/UpdateContextRequest.h
src/lib/serviceRoutinesV2/putEntity.cpp
src/lib/serviceRoutinesV2/putEntityAttribute.cpp
src/lib/serviceRoutinesV2/putEntityAttributeValue.cpp
test/functionalTest/cases/0988_put_with_param_type/0988_put_with_param_type.test

@kzangeli 
@fgalan 
Add: type param for PUT entity in v2
#988 #992 #1000

Add type param for PUT entity in v2

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1764_long_servicepath_component/1764_long_servicepath_component.test

It should fix #1764 #1774 and (re-opened) #1423 
@kzangeli 
@fgalan

Fix error with long servicepath component

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/create_entity.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_1.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/__init__.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/environment.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/steps/__init__.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/steps/step.py
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
- components/ngsiv2/entities/retrieve_entity/retrieve_entity.feature >> passed: 200, failed: 0, skipped: 0 and total: 200 with duration: 191.984 seconds.
- components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature >> passed: 19, failed: 0, skipped: 1 and total: 20 with duration: 24.310 seconds.
Date: Tuesday, February 09, 2016 10:33:31
219 scenarios passed, 0 failed, 1 skipped
1449 steps passed, 0 failed, 7 skipped, 0 undefined
Took 3m36.294s
```
Tests are appended to options=keyValues query parameter

[FEATURE] changes in json format in retrieve entity response

---

CHANGES_NEXT_RELEASE
src/lib/common/JsonHelper.cpp
src/lib/common/globals.h
src/lib/common/string.cpp
src/lib/common/string.h
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/Metadata.cpp
src/lib/orionTypes/QueryContextResponseVector.cpp
src/lib/parse/CompoundValueNode.cpp
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp
test/functionalTest/cases/1039_ngsiv2_date_support/basic_dates_support.test
test/unittests/testInit.cpp

Implements #1039
@kzangeli 
@crbrox

ADD basic date support

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp
test/functionalTest/cases/1805_option_with_value_in_qs/1805_option_with_value_in_qs.test

Fix unchecked dereference

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
test/functionalTest/cases/1316_create_subscription/post_subs_expr_q_lesser_or_equal_than.test
test/functionalTest/cases/1316_create_subscription/post_subs_expr_q_lesser_than.test
test/unittests/mongoBackend/mongoQueryContext_filters_test.cpp

Implement #1689
Changed from lesser than to less than the following files: 
- doc/apiary/v2/fiware-ngsiv2-reference.apib
- test/functionalTest/cases/1316_create_subscription/post_subs_expr_q_lesser_or_equal_than.test
- test/functionalTest/cases/1316_create_subscription/post_subs_expr_q_lesser_than.test
- test/unittests/mongoBackend/mongoQueryContext_filters_test.cpp

From lesser than to less than

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Entity.cpp
src/lib/ngsi/ContextAttributeVector.cpp
src/lib/ngsi/ContextAttributeVector.h
test/functionalTest/cases/1049_values_mode/attrs_order.test
test/functionalTest/cases/1049_values_mode/values_mode.test
test/functionalTest/cases/1049_values_mode/values_mode_entities.test
test/functionalTest/cases/1158_v2_entity_already_exists/create_already_exists.test
test/functionalTest/cases/1259_new_json_for_v2/v2_render_modes.test

Implements #1049 
@kzangeli 
@crbrox

ADD options=value mode for NGSIv2 entity queries

---

src/lib/orion_websocket/connection_manager.cpp
src/lib/orion_websocket/parser.cpp
src/lib/orion_websocket/ws.cpp
src/lib/rest/CMakeLists.txt
src/lib/rest/ConnectionInfo.cpp
src/lib/rest/ConnectionInfo.h
src/lib/rest/HttpHeaders.cpp
src/lib/rest/HttpHeaders.h

Add headers in input envelope

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/rest/uriParamNames.h
test/functionalTest/cases/1103_sorted_by_attribute/sorted_by_attribute.test

Implements #1103 
@kzangeli 
@crbrox

ADD sorted URI param in NGSIv2 queries

---

test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part2.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes.feature

see issue: https://github.com/telefonicaid/fiware-orion/issues/1782

[FIX] bug 1782 and tests reviewed

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1682_ngsiv2_entity_id/ngsiv2_entity_id_revisited.test

Fixes #1817 
Returning 422 InvalidModification instead of 404 NotFound whrn POSTing entity
@kzangeli 
@fgalan

Fix #1817 422 instead of 404

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/common_steps/entities/delete_steps.py
test/acceptance/behave/components/ngsiv2/entities/remove_entity/__init__.py
test/acceptance/behave/components/ngsiv2/entities/remove_entity/environment.py
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity/steps/__init__.py
test/acceptance/behave/components/ngsiv2/entities/remove_entity/steps/step.py

```
SUMMARY:
- components/ngsiv2/entities/remove_entity/remove_entity.feature >> passed: 72, failed: 0, skipped: 1 and total: 73 with duration: 8.525 seconds.
Date: Monday, February 22, 2016 16:43:20
72 scenarios passed, 0 failed, 1 skipped
393 steps passed, 0 failed, 7 skipped, 0 undefined
Took 0m8.525s
```

[FEATURE] remove entity with new json

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib

Implement documentation items for #1792, #1766, #1103 
@kzangeli 
@crbrox 
@jmcanterafonseca (in the case you have the time and opportunity)

Doc tokens for #1792 #1766 #1103

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/pagination.md
doc/manuals/user/v1_v2_coexistence.md
test/functionalTest/cases/1080_batch_query_context/batch_query_context_keyvalues.test
test/functionalTest/cases/1080_batch_query_context/batch_query_context_values.test
test/functionalTest/cases/1103_order_by/order_by_attribute.test
test/functionalTest/cases/1103_order_by/order_by_attribute_batch.test
test/functionalTest/cases/1103_order_by/order_by_attribute_ngsiv1.test
test/functionalTest/cases/1103_order_by/order_by_proximity.test

@crbrox 
@kzangeli 
@jmcanterafonseca (nice to have)

ADD .test and documentation changes

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/1039_ngsiv2_date_support/dates_in_uri_param.test
test/functionalTest/cases/1039_ngsiv2_date_support/dates_in_uri_param_lists.test
test/functionalTest/cases/1039_ngsiv2_date_support/dates_in_uri_param_ranges.test

Dates supported in 'q'

---

src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/0876_entity_dates/filter_entity_dates.test
test/functionalTest/cases/0876_entity_dates/get_entity_dates.test

Filters for dateCreated and dateModified

---

test/functionalTest/cases/1080_batch_query_context/batch_query_context_scopes.test
test/unittests/mongoBackend/mongoQueryContext_filters_test.cpp

@kzangeli OR @crbrox (I think that just one LGTM is ok this time)

FIX broke unit_test and ft

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/v1_v2_coexistence.md
src/lib/common/globals.h
src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/1103_order_by/order_by_proximity.test

@kzangeli 
@crbrox 
@jmcanterafonseca (nice to have)

RENAME geo:proximity -> geo:distance

---

src/lib/jsonParseV2/parseScopeVector.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/Scope.cpp
src/lib/serviceRoutinesV2/deleteEntity.cpp

Fixed all leaks for 0.28.0

---

test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_part3.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_1.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_2.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_3.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part3.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_part4.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_part4.feature
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
- components/ngsiv2/entities/create_entity/create_entity.feature >> passed: 148, failed: 0, skipped: 0 and total: 148 with duration: 27.404 seconds.
- components/ngsiv2/entities/create_entity/create_entity_part2.feature >> passed: 235, failed: 0, skipped: 0 and total: 235 with duration: 30.397 seconds.
- components/ngsiv2/entities/create_entity/create_entity_part3.feature >> passed: 294, failed: 0, skipped: 16 and total: 310 with duration: 34.327 seconds.
- components/ngsiv2/entities/list_entities/list_entities.feature >> passed: 188, failed: 0, skipped: 0 and total: 188 with duration: 50.240 seconds.
- components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_1.feature >> passed: 141, failed: 0, skipped: …
```

[FEATURE] none as default value in types

---

doc/manuals/admin/install.md
doc/manuals/quick_start_guide.md
scripts/build/fiwarelab/build-fiwarelab-image.sh
scripts/testScripts/README.md
test/xmlCheck/xmlCheck.sh

Based on the @dmoranj feedback.
In addition, I have take the oportunity to fix some fi-ware -> fiware in order to align with FIWARE "branding".

FIX Mongo 3.2 added to documentation

---

test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes.feature

see https://github.com/telefonicaid/fiware-orion/issues/1873 issue
These scenarios are skipped if the execution uses `-t=-skip` as tag

[PUT] skip tag associated to bug 1873

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/common_steps/entities/delete_steps.py
test/acceptance/behave/components/common_steps/initial_steps.py
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/__init__.py
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/environment.py
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/steps/__init__.py
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/steps/step.py
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data_part3.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity.feature
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
- components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature >> passed: 110, failed: 0, skipped: 11 and total: 121 with duration: 44.479 seconds.
- components/ngsiv2/entities/remove_entity/remove_entity.feature >> passed: 85, failed: 0, skipped: 7 and total: 92 with duration: 24.136 seconds.
Date: Tuesday, March 08, 2016 10:22:40
195 scenarios passed, 0 failed, 18 skipped
1104 steps passed, 0 failed, 114 skipped, 0 undefined
Took 1m8.616s
```
Also are appended tests to:
- "type" query parameter in remove an entity
- change of error description if metadata type …

[FEATURE] new json in remove an attribute and type query parameter

---

README.md
scripts/build/release.sh

Implements #1858 
@jmcanterafonseca (as expert in RTD and badgets)
@kzangeli (as father of the release.sh script)

ADD change version pointed by the RTD badge during version stepping process

---

doc/manuals/user/README.md
doc/manuals/user/append_and_delete.md
doc/manuals/user/delete_entity.md
mkdocs.yml

@dmoranj , as origina "requestor" of the documentation change)
@kzangeli (nice to -have), for English proof-reading (you can edit directly on the PR if you prefer to using comments)

MOVE delete entity documentation to a separte section

---

src/lib/orion_websocket/connection_manager.cpp
src/lib/orion_websocket/parser.cpp
src/lib/orion_websocket/parser.h
src/lib/orion_websocket/ws.cpp
src/lib/rest/rest.cpp
src/lib/rest/rest.h

Fix issue #1668 and add a parameter processor

Output Message and parameters processor

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/create_update_replace_steps.py
test/acceptance/behave/components/common_steps/entities/get_steps.py
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/__init__.py
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/environment.py
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value.feature
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/steps/__init__.py
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/steps/step.py
test/acceptance/behave/tools/NGSI_v2.py

```
SUMMARY:
- components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value.feature >> passed: 172, failed: 0, skipped: 18 and total: 190 with duration: 29.194 seconds.
Date: Thursday, March 10, 2016 15:43:59
172 scenarios passed, 0 failed, 18 skipped
1197 steps passed, 0 failed, 132 skipped, 0 undefined
Took 0m29.194s
```

[FEATURE] get attribute value

---

CHANGES_NEXT_RELEASE
src/lib/ngsi/ContextAttribute.cpp
src/lib/parse/textParse.cpp
test/functionalTest/cases/1904_attr_value_type_none/1904_attr_value_type_none.test

Fixed #1904 
@kzangeli 
@fgalan

Fix #1904 changing type to none when PUT attr value (text/plain)

---

CHANGES_NEXT_RELEASE
src/lib/alarmMgr/AlarmManager.cpp
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoConnectionPool.cpp
src/lib/mongoBackend/mongoDiscoverContextAvailability.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoOntimeintervalOperations.cpp
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoUnsubscribeContextAvailability.cpp
src/lib/mongoBackend/mongoUpdateContextAvailabilitySubscription.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
src/lib/mongoBackend/safeMongo.cpp
src/lib/mongoBackend/safeMongo.h
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/Metadata.cpp
test/functionalTest/cases/0000_ngsi10_convenience/subscriptions_onchange_nocache.test
test/functionalTest/cases/0000_ngsi10_subscriptions/subscription_sequence_onchange_nocache.test
test/functionalTest/cases/0000_ngsi10_subscriptions/subscription_sequence_ontimeinterval.test

Note that the landing branch is release/0.28.0, not develop (thus **don't delete branch after merging, as we would need to merge into develop**).
This PR correspond to a sum of minor changed developed as hotfixes for orion.lab. Most of them are related with loging, although there are some things to discuss (see specific comments on the PR).
@kzangeli 
@crbrox

Some accumulated changes for release/0.28.0

---

test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part3.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature

[APPEND] comments in the description of features (tests)

---

docker/Dockerfile

Fix for #1922 in the release/0.28.0 branch

FIX GIT_REV_ORION at Dockerfile

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Adjustments in the NGSIv2 spec related with #1918 and #1328
@jmcanterafonseca 
@anabelengp

ADD subscriptions description field and redefine the subscription status field in NGSIv2 spec

---

docker/Dockerfile

Fix #1922 in release/0.27.0 branch

FIX GIT_REV_ORION for release/0.27.0

---

docker/Dockerfile

Fix #1922 in release/0.26.1 branch

FIX GIT_REV_ORION for release/0.26.1

---

docker/Dockerfile

Fix #1922 in release/0.26.0 branch

FIX GIT_REV_ORION for release/0.26.0

---

docker/Dockerfile

Fix #1922 in release/0.25.0 branch

FIX GIT_REV_ORION for release/0.25.0

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

FIX json returned by query op in NGSIv2 apib

---

scripts/build/release.sh

Finished #1922 (potential bugs apart, of course ;)

FIX release.sh script to take into account Dockerfile changes

---

docker/README.md
docker/docker-compose.yml

MongoDB 2.6 -> 3.2 in docker stuff

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1947_1972_invalid_subs_crash/1947_1972_invalid_subs_crash.test

Fixes #1947 #1972  (crashes with invalid subscription)
@fgalan 
@kzangeli

Check types of subscription (v2)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1956_bug_cross_sp_update/bug_cross_sp_update.test

FIX bug #1956

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/dbConstants.h
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoSubCache.h
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
src/lib/ngsi10/SubscribeContextRequest.h
test/functionalTest/cases/1048_subscription_cache/csub_update_with_notif.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_errors.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_notif_cache.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_notif_nocache.test
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp

Implements #1328 and a couple of fixed in csubs cache that I have need to introduce on the way.
@kzangeli 
@crbrox

ADD pause subscriptions using the NGSIv2 API and a couple of csubs cache fixes

---

README.md
doc/manuals/contribution_guide.md
doc/manuals/contribution_guidelines.md

Use the "View" buttom to see the rendered document. Check specially that all code blocks are ok and according to the surrounding rule.
~~In addition, the *How to check* section needs to be completed in each rule before merging this PR.~~

Contribution guidelines document

---

scripts/build/fiwarelab/build-fiwarelab-image.sh

FIWARE Lab build script yum repository URL change

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/apiTypesV2/Attribute.cpp
src/lib/apiTypesV2/Entity.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoQueryTypes.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/ContextAttributeVector.cpp
src/lib/ngsi/ContextAttributeVector.h
src/lib/orionTypes/EntityType.cpp
src/lib/orionTypes/EntityType.h
src/lib/orionTypes/EntityTypeResponse.cpp
src/lib/orionTypes/EntityTypeVectorResponse.cpp
src/lib/serviceRoutines/getAttributesForEntityType.cpp
src/lib/serviceRoutines/getEntityTypes.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
src/lib/serviceRoutinesV2/getEntityType.cpp
test/functionalTest/cases/1027_get_all_entity_types/get_all_entity_types.test
test/functionalTest/cases/1028_get_entity_type/get_entity_type.test
test/functionalTest/cases/1705_csub_cache_objects/csub_cache_string_filter_update.test

Fixes #1833 and bullet 2 in #1636 
LGTM needed from:
@crbrox 
@kzangeli 
Be aware of and nice-to-have feedback:
@jmcanterafonseca 
@iariasleon

Fixes in GET /v2/types and GET /v2/types/T operations

---

scripts/build/fiwarelab/build-fiwarelab-image.sh

@fgalan 
Resolve a problem in the specification of fiware yum repositorie due to it try to resolve the variable.
Created the new release of the Orion following the changes with the new fiware yum repository.

Resolve a problem in the specification of the yum repository

---

src/lib/mongoBackend/mongoQueryTypes.cpp

Bug recently introduced in a past PR.

FIX attributes not shown in get types operation when attributes use metadata ID

---

scripts/managedb/csubs_control/csub_dups_checker.py

FIX csub dup script: status and description fields out of csub signature

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
doc/manuals/user/service_path.md
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp

Fixed #1961
No need of new test harness: behave test will cover this. In addition, no need of CNR entry for an "internal" fix like this, without effect in the functionality.

FIX bug #1961

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1952_sub_notification_wo_attrs/1952_sub_notification_wo_attrs.test

@fgalan 
@kzangeli 
fixed #1952

Fix bug 1952 opt attrs in subs notification

---

test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/api_entry_point/retrieve_api_resource.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_2.feature
test/acceptance/behave/requirements.txt

[CHANGES] to jenkins

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/rest/StringFilter.cpp
src/lib/rest/StringFilter.h
test/functionalTest/cases/1306_string2double/string2double_not_a_number.test
test/functionalTest/cases/1607_query_with_q_and_ranges_but_invalid_operator/query_with_q_and_ranges_but_invalid_operator.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_greater_or_equal_than.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_greater_than.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_inside_range.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_less_or_equal_than.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_less_than.test
test/functionalTest/cases/1945_filter_string_comparison/csub_filter_string_outside_range.test
test/functionalTest/cases/1945_filter_string_comparison/filter_string_comparison.test

Implements #1945
Note that some existing .test has reduced their scope, as some cases that previously result in error after this PR are no longer errors.
@kzangeli
@crbrox

ADD string support in <, >, <=, >= and range filters

---

src/lib/rest/StringFilter.cpp

Fixed a bug introduced in PR #2036

FIX StringFilterItem::compatibleType()

---

src/lib/apiTypesV2/Subscription.cpp

FIX JSON broken in NGSIv2 csub renders

---

scripts/build/osDistro.sh

Fix issue https://github.com/telefonicaid/fiware-orion/issues/2045
@iariasleon

FIX osDistro.sh script to support RHEL 6.7

---

test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature

[REVIEW] bugs: 2014, 2042, 2043, 2046 and 2056

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription.feature >> passed: 50, failed: 0, skipped: 0 and total: 50 with duration: 47.978 seconds.
Date: Thursday, April 21, 2016 15:58:22
50 scenarios passed, 0 failed, 0 skipped
270 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m47.978s
```
`retrieve_entity_types.feature` file is modified because I forgot remove the skip tag in a scenario

[FEATURE] create subcriptions - modifying headers

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

ADD attribute value matter filter descripion to NGSIv2 spec

---

src/lib/rest/rest.cpp
test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_traces_in_log.feature

```
SUMMARY:
- components/ngsiv2/entities/create_entity/create_entity_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 1.056 seconds.
- components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 1.476 seconds.
- components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 1.247 seconds.
- components/ngsiv2/attributes/update_attribute_data/update_attribute_data_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 1.601 seconds.
- …
```

[FEATURE] corr in log traces

---

test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats_order.test
test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats_order_in_values.test
test/functionalTest/testDiff.py

A complement of #1875 , increasing test cases coverage (in particular, attribute orderin in notifications for keyValues and default NGSIv2 notification formats).
@crbrox 
@kzangeli

ADD new test to check attribute order in notifications also in no-value modes

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1316_create_subscription/post_subs_errors.test
test/functionalTest/cases/1661_bad_input_on_notification_error/bad_input_on_notification_error.test
test/functionalTest/cases/1661_bad_input_on_notification_error/bad_input_on_notification_error_with_relogged_alarms.test
test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test

Fixes #2092 
@kzangeli 
@crbrox

FIX urls that make Orion to crash

---

makefile
src/lib/rest/httpRequestSend.cpp
src/lib/rest/rest.cpp
test/functionalTest/cases/CMakeLists.txt
test/functionalTest/testHarness.sh

@kzangeli 
@crbrox 
Note this PR slightly changes the code. I understand that is safe to merge during the de-leak period, as the changes are very minor and with controlled impact from the point of view of leaks.

FIX problems running some tests under coverage target

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/EntityId.cpp
src/lib/ngsi/Scope.cpp
src/lib/rest/rest.cpp

The title says it all.
Actually, one comment line was indented also ...

Fixed 3 leaks

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Editors & Acknowledgements section

---

doc/manuals/admin/logs.md

FIX minor fixes in logs.md doc

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature

```
SUMMARY:
- components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription.feature >> passed: 50, failed: 0, skipped: 0 and total: 50 with duration: 1.157 seconds.
- components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification.feature >> passed: 47, failed: 0, skipped: 61 and total: 108 with duration: 4.559 seconds.
- components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature >> passed: 97, failed: 0, skipped: 156 and total: 253 with duration: 5.615 seconds.
- components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature >> passed: 123, failed: 0, skipped: 47 and …
```

[FEATURE] create subscription - notification fields using ngsiv2

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/entities/get_steps.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/__init__.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/environment.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/steps/__init__.py
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/steps/step.py

```
SUMMARY:
- components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes.feature >> passed: 201, failed: 0, skipped: 0 and total: 201 with duration: 17.422 seconds.
Date: Wednesday, May 04, 2016 15:13:23
201 scenarios passed, 0 failed, 0 skipped
1247 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m17.422s
```

[FEATURE] retrieve entity attributes using NGSI v2

---

src/lib/apiTypesV2/CMakeLists.txt
src/lib/apiTypesV2/HttpInfo.cpp
src/lib/apiTypesV2/HttpInfo.h
src/lib/apiTypesV2/Subscription.cpp
src/lib/apiTypesV2/Subscription.h
src/lib/mongoBackend/mongoGetSubscriptions.cpp
test/unittests/mongoBackend/mongoGetSubscriptions_test.cpp

+ added fields for template subscriptions/notifications

Http => HttpInfo in separate module

---

doc/manuals/contribution_guidelines.md

@crbrox 
@kzangeli 
Please implement directly in the PR any English language fix.

ADD S13 rule and object passing and strings return design patterns

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/serviceRoutines/getEntityTypes.cpp
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
test/functionalTest/cases/1027_get_all_entity_types/get_all_entity_types.test
test/functionalTest/cases/2115_wrong_count_no_entity_types/wrong_count_no_entity_types.test
test/unittests/mongoBackend/mongoQueryTypes_test.cpp
test/unittests/unittest.cpp
test/unittests/unittest.h

Fixes #2115 
Some cleaning in NGSIv1 logic also, for the same price ;)
@kzangeli 
@iariasleon

FIX total count return in GET /v2/types operation

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/2106_wrong_text_payload_string_filter_subscription_error/wrong_text_payload_string_filter_subscription_error.test

Fixes #2106 
@crbrox 
@kzangeli

FIX wrong text payload when subscription string filter error occurs

---

CHANGES_NEXT_RELEASE
doc/apiary/v2/fiware-ngsiv2-reference.apib
src/lib/rest/StringFilter.cpp
test/functionalTest/cases/1903_colon_as_double_equal_synonym/csub_filter_colon_as_enum.test
test/functionalTest/cases/1903_colon_as_double_equal_synonym/csub_filter_colon_as_equal.test
test/functionalTest/cases/1903_colon_as_double_equal_synonym/csub_filter_colon_as_range.test
test/functionalTest/cases/1903_colon_as_double_equal_synonym/filter_query_colon.test

Implements #1903 
@kzangeli 
@crbrox

ADD ':' as alias for '==' in the NGSIv2 Simple Query Language

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoQueryTypes.h
src/lib/orionTypes/EntityTypeVectorResponse.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
test/functionalTest/cases/1027_get_all_entity_types/get_all_entity_types.test
test/functionalTest/cases/1170_get_types_values_option/get_types_values_option.test
test/functionalTest/cases/1170_get_types_values_option/get_types_values_option_with_empty_type_entities.test
test/functionalTest/cases/1170_get_types_values_option/get_types_values_option_with_null_and_empty_types.test
test/functionalTest/cases/1170_get_types_values_option/get_types_values_option_with_null_type_entities.test

Implements #1170 
@crbrox 
@kzangeli

options=values for GET /v2/types operation

---

src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoBackend/mongoCreateSubscription.cpp
src/lib/mongoBackend/mongoCreateSubscription.h
test/unittests/CMakeLists.txt
test/unittests/mongoBackend/mongoCreateSubscription_test.cpp

ADD mongoCreateSubscription() stub

---

src/lib/apiTypesV2/HttpInfo.cpp
src/lib/apiTypesV2/HttpInfo.h

ADD extended field to HttpInfo class

---

src/lib/rest/StringFilter.cpp

Fixed a bug in StringFilterItem::parse

---

src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/ngsi/NotifyConditionVector.cpp
src/lib/ngsi/NotifyConditionVector.h

Changed signature of subCacheItemInsert

---

src/lib/cache/subCache.cpp
src/lib/cache/subCache.h
src/lib/mongoBackend/mongoSubscribeContext.cpp

HttpInfo as parameter to subCacheItemInsert, instead of just the url string
[ make test running, ready by 16.35, if all goes smoothly ]

New signature for subCacheItemInsert

---

src/lib/apiTypesV2/SubscriptionUpdate.h
test/unittests/rest/Verb_test.cpp

Fix missing copyright header
@kzangeli @fgalan

Add copyright header

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/forbidden_characters.md

Doc part of #2015 
@kzangeli 
@jmcanterafonseca 
@mrutid

ADD functional description of templating mechanism in documentation

---

src/lib/apiTypesV2/SubscriptionUpdate.h
src/lib/mongoBackend/MongoCommonSubscription.cpp
src/lib/mongoBackend/mongoUpdateSubscription.cpp
src/lib/ngsi10/UpdateContextSubscriptionRequest.cpp

This PR contain pending changes in PR #2152 
@kzangeli

FIX issues raised in a (previous) PR

---

test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_queries_parameters.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_traces_in_log.feature

@kzangeli  @crbrox 
```
SUMMARY:
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes.feature >> passed: 201, failed: 0, skipped: 0 and total: 201 with duration: 43.250 seconds.
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes_queries_parameters.feature >> passed: 37, failed: 0, skipped: 1 and total: 38 with duration: 4.177 seconds.
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 3.033 seconds.
Date: Thursday, May 05, 2016 12:40:55
3 features passed, 0 failed, …
```

[FEATURE] queries parameters in retrieve entity attributes request

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoCreateSubscription.cpp
src/lib/mongoBackend/mongoCreateSubscription.h
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoSubscribeContext.h
src/lib/mongoBackend/mongoUpdateSubscription.cpp
src/lib/serviceRoutines/postSubscribeContext.cpp
src/lib/serviceRoutinesV2/postSubscriptions.cpp

FIX -noCache now avoids populating cache on create/update subscription operations

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature

[REVIEW] bug: 2106 and 2115

---

test/acceptance/behave/behave.ini
test/acceptance/behave/environment.py

@fgalan 
Use the behave `context` instead of `global` variables

[REFACTOR] in environment.py and behave.ini files

---

CHANGES_NEXT_RELEASE
makefile
src/lib/apiTypesV2/Subscription.cpp
src/lib/apiTypesV2/Subscription.h
src/lib/common/RenderFormat.cpp
src/lib/common/RenderFormat.h
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
test/functionalTest/cases/1048_subscription_cache/csub_update_with_notif.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subs_pagination.test
test/functionalTest/cases/1126_GET_v2_subscriptions/GET_v2_all_subscriptions.test
test/functionalTest/cases/1316_create_subscription/post_subscriptions.test
test/functionalTest/cases/1317_GET_v2_subscription/get_subscription.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_notif_nocache.test
test/functionalTest/cases/1577_servicepath_get_subs/get_subs_with_servicepath.test
test/functionalTest/cases/1658_v2_patch_subscription/patch_subscriptions.test
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv1.test
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv2.test
test/functionalTest/cases/1852_escaped_slashes_in_json_v1_payload/escaped_slashes_in_json_v1_payload.test
test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats.test
test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats_order.test
test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats_order_in_values.test
test/functionalTest/cases/1918_csub_description_field/csub_description.test
test/functionalTest/cases/1949_permanent_subscriptions/1949_permanent_get.test
test/functionalTest/cases/1952_sub_notification_wo_attrs/1952_sub_notification_wo_attrs.test
test/functionalTest/cases/2163_bug_attrs_format_not_stored/bug_attrs_format_not_stored.test

FIX processing/rendering of attrsFormat

---

src/lib/apiTypesV2/HttpInfo.cpp
src/lib/apiTypesV2/HttpInfo.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoUpdateSubscription.cpp
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/2015_notification_templates/notification_templates.test
test/functionalTest/cases/2015_notification_templates/notification_templates_many_notifications.test
test/functionalTest/cases/2015_notification_templates/notification_templates_with_decoded_chars_in_notifications.test

The title says it all ...
Also fixed a few functests from a previous PR, about the mime-type.

subscription templates now work for the noCache case as well

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/cli.md
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/2135_disable_custom_notifications_cli/disble_custom_notifications_cli.test
test/unittests/main_UnitTest.cpp

ADD -disableCustomNotifications CLI

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_1.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature
test/acceptance/behave/tools/NGSI_v2.py

```
Date: Thursday, May 26, 2016 16:20:33
55 features passed, 0 failed, 0 skipped
5534 scenarios passed, 0 failed, 579 skipped
39570 steps passed, 0 failed, 6471 skipped, 0 undefined
Took 5m51.490s
```

[REFACTOR] feature changes in integration environment

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

As discussed in the FIWARE Ngsi mailing list.
Deadline to merge this PR: Monday May 30th EoB.

Change 'date' to 'DateTime' for meaning a date time in the NGSIv2 specification

---

doc/manuals/admin/cli.md
doc/manuals/admin/diagnosis.md
doc/manuals/admin/perf_tuning.md
doc/manuals/user/README.md

Doc corresponding to issue #2166 
In addition, some fixes to user/README.md (missing links to two files added in a past PR).
**Note it is safe to merge this PR given it doesn't include code modifications.**
@crbrox

FIX file descriptors sizing documentation

---

CHANGES_NEXT_RELEASE
src/lib/cache/subCache.cpp

Infinite loop in sub-cache synch function fixed

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Algorithm for Get Attribute Value improved as suggested in #1849. 
@marcc-orange it would be great if you could review this PR and provide feedback. I have introduced some modifications on your original text in order to cover the  `Accept: */*` case and to make it more structured (i.e. two levels bullet list). I hope you find modifications fine :)
Deadline for merging: May 31st EoB (time enough to review so samll PR, +9 -13 lines).

FIX NGSIv2 spec get attribute value MIME type chosing algorithm

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib

Just to create a copy of existing .apib file.
The only interesting review that could be done in this branch is just to compare MD5SUM of both files (new an existing) to check they are exactly equal.

ADD new .apib file for stable release candidate May 2016

---

README.md
doc/apiary/v2/fiware-ngsiv2-cookbook-rc-2016_05_31.apib

This PR just does a copy of cookbook .apib, to set the stable release.

ADD RC copy for cookbook

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/2237_compound_values_in_forwarded_messages/compound_values_in_forwarded_messages.test
test/functionalTest/cases/2237_compound_values_in_forwarded_messages/compound_values_in_forwarded_messages_exactly_as_issue.test

Issue #2237 fixed
[ This fix includes cloning of compound values so the valgrind test suite should be run ]

Bug/2237 compound values in forwarded messages (release/1.2.0)

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/putEntityAttributeValue.cpp
test/functionalTest/cases/2246_attr_type_change_in_local/attr_type_change_in_local.test

Issue #2246 fixed (release/1.2.0)

---

CHANGES_NEXT_RELEASE
src/lib/rest/StringFilter.cpp
test/functionalTest/cases/2222_notif_not_sent_on_true/notif_not_sent_on_true.test

Fix subscription equal filter evaluation on update context logic (release/1.2.0)

---

CHANGES_NEXT_RELEASE
test/functionalTest/cases/2248_forwarding_updates_overwrite_the_types_of_attributes/attribute_type_converted_to_string_on_forward.test
test/functionalTest/cases/2248_forwarding_updates_overwrite_the_types_of_attributes/forwarding_updates_overwrite_the_types_of_attributes.test
test/functionalTest/cases/2248_forwarding_updates_overwrite_the_types_of_attributes/int_converted_to_string_on_forward.test

#2248 already fixed - this is just a functest to make sure it 'stays fixed'

Functest for issue 2248, issue fixed when 2246 was fixed (release/1.2.0)

---

src/lib/jsonParseV2/parseSubscription.cpp

freeing regex after validity check

---

src/lib/jsonParseV2/parseSubscription.cpp

freeing regex after validity check (develop)

---

src/lib/jsonParseV2/parseSubscription.cpp
src/lib/parse/forbiddenChars.cpp
src/lib/parse/forbiddenChars.h
test/functionalTest/cases/0876_entity_dates/filter_datemodified_sub.test
test/functionalTest/cases/1316_create_subscription/post_subs_errors.test
test/functionalTest/cases/1316_create_subscription/post_subscriptions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_errors.test
test/functionalTest/cases/1654_del_subs_v2/delete_subs_v2.test
test/functionalTest/cases/1658_v2_patch_subscription/patch_subscriptions.test
test/functionalTest/cases/1693_preserve_sp_updating_subscription/preserve_sp_updating_subscription_ngsiv2.test
test/functionalTest/cases/1918_csub_description_field/csub_description.test
test/functionalTest/cases/1947_1972_invalid_subs_crash/1947_1972_invalid_subs_crash.test
test/functionalTest/cases/1949_permanent_subscriptions/1949_permanent_get.test
test/functionalTest/cases/1952_sub_notification_wo_attrs/1952_sub_notification_wo_attrs.test
test/functionalTest/cases/2092_incorrect_url_bug/check_incorrect_urls.test

Add validations in parsing the subscriptions

---

doc/manuals/admin/logs.md

Please don't delete branch after merging.

Doc: logs.md mentioning that Orion prints using UTC

---

src/lib/jsonParseV2/parseSubscription.cpp

Fix Empty() -> ObjectEmpty()

---

doc/apiary/v2/fiware-ngsiv2-cookbook-rc-2016_05_31.apib
doc/apiary/v2/fiware-ngsiv2-cookbook.apib

Cookbook updated due to #2201 as requested in https://github.com/Fiware/tutorials.TourGuide-App/issues/114

Change 'date' to 'DateTime' in the Cookbook.

---

src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1316_create_subscription/post_subs_errors.test

Make condition in subject optional

---

src/lib/jsonParseV2/parseSubscription.cpp

@fgalan 
@kzangeli 
FYI: @iariasleon 
closes #2018 #2095 #2099

Add validation for attr names in subscriptions

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_http.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_notification_http.feature >> passed: 72, failed: 0, skipped: 73 and total: 145 with duration: 15.520 seconds.
Date: Wednesday, June 15, 2016 14:48:26
72 scenarios passed, 0 failed, 73 skipped
396 steps passed, 0 failed, 365 skipped, 0 undefined
Took 0m15.520s
```
@kzangeli @crbrox @fgalan

[FEATURE] subscription notification http - ngsi v2

---

doc/manuals/user/ngsiv2_implementation_notes.md

Don't delete branch after merge.

ADD NGSIv2 CPr fwd considerations to doc

---

doc/manuals/user/ngsiv2_implementation_notes.md
doc/manuals/user/v1_v2_coexistence.md

Ammend PR https://github.com/telefonicaid/fiware-orion/pull/2283

NGSIv2 ops with CPr doc fixes (release/1.2.0)

---

doc/manuals/user/v1_v2_coexistence.md

A kind of mirror of PR #2283 + PR #2285.
Hoever, note that the last bullet is sligthly different, compared with release/1.2.0 version.

FIX NGSIv2 CPr doc (develop)

---

src/lib/jsonParseV2/parseSubscription.cpp

@fgalan 
@kzangeli 
FYI: @iariasleon 
it should fix #2100 #1980 #1974 #1965
covered by QA tests

Add length validations in subs

---

CHANGES_NEXT_RELEASE
test/functionalTest/cases/1785_error_on_empty_attr_type/error_on_empty_attr_type.test

Just a functest, this issue has been fixed already as it seems.

Functest for issue 1785

---

makefile

Attemp to fix coverage metrics in central sonar

FIX sonar_metrics target

---

test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value.feature

[REVIEW] bug 1360

---

doc/manuals/user/ngsiv2_implementation_notes.md
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_expires.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_expires.feature >> passed: 15, failed: 0, skipped: 24 and total: 39 with duration: 5.087 seconds.
Date: Monday, June 20, 2016 09:40:12
15 scenarios passed, 0 failed, 24 skipped
79 steps passed, 0 failed, 120 skipped, 0 undefined
Took 0m5.087s
```
@kzangeli @fgalan @crbrox

[FEARTURE] subscription expires using ngsi v2

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/apiary/v2/fiware-ngsiv2-reference.errata

The ngsiv2 spec a little clearer about 'condition' in subscriptions.
Ah, and an error encountered and fixed.

clearly stating that condition is optional

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_description.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_description.feature >> passed: 5, failed: 0, skipped: 6 and total: 11 with duration: 0.731 seconds.
Date: Monday, June 20, 2016 12:01:31
5 scenarios passed, 0 failed, 6 skipped
29 steps passed, 0 failed, 30 skipped, 0 undefined
Took 0m0.731s
```
@crbrox @kzangeli @fgalan

[FEATURE] subscription description using ngsi v2

---

doc/apiary/v2/fiware-ngsiv2-reference.errata
scripts/check_files_compliance.py

Added 'errata' suffix for check_files_compliance.py, and a copyright header for the errata file, to avoid problems ...

Added 'errata' suffix for check_files_compliance.py

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_throttling.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_throttling.feature >> passed: 16, failed: 0, skipped: 0 and total: 16 with duration: 4.012 seconds.
Date: Monday, June 20, 2016 14:19:59
16 scenarios passed, 0 failed, 0 skipped
89 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m4.012s
```
@kzangeli @fgalan @crbrox

[FEATURE] subscription throttling using ngsi v2

---

src/lib/jsonParseV2/parseSubscription.cpp

Fixes #2308 
@fgalan 
@kzangeli 
FYI: @iariasleon 
Covered by QA tests

Do not allow forbidden charsin description for subscription

---

CHANGES_NEXT_RELEASE
src/lib/common/errorMessages.h
src/lib/serviceRoutines/badVerbAllFive.cpp
src/lib/serviceRoutines/badVerbAllFour.cpp
src/lib/serviceRoutines/badVerbGetDeleteOnly.cpp
src/lib/serviceRoutines/badVerbGetOnly.cpp
src/lib/serviceRoutines/badVerbGetPostDeleteOnly.cpp
src/lib/serviceRoutines/badVerbGetPostOnly.cpp
src/lib/serviceRoutines/badVerbGetPutDeleteOnly.cpp
src/lib/serviceRoutines/badVerbPostOnly.cpp
src/lib/serviceRoutines/badVerbPutDeleteOnly.cpp
src/lib/serviceRoutines/badVerbPutOnly.cpp
src/lib/serviceRoutinesV2/badVerbAllNotDelete.cpp
src/lib/serviceRoutinesV2/badVerbGetDeletePatchOnly.cpp
src/lib/serviceRoutinesV2/badVerbGetPutOnly.cpp
test/functionalTest/cases/0999_update_single_attr_value_by_eid/update_single_attr_value_by_eid_fake_field_cases.test
test/functionalTest/cases/1305_all_tests_empty_payload/all_tests_empty_payload.test
test/functionalTest/cases/1582_alarmManager/alarm_manager_bad_input.test
test/functionalTest/cases/1585_log_summary/log_summary.test
test/functionalTest/cases/1697_more_than_one_bad_input/more_than_one_bad_input.test
test/functionalTest/cases/1913_log_level_change_via_rest/log_level_change_via_rest.test
test/functionalTest/cases/2075_no_payload_in_error_response/no_payload_in_error_response.test

Fixed issue #2075, about no payload in 405 errors in NGSIv2 requests.
Issues #2078 and #2083 also fixed by this PR.

Fixed issue 2075

---

makefile
scripts/build/sonarProperties.sh

Removes the comments introduced by PRs https://github.com/telefonicaid/fiware-orion/pull/2304 and 
https://github.com/telefonicaid/fiware-orion/pull/2299.

Removing old comments

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Entity.cpp
src/lib/serviceRoutinesV2/getEntity.cpp
test/functionalTest/cases/2241_fix_attrs_filter/fix_attrs_filter.test

FIX proper response for 'GET /v2/entities/<id>?attrs=<attrName>' and …'GET /v2/entities/<id>/attrs?attrs=<attrName>' when <attrName> doesn't exist

---

test/functionalTest/cases/2086_allow_trailing_semicolon/allow_trailing_semicolon.test

Fixed a broken copyright header in a functest

---

test/functionalTest/cases/2086_allow_trailing_semicolon/allow_trailing_semicolon.test

Fixed copyright header for functest

---

makefile

Removed style guide checking from make target 'release'

Removed style guide checking from make target 'release'

---

CHANGES_NEXT_RELEASE
doc/manuals/user/v1_v2_coexistence.md
src/lib/ngsi/Metadata.cpp
test/functionalTest/cases/2339_json_native_types_in_v1/json_native_types_in_v1.test

Fixes part of #1068
Correct rendering of metadata values in v1

Correct rendering of metadata values in v1

---

test/functionalTest/cases/2339_json_native_types_in_v1/json_native_types_in_v1.test

Fixed other occurrences of 3.140000000001

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/dbConstants.h
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/Metadata.cpp
src/lib/ngsi/Metadata.h
test/functionalTest/cases/1112_metadata_as_keymap/metadata_with_dots_v1.test
test/functionalTest/cases/1112_metadata_as_keymap/metadata_with_dots_v2.test
test/functionalTest/cases/2339_json_native_types_in_v1/json_native_types_in_v1.test
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

Implements #1112 
This PR include changes in the code and data model documentation. Migration script and related documentation will be part of a next PR.
@kzangeli

Metadata as keymap

---

doc/manuals/user/README.md
doc/manuals/user/regex_in_payload.md
mkdocs.yml

Implement documentation changes related with #2142 
@kzangeli 
@dmoranj

ADD clarificationa about regex usage in payloads to documentation

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/dbConstants.h
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoSubCache.cpp
test/unittests/mongoBackend/mongoCreateSubscription_test.cpp
test/unittests/mongoBackend/mongoGetSubscriptions_test.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptionsNoCache_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptions_test.cpp

Code and documentation parts for #1851

Csubs data model simplification

---

test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity.feature

[ADD] new scenario with issue 2364

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/apiary/v2/fiware-ngsiv2-reference.errata

This PR includes (partially) the changes described in #1156 in the WIP .apib file of the NGSIv2 specification.
@kzangeli
Feedback is welcome!
Merging deadline: Friday July 15th EoB.

NGSIv2 spec: 'q' (and new 'mq' filter) for structured attribute values and metadata

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

This PR includes the changes described in #2223 in the WIP .apib file of the NGSIv2 specification.
@kzangeli 
@jmcanterafonseca 
Feedback is welcome!
Merging deadline: Friday July 15th EoB.

NGSIv2 spec: default types for entities and attributes

---

doc/manuals/admin/upgrading_crossing_1-3-0.md
scripts/managedb/csub_merge_condvalues.py
scripts/managedb/mdsvector2mdsobject.py

Part of #1851 
It has been tested with real data coming from orion.lab. In addition, all the skip conditions has been manually tested with "hacked" documents at csub.

DB migration script (+doc): csub collection

---

scripts/accumulator-server.py
src/lib/serviceRoutines/postQueryContext.cpp
test/functionalTest/cases/2360_cpr_invalid_response/cpr_invalid_response.test

FIX CB response break when CPr response has parse errors

---

docker/Dockerfile

Some comments related with changes to Dockerfile introduced in PR https://github.com/telefonicaid/fiware-orion/pull/2358
@cesarjorgemartinez

ADD detail to some dockefile comments

---

test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_traces_in_log.feature

```
`                    SUMMARY:
- components\ngsiv2\entities\list_entities\list_entities_attributes.feature >> passed: 148, failed: 0, skipped: 0 and total: 148 with duration: 129.078 seconds.
- components\ngsiv2\entities\list_entities\list_entities_headers.feature >> passed: 49, failed: 0, skipped: 1 and total: 50 with duration: 27.235 seconds.
- components\ngsiv2\entities\list_entities\list_entities_queries_parameters_part_1.feature >> passed: 141, failed: 0, skipped: 4 and total: 145 with duration: 163.785 seconds.
- components\ngsiv2\entities\list_entities\list_entities_queries_parameters_part_2.feature >> passed: 132, failed: 0, skipped: 0 and total: 132 with duration: 252.324 seconds.
- …
```

[FEATURE] issue 2128 apply GET list entities - traces in log

---

test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part2.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes.feature

[REVIEW] bugs 2083, 2078 and 2075 in acceptance tests

---

test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value_part2.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_part3.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature

[REVIEW] bugs: 1939, 1909, 1890, 1887, 1886, 1487, 1426 and 1112 tests associated

---

test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data_part3.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_part3.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part3.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_part3.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_part3.feature

[FIX] issue 1068 tests

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data.feature

```
SUMMARY:
- components\ngsiv2\attributes\get_attribute_data\get_attribute_data.feature >> passed: 247, failed: 0, skipped: 7 and total: 254 with duration: 71.756 seconds.
Date: Tuesday, July 26, 2016 10:15:09
247 scenarios passed, 0 failed, 7 skipped
1776 steps passed, 0 failed, 56 skipped, 0 undefined
Took 1m11.756s
```
See the issue #2128 

[FIX] regression test in get attribute data test suite

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value_part2.feature

```
SUMMARY:
- components\ngsiv2\attributes_values\update_attribute_value\update_attribute_value.feature >> passed: 123, failed: 0, skipped: 0 and total: 123 with duration: 46.278 seconds.
- components\ngsiv2\attributes_values\update_attribute_value\update_attribute_value_part2.feature >> passed: 207, failed: 0, skipped: 7 and total: 214 with duration: 104.687 seconds.
- components\ngsiv2\attributes_values\update_attribute_value\update_attribute_value_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.955 seconds.
Date: Wednesday, July 27, 2016 11:27:16
3 features passed, 0 failed, 0 skipped
331 scenarios …
```

[FIX] tests review in update attribute value test suites

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_part3.feature

```
`
SUMMARY:
- components\ngsiv2\entities\create_entity\create_entity.feature >> passed: 148, failed: 0, skipped: 0 and total: 148 with duration: 63.652 seconds.
- components\ngsiv2\entities\create_entity\create_entity_part2.feature >> passed: 235, failed: 0, skipped: 0 and total: 235 with duration: 53.038 seconds.
- components\ngsiv2\entities\create_entity\create_entity_part3.feature >> passed: 311, failed: 0, skipped: 0 and total: 311 with duration: 66.467 seconds.
- components\ngsiv2\entities\create_entity\create_entity_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.800 seconds.
Date: Wednesday, July 27, 2016 14:28:14 …
```

[FIX] tests review in create entity test suites

---

test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part2.feature

```
SUMMARY:
- components\ngsiv2\entities\replace_all_entity_attributes\replace_all_entity_attributes.feature >> passed: 262, failed: 0, skipped: 0 and total: 262 with duration: 126.494 seconds.
- components\ngsiv2\entities\replace_all_entity_attributes\replace_all_entity_attributes_part2.feature >> passed: 222, failed: 0, skipped: 0 and total: 222 with duration: 78.301 seconds.
- components\ngsiv2\entities\replace_all_entity_attributes\replace_all_entity_attributes_part3.feature >> passed: 113, failed: 0, skipped: 0 and total: 113 with duration: 46.295 seconds.
- components\ngsiv2\entities\replace_all_entity_attributes\replace_all_entity_attributes_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 5.308 …
```

[FIX] tests review in replace entity test suites

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_queries_parameters.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes.feature >> passed: 210, failed: 0, skipped: 1 and total: 211 with duration: 85.870 seconds.
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes_queries_parameters.feature >> passed: 37, failed: 0, skipped: 1 and total: 38 with duration: 10.457 seconds.
- components\ngsiv2\entities\retrieve_entity_attributes\retrieve_entity_attributes_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 5.689 seconds.
Date: Thursday, July 28, 2016 10:40:11
3 features passed, 0 failed, 0 skipped
248 …
```

[FIX] tests review in retrieve entity attributes test suites

---

test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_part2.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_part3.feature

```
SUMMARY:
- components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attrib
- components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attribonds.
- components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attribonds.
- components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attrib
- components\ngsiv2\entities\update_existing_entity_attributes\update_existing_entity_attribeconds.
Date: Friday, July 29, 2016 09:25:21
5 features passed, 0 failed, 0 skipped
617 scenarios passed, 0 failed, 25 skipped
4424 steps passed, 0 failed, 160 …
```

[FIX] tests review in update existing entity attributes test suites

---

test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_part4.feature

```
SUMMARY:
- components\ngsiv2\entities\update_or_append_entity_attributes\update_or_append_entity_attributes.feature >> passed: 213, failed: 0, skipped: 0 and total: 213 with duration: 83.989 seconds.
- components\ngsiv2\entities\update_or_append_entity_attributes\update_or_append_entity_attributes_part2.feature >> passed: 269, failed: 0, skipped: 0 and total: 269 with duration: 138.834 seconds.
- components\ngsiv2\entities\update_or_append_entity_attributes\update_or_append_entity_attributes_part3.feature >> passed: 284, failed: 0, skipped: 0 and total: 284 with duration: 125.462 seconds.
- components\ngsiv2\entities\update_or_append_entity_attributes\update_or_append_entity_attributes_part4.feature >> passed: 67, failed: 0, skipped: 0 …
```

[FIX] tests review in update or append entity attributes test suites

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/perf_tuning.md
doc/manuals/user/forbidden_characters.md
doc/manuals/user/known_limitations.md
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
test/functionalTest/cases/1316_create_subscription/post_subs_errors.test
test/functionalTest/cases/1316_create_subscription/post_subscriptions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions.test
test/functionalTest/cases/1328_pause_subscriptions/pause_subscriptions_errors.test
test/functionalTest/cases/1654_del_subs_v2/delete_subs_v2.test
test/functionalTest/cases/1658_v2_patch_subscription/patch_subscriptions.test
test/functionalTest/cases/1678_geosubscriptions/geosubscriptions.test
test/functionalTest/cases/1678_geosubscriptions/geosubscriptions_errors.test
test/functionalTest/cases/1678_geosubscriptions/geosubscriptions_plus_q_filter.test
test/functionalTest/cases/1918_csub_description_field/csub_description.test
test/functionalTest/cases/1947_1972_invalid_subs_crash/1947_1972_invalid_subs_crash.test
test/functionalTest/cases/1949_permanent_subscriptions/1949_permanent_get.test
test/functionalTest/cases/1952_sub_notification_wo_attrs/1952_sub_notification_wo_attrs.test

Geosubscriptions

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_description.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_expires.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_attrs.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_description.feature >> passed: 15, failed: 0, skipped: 0 and total: 15 with duration: 2.928 seconds.
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_expires.feature >> passed: 34, failed: 0, skipped: 5 and total: 39 with duration: 4.484 seconds.
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_headers.feature >> passed: 50, failed: 0, skipped: 0 and total: 50 with duration: 11.154 seconds.
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_notification_attrs.feature >> passed: 68, failed: 0, skipped: 4 and total: 72 with duration: …
```

[FIX] tests review in create a new subscription test suites

---

test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\types\retrieve_an_entity_type\retrieve_an_entity_type.feature >> passed: 74, failed: 0, skipped: 1 and total: 75 with duration: 52.511 seconds.
- components\ngsiv2\types\retrieve_an_entity_type\retrieve_an_entity_type_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 7.995 seconds.
Date: Friday, July 29, 2016 12:35:31
75 scenarios passed, 0 failed, 1 skipped
951 steps passed, 0 failed, 30 skipped, 0 undefined
Took 1m0.506s
```

[FIX] tests review in retrieve an entity type test suites

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types_traces_in_log.feature

```
`                    SUMMARY:
- components\ngsiv2\types\retrieve_entity_types\retrieve_entity_types.feature >> passed: 83, failed: 0, skipped: 1 and total: 84 with duration: 92.571 seconds.
- components\ngsiv2\types\retrieve_entity_types\retrieve_entity_types_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 9.074 seconds.
Date: Friday, July 29, 2016 13:05:55
84 scenarios passed, 0 failed, 1 skipped
1278 steps passed, 0 failed, 30 skipped, 0 undefined
Took 1m41.645s
```

[FIX] tests review in retrieve entity types test suites

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/cli.md
doc/manuals/admin/logs.md
doc/manuals/admin/management_api.md
doc/manuals/admin/perf_tuning.md
src/app/contextBroker/contextBroker.cpp
src/lib/logMsg/logMsg.cpp
src/lib/logMsg/logMsg.h
src/lib/parseArgs/paBuiltin.cpp
src/lib/serviceRoutinesV2/logLevelTreat.cpp
src/lib/serviceRoutinesV2/logLevelTreat.h
test/functionalTest/cases/0000_cli/bool_option_with_value.test
test/functionalTest/cases/0000_cli/command_line_options.test
test/functionalTest/cases/0000_cli/tracelevel_without_logLevel_as_DEBUG.test
test/functionalTest/cases/2352_get_log_level/get_log_level.test

Implements #2352 (and a little part we missed regarding #2353 and WARNING -> WARN log level)

ADD operation to retrieve log level and WARNING -> WARN log level change

---

test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature

review tests to issue #2406 and changed a http code reason "Method Not Allowed"

[FIX] issue 2406 and http code

---

test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes_values/get_attribute_value/get_attribute_value_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\entities\update_or_append_entity_attributes\update_or_append_entity_attributes_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.778 seconds.
- components\ngsiv2\entities\create_entity\create_entity_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.154 seconds.
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.052 seconds.
- components\ngsiv2\attributes_values\get_attribute_value\get_attribute_value_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.979 seconds.
- …
```

[FEATURE] allign log format with iotp components

---

doc/apiary/orioncontextbroker.apib
doc/manuals/user/walkthrough_apiv1.md
doc/manuals/user/walkthrough_apiv2.md
scripts/accumulator-server.py
test/functionalTest/harnessFunctions.sh
test/heavyTest/heavyTest.sh

Implements https://github.com/telefonicaid/fiware-orion/issues/187

ADD CLI for accumulator-server.py script

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/2394_inconsistent_mdnames_after_update/inconsistent_mdnames_after_update.test

FIX correct mdNames in updates

---

CHANGES_NEXT_RELEASE
src/lib/parse/textParse.cpp
test/functionalTest/cases/2386_missing_citation_mark_error/missing_citation_mark_error.test

FIX return NGSIv2 error if citation-mark is missing 

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/admin/retrieve_log_level/__init__.py
test/acceptance/behave/components/ngsiv2/admin/retrieve_log_level/environment.py
test/acceptance/behave/components/ngsiv2/admin/retrieve_log_level/retrieve_log_level.feature
test/acceptance/behave/components/ngsiv2/admin/retrieve_log_level/steps/__init__.py
test/acceptance/behave/components/ngsiv2/admin/retrieve_log_level/steps/step.py

```
SUMMARY:
- components\ngsiv2\admin\retrieve_log_level\retrieve_log_level.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 0.098 seconds.
Date: Tuesday, August 02, 2016 12:06:50
1 scenario passed, 0 failed, 0 skipped
3 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.098s
```
@fgalan @kzangeli @crbrox 
issue associated #2352

[FEATURE] retrieve the log level

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/admin/change_log_level/__init__.py
test/acceptance/behave/components/ngsiv2/admin/change_log_level/change_log_level.feature
test/acceptance/behave/components/ngsiv2/admin/change_log_level/environment.py
test/acceptance/behave/components/ngsiv2/admin/change_log_level/steps/__init__.py
test/acceptance/behave/components/ngsiv2/admin/change_log_level/steps/step.py

```
SUMMARY:
- components\ngsiv2\admin\change_log_level\change_log_level.feature >> passed: 1, failed: 0, skipped: 14 and total: 15 with duration: 0.323 seconds.
Date: Wednesday, August 03, 2016 09:22:09
1 scenario passed, 0 failed, 14 skipped
3 steps passed, 0 failed, 90 skipped, 0 undefined
Took 0m0.323s
```
@fgalan @kzangeli @crbrox 
See issue #1913

[FEATURE] change log level

---

.gitignore
CHANGES_NEXT_RELEASE
src/lib/common/JsonHelper.cpp
src/lib/common/limits.h
src/lib/common/macroSubstitute.cpp
src/lib/common/string.cpp
src/lib/common/string.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp
test/functionalTest/cases/0000_statistics_operation/statistics_with_notifqueue.test
test/functionalTest/cases/1068_metadata_value_as_compound/metadata_value_as_compound_object.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_deeper.test
test/functionalTest/cases/1179_options_test/GET_v2_ent_attr_val_options_text.test
test/functionalTest/cases/1259_new_json_for_v2/get_attribute_value.test
test/functionalTest/cases/1849_attribute_values_and_multiple_accept_types/attribute_values_and_multiple_accept_types_for_number_attribute.test
test/functionalTest/cases/2015_notification_templates/custom_qs_and_headers_names.test
test/functionalTest/cases/2015_notification_templates/notification_templates.test
test/functionalTest/cases/2015_notification_templates/notification_templates_cache_refresh.test
test/functionalTest/cases/2015_notification_templates/notification_templates_many_notifications.test
test/functionalTest/cases/2015_notification_templates/notification_templates_payload_as_xml.test
test/functionalTest/cases/2176_not_print_spurious_decimals/not_print_spurious_decimals.test
test/functionalTest/cases/2176_not_print_spurious_decimals/one_to_nine_decimals.test
test/functionalTest/cases/2203_http_info_for_sub_update/http_info_for_sub_update.test
test/functionalTest/cases/2207_not_spurious_decimals_in_custom_notifications/not_spurious_decimals_in_custom_notifications.test
test/functionalTest/cases/2383_round_number_to_nine_digits/round_number_to_nine_digits.test

Fixes #2383, #2207, #2176 
@kzangeli 
@crbrox

FIX render float values with 9 digits precision in all cases, avoding spurious decimals

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

ADD more detail about Payload is too large error in NGSIv2 spec

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

ADD mention geo:xxxx types in Special Attribute Types section in the NGSIv2 spec

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_geospatial_properties_of_entities.feature

```
SUMMARY:
- components\ngsiv2\entities\create_entity\create_entity_geospatial_properties_of_entities.feature >> passed: 90, failed: 0, skipped: 0 and total: 90 with duration: 17.417 seconds.
Date: Thursday, August 04, 2016 12:38:19
90 scenarios passed, 0 failed, 0 skipped
400 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m17.417s
```
issues associated: https://github.com/telefonicaid/fiware-orion/issues/1038 and https://github.com/telefonicaid/fiware-orion/issues/1920

[FEATURE] geo-spatial values - create entity usig NGSI v2

---

mkdocs.yml

ADD google analytics for RTD

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/subscriptions/notification_steps.py
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/__init__.py
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/environment.py
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_expiration_and_status.feature
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_notification_attrs.feature
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_subject_entities.feature
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/steps/__init__.py
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/steps/step.py

```
SUMMARY:
- components\ngsiv2\subscriptions\notifications\notifications_expiration_and_status.feature >> passed: 6, failed: 0, skipped: 0 and total: 6 with duration: 9.063 seconds.
- components\ngsiv2\subscriptions\notifications\notifications_notification_attrs.feature >> passed: 19, failed: 0, skipped: 0 and total: 19 with duration: 25.150 seconds.
- components\ngsiv2\subscriptions\notifications\notifications_subject_entities.feature >> passed: 50, failed: 0, skipped: 0 and total: 50 with duration: 70.329 seconds.
Date: Friday, August 26, 2016 15:19:18
3 features passed, 0 failed, 0 skipped
75 scenarios passed, 0 failed, 0 skipped
676 …
```

[FEATURE] notifications using expires, status, entities and notif_attrs

---

test/acceptance/behave/components/ngsiv2/admin/change_log_level/change_log_level.feature

```
SUMMARY:
- components\ngsiv2\admin\change_log_level\change_log_level.feature >> passed: 15, failed: 0, skipped: 0 and total: 15 with duration: 20.647 seconds.
Date: Monday, August 29, 2016 14:48:25
15 scenarios passed, 0 failed, 0 skipped
99 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m20.647s
```

[REVIEW] bugs 2419 and 2420

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

FIX .apib document to make them work with Fabre for FIWARE R5 release

---

test/functionalTest/cases/1853_typePattern_3a/get_v2_entities.test.DISABLED
test/functionalTest/cases/1853_typePattern_3a/subcache_typepattern.test

Part of issue #1853.
One more functest for 1853 and a fix in 1853/subcache_typepattern.test.

One more functest for 1853 and a fix in 1853/subcache_typepattern.test

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_structured_content.feature

```
SUMMARY:
- components\ngsiv2\entities\list_entities\list_entities_structured_content.feature >> passed: 46, failed: 0, skipped: 0 and total: 46 with duration: 20.088 seconds.
Date: Wednesday, August 31, 2016 09:39:42
46 scenarios passed, 0 failed, 0 skipped
828 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m20.088s
```

[FEATURE] structured content en attributes using ngsi v2

---

doc/manuals/admin/build_source.md
docker/Dockerfile
scripts/bootstrap/centos65.sh
scripts/bootstrap/ubuntu1404.sh
test/unittests/commonMocks.h

FIX change URL to download gmock-1.5.0.tar.bz2 package

---

doc/manuals/user/walkthrough_apiv1.md
doc/manuals/user/walkthrough_apiv2.md

Fix broken links in documentation.

FIX link to install md

---

test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_expiration_throttling_and_status.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\notifications\notifications_expiration_throttling_and_status.feature >> passed: 8, failed: 0, skipped: 0 and total: 8 with duration: 26.094 seconds.
Date: Wednesday, September 07, 2016 13:03:20
8 scenarios passed, 0 failed, 0 skipped
86 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m26.094s
```

[FEATURE] notification throttling

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseMetadata.cpp
src/lib/ngsi/Metadata.cpp
test/functionalTest/cases/2443_mq_date_processing/mq_date_processing.test
test/functionalTest/cases/2445_mq_date_processing_subs/mq_date_processing_subs.test

Implements a fix for #2443 and  #2445

Fixes DateTime filters for mq

---

test/functionalTest/cases/2495_typepattern_on_sub_update/typepattern_on_sub_update.test

Funcional test to cover the case described in #2495

ADD unit test to cover the typePattern update case in csubs

---

test/functionalTest/cases/2490_query_url_regex_with_slash/query_url_regex_with_slash.test
test/functionalTest/cases/2494_query_payload_regex_with_slash/query_payload_regex_with_slash.test

Add .test for #2490 and for #2494

ADD new functional test cases to cover #2490 and #2494

---

test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_conditions.feature

Also a test is appended to bug 2442
@fgalan @crbrox @kzangeli

[REVIEW] tests associated to bug 2445

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_format.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\notifications\notifications_format.feature >> passed: 5, failed: 0, skipped: 0 and total: 5 with duration: 6.904 seconds.
Date: Tuesday, September 13, 2016 12:06:37
5 scenarios passed, 0 failed, 0 skipped
45 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m6.904s
```
@fgalan @crbrox @kzangeli

[FEATURE] notification format using ngsi v2

---

CHANGES_NEXT_RELEASE
src/lib/rest/StringFilter.cpp
test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_existence_subs.test

Fixes #2496 and additional (not reported yet) bug.

FIX metadata filter crashes and compound filtering bug

---

test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_template.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\notifications\notifications_template.feature >> passed: 10, failed: 2, skipped: 0 and total: 12 with duration: 18.870 seconds.
Date: Wednesday, September 14, 2016 13:07:41
Failing scenarios:
components\ngsiv2\subscriptions\notifications\notifications_template.feature:180  send a notification using NGSI v2 with custom templates and decimal number as value -- @2.1 # @ISSUE_2207
components\ngsiv2\subscriptions\notifications\notifications_template.feature:181  send a notification using NGSI v2 with custom templates and decimal number as value -- @2.2 # @ISSUE_2207
0 features passed, 1 failed, 0 …
```

[FEATURE] notification templates using ngsi v2

---

test/acceptance/behave/logging.ini
test/acceptance/behave/tools/notification_listener.py

Also, it is appended a new logger associated to `listener`

[ADD] new methods in the listener

---

test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\notifications\notifications_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 3.980 seconds.
Date: Thursday, September 15, 2016 09:47:52
1 scenario passed, 0 failed, 0 skipped
11 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m3.980s
```

[FEATURE] traces in log when a notification is sent

---

CHANGES_NEXT_RELEASE
docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h

@dmoranj 
Similar to PR https://github.com/telefonicaid/fiware-orion/pull/2516

Step 1.2.3 version

---

test/acceptance/behave/README.md
test/acceptance/behave/components/common_steps/subscriptions/notification_steps.py
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_conditions.feature
test/acceptance/behave/tools/NGSI_v2.py

- new steps to notifications
- the issue 2442 i splitted in two scenarios
- append a policy of retry when get a notification in the listener
- new functions in ngsi v2 verification library
@fgalan @crbrox @kzangeli

[APPEND] verification to notifications

---

test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_entity_types/retrieve_entity_types_traces_in_log.feature

[FEATURE] Thing type

---

test/acceptance/behave/environment.py

Now in the new format, the summary is presented as a table
See a example in https://jirapdi.tid.es/secure/attachment/912737/regressiom_test.txt

[CHANGES] in Tests summary (table)

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_attrs_and_orderby.feature

```
SUMMARY:
---------------------------------------------------------------------------------------------------------------------------------------------------------
|                                               name                                                  | passed | failed | skipped |  total  | duration(s) |
---------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\entities\list_entities\list_entities_queries_parameters_attrs_and_orderby.feature |     17 |      0 |       0 |      17 |       9.772 |
---------------------------------------------------------------------------------------------------------------------------------------------------------
|  Date: …
```

[FEATURE] list entities sorted

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/subscriptions/notifications/notifications_metadata.feature

```
SUMMARY:
----------------------------------------------------------------------------------------------------------------------------------
|                                   name                                       | passed | failed | skipped |  total  | duration(s) |
----------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\subscriptions\notifications\notifications_metadata.feature |     31 |      0 |      18 |      49 |      50.137 |
----------------------------------------------------------------------------------------------------------------------------------
|  Date: Thursday, September 29, 2016 15:56:46
1 feature passed, 0 failed, 0 …
```

[FEATURE] Special metadata in notifications

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_metadata.feature

```
SUMMARY:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                      name                                                         | passed | failed | skipped |  total  | duration(s) |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
| components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_notification_metadata.feature |     23 |      0 |       0 |      23 |       4.199 |
--------------------------------------------------------------------------------------------------------------- …
```

[FEATURE] subscription with notification metadata

---

test/acceptance/behave/components/common_steps/subscriptions/notification_steps.py
test/acceptance/behave/tools/NGSI_v2.py

In `notifications_step.py` we can to see the step definition where is executed the `verify_metadata_notification` method in the `NGSI_v2.py ` library. This method has all assertions.

[APPEND] steps and verification library in .py

---

makefile

FIX style_check_included_in_make_steps to remove LINT* leftovers

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/common/globals.h
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoQueryTypes.h
src/lib/ngsi/ContextAttributeVector.cpp
src/lib/ngsi/ContextAttributeVector.h
src/lib/rest/ConnectionInfo.cpp
src/lib/serviceRoutines/getAttributesForEntityType.cpp
src/lib/serviceRoutines/getEntityTypes.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
src/lib/serviceRoutinesV2/getEntityType.cpp
test/functionalTest/cases/2073_uri_param_to_disable_type_detail/uri_param_to_disable_type_detail.test
test/unittests/mongoBackend/mongoQueryTypes_test.cpp

Mirrors PR https://github.com/telefonicaid/fiware-orion/pull/2568 (through 2568.diff patch)

feature/2073_uri_param_to_disable_type_detail (into releaes/1.4.0)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp

Mirrors #2572 (in master) now for release/1.4.0 branch.

bug/2571_semaphore_problem (release/1.4.0)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp

Mirrors #2572 (in master) now for release/1.2.0 branch.

bug/2571_semaphore_problem (release/1.2.0)

---

CHANGES_NEXT_RELEASE
docker/Dockerfile
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h

Compare with changes in https://github.com/telefonicaid/fiware-orion/pull/2530

Step 1.2.4 versoin

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/2549_append_or_update_in_actionType_in_notifications/append_or_update_in_actionType_in_notifications.test

Twin PR for #2580 for master branch  (cherry-pick of the squash commit).

 Bug/2549 append or update in action type in notifications (master)
