scripts/build/release.sh

Fix in a previous PR. I though that `--tag` means "only push the tags" not "push the tags in addition to the branch, as usual".
Thus, the "git push" command shouldn't be commented out compeltely but adjusted.
@dmoranj @alvarolmedo

FIX git push command

---

src/lib/rest/rest.cpp
src/lib/rest/rest.h

This PR doesn't merge in release/0.18.1 as in the IoTP version Fiware-ServicePath is always use, so this hardening is not needed.

FIX explicit default service path in code

---

src/lib/serviceRoutines/postUpdateContext.cpp

fixed a leak when skipping context element response for forwarding updates
Possibly fixed a bug as well ... (see the ix = ix  1).

fixed a leak

---

etc/init.d/contextBroker.ubuntu

Init script of Ubuntu is omitting $BROKER_USER. There is also one /dev/null redirection missing.

$BROKER_USER omission

---

makefile
rpm/SPECS/contextBroker.spec
scripts/build/release.sh

Implements https://github.com/telefonicaid/fiware-orion/issues/779
I have tested this with `make rpm` and it seems to generate a correct contextBroker-0.19.0_next-dev.x86_64.rpm package. However, the "definitive test" will be done when we produce 0.20.0 using the release.sh script.

REMOVE contextBroker-fiware virtual RPM stuff

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonRegister.h
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoNotifyContextAvailability.cpp
src/lib/mongoBackend/mongoNotifyContextAvailability.h
src/lib/mongoBackend/mongoQueryContext.cpp
src/lib/mongoBackend/mongoRegisterContext.cpp
src/lib/mongoBackend/mongoRegisterContext.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/ContextElement.cpp
src/lib/ngsi/ContextElement.h
src/lib/ngsi/ProvidingApplication.cpp
src/lib/ngsi/ProvidingApplication.h
src/lib/serviceRoutines/postNotifyContextAvailability.cpp
src/lib/serviceRoutines/postRegisterContext.cpp
test/unittests/mongoBackend/mongoContextProvidersQuery_test.cpp
test/unittests/mongoBackend/mongoContextProvidersUpdate_test.cpp
test/unittests/mongoBackend/mongoNotifyContextAvailability_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp.bak
test/unittests/mongoBackend/mongoRegisterContext_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_update_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

This implements the part of #722 corresponding to mongoBackend. Note that the base feature/ branch for this PR has been branched from feature/787_cprs_full_functional instead of develop, given that feature/787_cprs_full_functional has the last snapshoot of mongoBackend (I don't like it but I don't have another option :( ).
At some point (probably when both query *and* update forward functionally get completed) we have to do the feature/787_cprs_full_functional -> feature/722_unhardwire_format_cpr, getting many compilation errors, but easy to solve (just use `providingApplication.get()` instead just `providingApplication`).
Tested using unit test (only failing the ones that was already failing in feature/787_cprs_full_functional) and test harness (there are fails due to …

Unhardwire format CPr at mongobackend

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

hasMetadata() was called with ContextAttribute* when it accepted a ContextAttribute.
The C++ compiler decided to create a ContextAttribute out of the ContextAttribute* and that object got lost, of course ...

Fixed a 'funny' leak

---

src/app/contextBroker/CMakeLists.txt
test/unittests/CMakeLists.txt

Hello,
It seems boost regex is missing from the linking instructions. I have experienced such a problem in Ubuntu 12.04.2, but I cannot confirm the same problem might happen in other Ubuntu versions or other distros. That's why I'm proposing this PR
thanks!

FIX linking instructions. boost regexp is missing. Ubuntu 12.04.2

---

scripts/check_files_compliance.py

After this PR, both:
```
Copyright 2013
```
and
```
Copyright (c) 2013
```
are supported in the license header

FIX files compliance script to support more flexible copyright line

---

CHANGES_NEXT_RELEASE
src/lib/jsonParse/jsonRequest.cpp
src/lib/xmlParse/xmlRequest.cpp

Remove unconditional tracing on xmlTreat()/jsonTreat() which was impacting on performance (specially in high-load scenarios)

Bug/remove traces  

---

CMakeLists.txt

Fixes #842 
CMakeList.txt has been modified .

Corrected error of CMake when BUILD_ARCH is not defined

---

test/unittests/mongoBackend/mongoDiscoverContextAvailability_test.cpp
test/unittests/mongoBackend/mongoOntimeintervalOperations_test.cpp
test/unittests/mongoBackend/mongoQueryContextGeo_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoQueryTypes_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_update_test.cpp
test/unittests/mongoBackend/mongoSubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextAvailabilitySubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptions_test.cpp
test/unittests/testInit.h

Fixes #628 
The definition in testInit.h has been changed from 'unittest' to 'utest' and from those direct usages of 'unittest' stored in test/unittests/mongoBackend/

Rename db unittests

---

doc/apiary/v2/fiware-ngsiv2-cookbook.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

In addition, I have removed the licence header in the cookbook .apib (which was defferred due to a hurry in a past PR).

ADD comment about NGSI list archives

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Implementing changes after our discussion on June 26th on issue #1022 topics:
* Commenting out sections on `/type/<type>/id/<id>` in order to have a shorter and cleaner specification
* Clarifying how JSON types and NGSI types works (including some remarks regarding appliying filtering to non-numeric and non-date types). Dates and geo:point are the only special NGSI types for CB (both string-based from a JSON type point of view).
* Including cannonical representation definition.
* Fixing "GET /v2/types" and "GET /v2/types/{type}" operations
* Removing `?attrs` paramter in "DELETE /v2/entities/{id}" and "DELETE /v2/entities/type/{type}/id/{id}" operations

FIX apiary specification document after refining #1022

---

doc/manuals/admin/database_model.md
doc/manuals/admin/management_api.md
doc/manuals/user/append_and_delete.md
doc/manuals/user/context_providers.md
doc/manuals/user/duration.md
doc/manuals/user/filtering.md
doc/manuals/user/geolocation.md
doc/manuals/user/metadata.md
doc/manuals/user/structured_attribute_valued.md
doc/manuals/user/updating_regs_and_subs.md
doc/manuals/user/walkthrough_apiv1.md

It has been removed the XML format from these files : 
-/doc/manuals/user/ append_and_delete.md duration.md structured_attribute_valued.md updating_regs_and_subs.md geolocation.md metadata.md context_providers.md filtering.md
-/doc/manuals/admin/database_model.md.
There are also other files that contains some XML formats: 
--In the files: code_contributions.md, federation.md, http_and_gsi.md, known_limitations.md, multitenancy.md, pagination.md,empty_types.md
--In the file /doc/manuals/walkthrough_apiv1.md , in :
All the examples implemented.
It is the Funny example (/v1/registry/contextEntityTypes/Funny ).

Remove all XML format

---

scripts/build/release.sh

This is a leftover of the PR in which we change from 3-digit to 4-digit functional test cases directories. The actual version_via_rest.test is actually inside cases/0000_version_operation directory.
Upon merging, the problem with jenkins file compliance job should be fixed.

REMOVE empty version_via_rest.test (leftover of a past PR refactoring)

---

test/functionalTest/cases/0970_create_entity/creation_with_attribute_as_object.test
test/functionalTest/cases/0970_create_entity/simple_creation.test

I installed a newer version of python (2.7.10) and my CentOS now works just like Jenkins.

3.2999999999998 => 3.3 - new python version fixes the problem

---

doc/manuals/user/walkthrough_apiv1.md

Fixed what seemed like a copy-paste error, where the first example for an update context request was actually the JSON of the response.

Fixed update context request json

---

src/lib/jsonParse/jsonParse.cpp
src/lib/ngsi/Scope.cpp
src/lib/xmlParse/xmlParse.cpp
test/functionalTest/cases/0619_forbidden_characters_in_payload/input.test
test/functionalTest/cases/0864_filter_string_scope/filter_string_scope.test

Not checking for illegal characters in payload inside 'scope-values' if their scope-type is FIWARE::StringQuery

Task/no illegal char for FIWARE::StringQuery scope in payload

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp

Removed the check of forbidden characters for the value of the URI param **idPattern**

No forbiddenChars check for URI param idPattern

---

docker/Dockerfile
docker/README.md
docker/docker-compose.yml

And adding the --smallfiles option (as comment)

FIX docker compose scripts resersing mongo/orion startup order 

---

src/lib/cache/Subscription.cpp
src/lib/cache/SubscriptionCache.cpp
src/lib/cache/SubscriptionCache.h
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h

Fixes #1186 
Note that no entry is included in CNR file, as this bug was introduced by the cache subscription feature and it is not a bug in previous Orion version.

FIX tenant in wrong places in subscription cache code

---

src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h

Fixes #1210.
CNR entry not needed, as the fix is on functionality developed in the current version (subscriptions cache).
Manually tested.

FIX CB crashes when DB stops due to cache refresh

---

README.md
doc/manuals/admin/README.md
doc/manuals/admin/cli.md
doc/manuals/admin/database_admin.md
doc/manuals/admin/database_model.md
doc/manuals/admin/diagnosis.md
doc/manuals/admin/install.md
doc/manuals/admin/logs.md
doc/manuals/admin/running.md
doc/manuals/user/filtering.md
doc/manuals/user/walkthrough_apiv1.md
mkdocs.yml

Sections related Installing and Running Orion has been moved from master README.md to administration manual, in order they get included in the readthedocs manuals. README.md now include links to the admin manual .md documents in those places.
In addition, this PR fixes the ToC problems described in issue #1136

REFACTOR README.md sections into admin manual

---

doc/manuals/admin/cli.md
doc/manuals/admin/diagnosis.md
doc/manuals/admin/management_api.md
doc/manuals/user/context_providers.md
doc/manuals/user/empty_types.md
doc/manuals/user/federation.md
doc/manuals/user/forbidden_characters.md
doc/manuals/user/http_and_ngsi_sc.md
doc/manuals/user/known_limitations.md
doc/manuals/user/multitenancy.md
doc/manuals/user/pagination.md
doc/manuals/user/security.md
doc/manuals/user/service_path.md
doc/manuals/user/walkthrough_apiv1.md

Removing XML leftovers in the manual, yet pending until now.
After this PR, the `grep '</' -R *` run in doc/manuals show only the following ocurrences:
* code_contributions.md. They are verbatim contributions from users, done in the past, so it means sense to have XML there.
* `<a name="top">` marks. They are not rendered, used for intra-page navigation. No problem.
* known_limitations.md. A cite to the HTML error that libmicrohttp generates for huge requests. It ok to have it as is, as is a text generated by the library.
So, after merging this PR, documentation is XML-free finally :)

FIX remove XML leftovers from manuals

---

test/functionalTest/cases/0000_statistics_operation/statistics.test
test/functionalTest/cases/0000_statistics_operation/statistics_with_semaphores.test
test/functionalTest/cases/0392_service_path_update_and_query/service_path_http_header.test
test/functionalTest/cases/0563_ngsi10_get_list_of_all_entities/all_entities_no_filter.test
test/functionalTest/cases/0581_include_type_in_convops/v1_registry_contextEntities_enType_ENTYPE_enId_ENID_attribute_attrName.test
test/functionalTest/cases/1048_subscription_cache/cache_population_at_init.test
test/functionalTest/cases/1048_subscription_cache/three_subscriptions.test

Made the last changes (there was no time to include this in the release 0.24.0) to fix the failing functests under the valgrind suite.
Now only coap_basic fails under valgrind.

All functests but coap_basic now work again under valgrind

---

scripts/build/fiwarelab/README.md
scripts/build/fiwarelab/build-fiwarelab-image.sh
scripts/build/fiwarelab/check-fiwarelab-image.sh

Manually tested in FIWARE Lab environment:
* Deploy base_centos_6 VM
* Donwload the script from github ` wget https://raw.githubusercontent.com/telefonicaid/fiware-orion/hardening/fiwarelab-scripts/scripts/build/fiwarelab/build-fiwarelab-image.sh`
* Run the script
* Reboot VM
* Set `IP` envar in an external machine, then run check-fiwarelab-image.sh and check it works

FIX FIWARE Lab image building scripts

---

src/app/contextBroker/contextBroker.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoQueryTypes.h
src/lib/orionTypes/CMakeLists.txt
src/lib/orionTypes/EntityType.cpp
src/lib/orionTypes/EntityType.h
src/lib/orionTypes/EntityTypeResponse.cpp
src/lib/orionTypes/EntityTypeResponse.h
src/lib/orionTypes/EntityTypeVector.cpp
src/lib/orionTypes/EntityTypeVector.h
src/lib/orionTypes/EntityTypeVectorResponse.cpp
src/lib/orionTypes/EntityTypeVectorResponse.h
src/lib/serviceRoutines/getAttributesForEntityType.cpp
src/lib/serviceRoutines/getEntityTypes.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
src/lib/serviceRoutinesV2/getEntityType.cpp
test/unittests/mongoBackend/mongoQueryTypes_test.cpp

Implements #1173. No CNR entry needed (this is an  internal change in the code base, without external effects).
* TypeEntity => EntityType
* TypeEntityVector  => EntityTypeVector
* EntityTypeAttributesResponse => EntityTypeResponse
* EntityTypesResponse => EntityTypeVectorResponse
Tested with: make unit_test, make test compilations (functional tests without effect) and grep:
```
$ grep -i TypeEntity -R src/*
$ grep -i TypeEntity -R test/unittests/*
$ grep -i TypeEntityVector -R src/*
$ grep -i TypeEntityVector -R test/unittests/*
$ grep -i EntityTypeAttributesResponse -R src/*
$ grep -i EntityTypeAttributesResponse -R test/unittests/*
fermin@oriondeb:~/src/fiware-orion$ grep -i EntityTypesResponse -R src/*
src/lib/ngsi/Request.h:  RtEntityTypesResponse,
src/lib/ngsi/Request.cpp:  case …
```

Rename types to make code clearer

---

scripts/build/fiwarelab/build-fiwarelab-image.sh

The Redis+Rush installation fragment has been tested isolatedly. Thus, it would be needed a test of the whole build-fiwarelab-image.sh script after LGTM but before merging.

Add Rush installation stuff to the build image script

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutinesV2/getEntities.cpp
src/lib/serviceRoutinesV2/getEntityAllTypes.cpp
test/functionalTest/cases/0947_v2_list_all_entities/GET_v2_entities.test
test/functionalTest/cases/0947_v2_list_all_entities/GET_v2_entities_pagination.test
test/functionalTest/cases/0953_list_all_ents_id/GET_v2_entities.test
test/functionalTest/cases/0953_list_all_ents_id/GET_v2_entities_pagination.test
test/functionalTest/cases/0953_list_all_ents_id/GET_v2_entities_pattern.test
test/functionalTest/cases/1041_GET_v2_entities_options_count/get_entities_option_count.test

Use options=count when getting entities, closes #1041

Use options=count when getting entities

---

test/functionalTest/cases/0953_list_all_ents_id/GET_v2_entities_pattern.test

It seems we leave some comment without fix in a past PR (I have spoted by coincidence)

FIX typo in test harness comment

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Please note that due to standard Apiary rendering limitations some payloads (those which contain nested data structures) have not been migrated to the Attributes format. However they have been aligned to the usage of '+' for lists to enable its easy migration once that Apiary limitation is fixed.

Apiary - NGSIv2 - Normalize the document to use attributes and groups

---

doc/manuals/user/forbidden_characters.md

Add a warning in the documentation about the use of characters with meaning for the URL decoding.

ADD Warning about characters with URL meaning

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoConnectionPool.cpp
src/lib/mongoBackend/mongoOntimeintervalOperations.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoUpdateContextAvailabilitySubscription.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
src/lib/mongoBackend/safeBsonGet.cpp
src/lib/mongoBackend/safeBsonGet.h

Partial implementation of #136 
Instead of using directly BSON class method, I have defined "wrapper" functions that do all the checking and prevent cases in the safeBsonGet.h module.
At the end, no code should use directly BSON methods (except unit test code). However, note that some leftover remains in cache/ (I have preferred not to touch there, as the cache is being re-done and the work will eventually land in develop branch).

FIX hardening mongoBackend checking for field existence and proper type to avoid broker crashes due to DB corruption

---

src/lib/convenience/UpdateContextAttributeRequest.cpp
src/lib/convenience/UpdateContextAttributeRequest.h
src/lib/jsonParse/jsonUpdateContextAttributeRequest.cpp
src/lib/ngsi10/UpdateContextRequest.cpp
src/lib/xmlParse/xmlUpdateContextAttributeRequest.cpp
test/functionalTest/cases/1358_v1_empty_attribute_values/empty_values_conv_ops.test
test/functionalTest/cases/1392_empty_attr_conv_op/empty_attr_conv_op.test

Fixes #1392 
CNR entry is not included (as this is a fix in a issue adressed in 0.25.0, not present in previous versions).

FIX empty attribute values in PUT/POST /v1/contextEntities/<id>/attributes/<attr> operation

---

src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoConnectionPool.cpp
test/unittests/cache/SubscriptionCache_test.cpp
test/unittests/mongoBackend/mongoContextProvidersQuery_test.cpp
test/unittests/mongoBackend/mongoContextProvidersUpdate_test.cpp
test/unittests/mongoBackend/mongoDiscoverContextAvailability_test.cpp
test/unittests/mongoBackend/mongoNotifyContextAvailability_test.cpp
test/unittests/mongoBackend/mongoNotifyContext_test.cpp
test/unittests/mongoBackend/mongoOntimeintervalOperations_test.cpp
test/unittests/mongoBackend/mongoQueryContextFilterExistEntity_test.cpp
test/unittests/mongoBackend/mongoQueryContextGeo_test.cpp
test/unittests/mongoBackend/mongoQueryContext_filters_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoQueryTypes_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_update_test.cpp
test/unittests/mongoBackend/mongoSubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContextAvailability_test.cpp
test/unittests/mongoBackend/mongoUnsubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextAvailabilitySubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContextGeo_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_withOnchangeSubscriptions_test.cpp
test/unittests/testInit.cpp

Functional test were not generating coverage in report since DB pool implementation. This PR is supossed to fix that.
The PR is long, but most of the changes in *_test.cpp files are all the same. The interesting parts to review are in: MongoGlobal.cpp/h, mongoConnectionPool.cpp and testInit.cpp.

FIX coverage for functional tests

---

CHANGES_NEXT_RELEASE
src/lib/common/tag.cpp
src/lib/common/tag.h
src/lib/ngsi/ContextAttribute.cpp
src/lib/parse/CompoundValueNode.cpp

Exceptionally, this PR doesn't include test func (they will be added in a next PR).

Not string values in ngsv1 compounds renders

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoUnsubscribeContext.cpp
test/functionalTest/cases/1471_ngsiv1_render_not_string_in_compounds/ngsiv1_render_not_string_in_compounds.test
test/functionalTest/cases/1488_unsubscribe_sem_bug/unsubscribe_sem_bug.test

Fix #1488 
In addition, to save time, it includes a missing .tes (closing #1472)

FIX semaphore releasing bug in unsubscribeContext when subscription ID is the empty string

---

src/lib/ngsiNotify/QueueNotifier.cpp
src/lib/ngsiNotify/QueueStatistics.cpp
src/lib/ngsiNotify/QueueStatistics.h
src/lib/ngsiNotify/QueueWorkers.cpp
src/lib/serviceRoutines/statisticsTreat.cpp

@fgalan 
@kzangeli 
Fix broken build by not supported boost library (1.53.0)
(temporary, to be refactored to be aligned with common statistics)

Urgent: Do not use boost/atomic

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Old "JSON entity representation" section has been rewritten, spliten in three subsections: "JSON entity representation", "JSON attribute representation" and "Direct access to attribute value" in order to match with the new JSON format (which implementation work is associated to issue #1259).
@jmcanterafonseca has been assigned as main reviewer of this, but all the others (@kzangeli, 
@mrutid and @antoniojoseln) who have take part in the looooong ;) discussions about this (both in skype and email) are welcome to contribute to this PR with comments.

REFACTOR rewritten JSON representation section in NGSIv2 reference apib

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
doc/manuals/deprecated.md
doc/manuals/user/walkthrough_apiv1.md

As usual, straighforward English fixes can be done directly in the PR, without needed of commenting.

Documentation changes to deprecate ONTIMEINTERVAL

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/serviceRoutinesV2/getSubscription.cpp
test/functionalTest/cases/1552_invalid_sub_id/invalid_sub_id.test

Fixes issue #1552 
Checking subscription ID before letting it pass down to mongo layer, for GET "/v2/subscriptions/XXX"

Check of Subscription ID before sending request to mongo layer

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Align NGSIv2 spec operation descriptions after the last PRs touching the .apib (in particular the one related with the JSON entity format representation and the one related with geolocation and geoqueries).

FIX align NGSIv2 spec operation descriptions

---

CHANGES_NEXT_RELEASE
scripts/build/osDistro.sh
src/lib/common/string.cpp
test/unittests/common/commonString_test.cpp

FIX pasrseUrl() function

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/compoundResponses.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/Metadata.cpp
src/lib/parse/CompoundValueNode.cpp
test/unittests/mongoBackend/mongoQueryContextCompoundValues_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextCompoundValues_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp

The following unit test has been extened in order to ensure support 
Related with query:
* CCompoundValue1Native
* CCompoundValue2Native
* CCompoundValue1PlusSimpleValueNative
* CompoundValue2PlusSimpleValueNative
* queryCustomMetadataNative
* queryNativeTypes
Related with update:
* createEntityCompoundValue1Native
* createEntityCompoundValue2Native
* createEntityCompoundValue1PlusSimpleValueNative
* createEntityCompoundValue2PlusSimpleValueNative
* createNativeTypes
* updateNativeTypes
* preservingNativeTypes
* createMdNativeTypes
* updateMdNativeTypes
* preservingMdNativeTypes
No new functional test added. It is expected (make ft running just now) that all will be working (except the 2 ones in 1164 and 1305 that are expected to fail).

New NGSIv2 JSON: part 8 (null support in mongoBackend)

---

scripts/accumulator-server.py

This PR is supposed to fix the ipv4_ipv6.test problem in some distributions. In order to test, you need to re-install the accumulator-server.py, typically running:
```
make install_scripts
```
(Use the proper INSTALL_DIR if you need so)

FIX accumulator-server.py to work with IPv6 in Debian 8.2 (maybe it also helps others, e.g. Ubuntu)

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/build_source.md
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/connectionOperations.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoQueryTypes.cpp
src/lib/mongoBackend/mongoSubCache.cpp

Upgrading driver hasn't impact in the code (it has impact in the system that builts the RPMs, i.e. jenkins, that will be upgraded after this PR got merged) but this PR includes some changes in the `LmtMongo` traces that were used the bug that motivates this upgrade and that can be useful in the future.
@kzangeli 
@crbrox

FIX mongo driver legacy-1.0.2 -> legacy-1.0.7

---

docker/Dockerfile

Adjust dockerfile as required after this issue https://github.com/telefonicaid/fiware-orion/issues/1675 (libmicrohttpd installation from sources).
I have testes building the image locally with that dockerfile, then using it in a docker-compose.yml to start the CB-Mongo system.
@LeandroGuillen

FIX dockerfile for libmicrohttpd installation from sources

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutinesV2/patchEntity.cpp
test/functionalTest/cases/1782_forbidden_char_id_uri_patch/1782_forbidden_char_id_uri_patch.test

Fix bug #1782, forbidden chars in ID PATCH v2
@kzangeli 
@fgalan

Fix bug #1782, forbidden chars in ID PATCH v2

---

CHANGES_NEXT_RELEASE
src/lib/common/errorMessages.h
src/lib/serviceRoutinesV2/deleteEntity.cpp
src/lib/serviceRoutinesV2/getEntity.cpp
src/lib/serviceRoutinesV2/getEntityAttribute.cpp
src/lib/serviceRoutinesV2/getEntityAttributeValue.cpp
src/lib/serviceRoutinesV2/postEntity.cpp
src/lib/serviceRoutinesV2/putEntity.cpp
src/lib/serviceRoutinesV2/putEntityAttribute.cpp
src/lib/serviceRoutinesV2/putEntityAttributeValue.cpp
test/functionalTest/cases/1793_forbidden_id_chars_in_uri/1793_forbidden_id_chars_in_uri.test
test/functionalTest/cases/1793_forbidden_id_chars_in_uri/1793_forbidden_id_chars_in_uri_attrs.test

Check forbidden chars for ids/attr names in URIs

---

src/lib/apiTypesV2/Entity.cpp
src/lib/cache/subCache.cpp
src/lib/ngsi/ParseData.h
src/lib/orionTypes/areas.cpp

Tested using the following command
```
cppcheck --quiet --enable=warning,performance,portability  --inline-suppr -Isrc/lib/ -Isrc/app -DLM_ON  src/
```
```
[src/lib/rest/ConnectionInfo.h:55]: (warning) Member variable 'ConnectionInfo::requestType' is not initialized in the constructor.
[src/lib/rest/ConnectionInfo.h:77]: (warning) Member variable 'ConnectionInfo::requestType' is not initialized in the constructor.
[src/lib/rest/ConnectionInfo.h:99]: (warning) Member variable 'ConnectionInfo::requestType' is not initialized in the constructor.
[src/lib/apiTypesV2/Entity.cpp:128]: (warning) %zd in format string (no. 1) requires a signed integer given in the argument list.
[src/lib/apiTypesV2/Entity.cpp:141]: (warning) %zd in format string (no. 1) requires a signed integer given in the …
```

Fix ccpcheck

---

doc/manuals/deprecated.md
doc/manuals/user/known_limitations.md

Documentation pieces related with issue https://github.com/telefonicaid/fiware-orion/issues/1289

ADD keysize related limitation in documentation

---

src/lib/mongoBackend/mongoQueryTypes.cpp

This fixes loging the following ERROR traces (which is not actually an ERROR):
```
Runtime Error (field '_id' was supposed to be a string but type=10 in BSONObj
```
**DO NOT DELETE BRANCH AFTER MERGE**. We would need it to merge this also in develop

FIX overloging false Runtime Error

---

src/lib/ngsiNotify/Notifier.cpp
src/lib/ngsiNotify/senderThread.cpp
src/lib/ngsiNotify/senderThread.h

Part of #1669 
Unfortunatelly, make ft is broken in feature/1181_websocket due to current WS implementation in that branch, I cannot assure this modification doesn't break anything...
@fortizc

ws:// processing at Notifier library

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp
src/lib/mongoBackend/MongoCommonRegister.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/mongoRegisterContext.cpp
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
src/lib/ngsiNotify/Notifier.cpp
src/lib/rest/rest.cpp
src/lib/serviceRoutines/postUpdateContext.cpp
test/unittests/mongoBackend/mongoDiscoverContextAvailability_test.cpp
test/unittests/mongoBackend/mongoNotifyContext_test.cpp
test/unittests/mongoBackend/mongoQueryContext_test.cpp
test/unittests/mongoBackend/mongoRegisterContext_test.cpp
test/unittests/mongoBackend/mongoSubscribeContext_test.cpp
test/unittests/mongoBackend/mongoUpdateContextSubscription_test.cpp
test/unittests/mongoBackend/mongoUpdateContext_test.cpp
test/unittests/rest/RestService_test.cpp
test/unittests/serviceRoutines/putIndividualContextEntityAttribute_test.cpp
test/unittests/unittest.cpp
test/unittests/unittest.h

"No .test was harmed in the making of this PR" :)
Apart of fixing #2024 itself, this PR moves the SP defaulting logic to mongoBackend, thus allowing to simplify removing defaultServicePath() funtion. In addition, some refactors has been include to make centralize SP filtering functionality across mongoBackend in the fillQueryServicePath() function.
Finally, unit test code has been optimized, removing duplicated copies of the "mock" service path.
Test done to check that #2024 has been solved with this PR:
```
$  curl -v -H "Content-Type: application/json" -H "Fiware-Service: test_service_path" http://localhost:1026/v2/subscriptions -d '{"notification": {"callback": "http://localhost:1234", "attributes": ["temperature"]}, "expires": "2016-04-05T14:00:00.00Z", "subject": {"entities": …
```

FIX service path persistence at subscription creation (along with some refactoring)

---

doc/manuals/deprecated.md

Another fix for the new URL (this time in the documentation) which has passed unoticed until now.
@pratid

FIX FIWARE repository URL

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

This PR fixes the NGSIv2 spec .apib in order to align with the latest changes in CB implementation (related with issues #2014, #2042 and #2043).
People that may be insterested in having a look to this:
@iariasleon 
@anabelengp 
@kzangeli 
@crbrox 

Align csub pyaload description in NGSIv2 spec with latest changes in implementation

---

CHANGES_NEXT_RELEASE
src/lib/common/tag.cpp
src/lib/common/tag.h
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/2058_wrong_number_rendering/ilegal_json_attributeformat_object_with_number.test

Fixes #2058 
@crbrox 
@kzangeli

FIX illegal JSON in attributeFormat=object mode

---

docker/Dockerfile

Related with #2063 
Remove unneded stuff in Dockefile in order to reduce docker images footprint.

REMOVE /opt/libmicrohttpd-0.9.48 in Dockerfile

---

test/unittests/CMakeLists.txt

Small fix on the Debian 8.3 unit test building cmake files.

FIX unittest cmake file for Debian 8.3

---

CHANGES_NEXT_RELEASE
doc/manuals/deprecated.md
doc/manuals/user/geolocation.md
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextElementResponse.cpp
test/functionalTest/cases/0000_deprecated_checkings/legacy_geolocalization_area_json.test
test/functionalTest/cases/0000_deprecated_checkings/legacy_geoquery_bad_coords.test
test/functionalTest/cases/0000_deprecated_checkings/legacy_geoquery_circle_json.test
test/functionalTest/cases/0000_deprecated_checkings/legacy_geoquery_polygon_json.test
test/functionalTest/cases/0000_deprecated_checkings/legacy_location_no_actual_location_change.test
test/functionalTest/cases/1677_geo_location_for_api_v2/ngsiv2_location_in_ngsv1.test
test/functionalTest/cases/1677_geo_location_for_api_v2/ngsiv2_location_in_ngsv1_near.test
test/functionalTest/cases/1875_NGSIv2_notification_formats/NGSIv2_notification_formats.test

This PR deprecates `location` as a way of specifying entity location, in favour of using `geo:point`. Old test in 0000_ngsi10_geolocation has been changed to the "new way" and the old ones has been moved to the 0000_deprecated_checkings with the `legacy_` prefix in order to ensure that deprecated functionality is still supported until we decide remove it definetivelly.
@kzangeli 
@crbrox

DEPRECATE location metadata to specify entity location

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature

@kzangeli  @crbrox 
```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_subject_entities.feature >> passed: 123, failed: 0, skipped: 47 and total: 170 with duration: 194.042 seconds.
Date: Friday, April 22, 2016 09:47:31
123 scenarios passed, 0 failed, 47 skipped
710 steps passed, 0 failed, 236 skipped, 0 undefined
Took 3m14.042s
```
There are still pending to resolve the bugs following: (1964, 1965, 1967, 1973, 1974, 1975, 1976, 1978, 1984, 1985, 1986)

[FEATURE] create subscription - checking subject-entities fields

---

test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/attributes/update_attribute_data/update_attribute_data.feature
test/acceptance/behave/components/ngsiv2/attributes_values/update_attribute_value/update_attribute_value.feature
test/acceptance/behave/components/ngsiv2/entities/replace_all_entity_attributes/replace_all_entity_attributes_part2.feature
test/acceptance/behave/components/ngsiv2/entities/update_existing_entity_attributes/update_existing_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/update_or_append_entity_attributes/update_or_append_entity_attributes.feature

**WARNING: verify that the PR: https://github.com/telefonicaid/iotqatools/pull/78 has been merged**
```
SUMMARY:
- components/ngsiv2/entities/create_entity/create_entity.feature >> passed: 142, failed: 0, skipped: 6 and total: 148 with duration: 18.738 seconds.
- components/ngsiv2/entities/create_entity/create_entity_part2.feature >> passed: 235, failed: 0, skipped: 0 and total: 235 with duration: 32.492 seconds.
- components/ngsiv2/entities/create_entity/create_entity_part3.feature >> passed: 294, failed: 0, skipped: 16 and total: 310 with duration: 33.819 seconds.
- components/ngsiv2/entities/create_entity/create_entity_traces_in_log.feature >> passed: 0, failed: 0, skipped: 1 and total: 1 with duration: 0.000 seconds. …
```

[FEATURE] attrs resources using ngsi v2

---

test/acceptance/behave/tools/NGSI_v2.py

These fields are used in a dict with all properties of the subscription, see [dict](https://github.com/telefonicaid/iotqatools/blob/develop/iotqatools/cb_v2_utils.py#L186)
@kzangeli @crbrox @fgalan

[FEATURE] changes in the subscription structure. Verification library

---

docker/README.md
docker/docker-compose.yml

Given that WiredTiger is default storage in MongoDB 3.2 (according to https://docs.mongodb.com/manual/release-notes/3.2/#wiredtiger-as-default) and that smallfiles applies only to mmapv1 (see https://docs.mongodb.com/manual/reference/configuration-options/#storage-options) all the references to `smallfiles` could be removed from Docker configurations.

Remove smallfiles from Docker configurations

---

CHANGES_NEXT_RELEASE
src/lib/rest/StringFilter.cpp
src/lib/rest/StringFilter.h
test/functionalTest/cases/2164_regex_filter_crash/regex_filter_crash.test

Fixes #2164. In addition, it includes the CNR line for #2064, that we missed to include in a past PR.
Please, pay special attention to memory management logic (i.e. `new`s and `delete`s) in order to be sure that this PR is not introducing any leakage.
@kzangeli 
@crbrox

FIX query filter regex crashes

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

This PR solve some minor issues in the NGSIv2 specification .apib, in order to leave it ready to branch the stable release. Some of the issues correspond to issues raised by NEC at fiware-ngsi mailing list (thanks!).
Summary of changes:
* "Conformance" section changed, in order to prepare for optionality and roles/profiles in a next interation of the stable spec.
* Clarifications on type "none"
* Explicit mention that new error codes/messages could be defined in the future.
* Using "batch" instead of "PoJ"
* Remove references to ServicePath
* More detailed section referencing inside text, in order to cope with APIary poor hyperlinking capabilities.
* Some minor typos fixed
Anybody is welcome to have a look and comment!
Target merging deadline: Monday 23rd May, EoB.

Polishing NGSIv2 specification to prepare the stable release

---

CHANGES_NEXT_RELEASE
src/lib/logMsg/logMsg.cpp

Twin PR (into release/1.2.0) of #2233
* UTC in logfile and not the nodes time-zone (which did not correspond to the times)
* gmtime_r seems to solve the problem
* CHANGES_NEXT_RELEASE

Hardening/2232 utc in logfile (into release/1.2.0)

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib

This PR finished the work to prepare the NGSIv2 specification release candidate May 2016.
Summary of changes:
* Rewritten "Status" section (with the Status corresponding to Release Candidates)
* Added section on "Reference Implementations"
* Removed references to "role" concept
* Removed empty placeholders "Terminology" subsections 
* Removed Context Element section (as it has not been yet decided if this concetp will be part of the final version of the API)
* Removed "pending discussion" notes.
* Removed "registration_url" removed from GET /v2 operation (as context management availability as not been yet defined in NGSIv2 specification)
* Removed "# Group Registrations" (as context management availability as not been yet defined in NGSIv2 specification)
* Removed "scopes" in POST …

Final fixes for the NGSIv2 release candidate May 2016

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_subject_condition.feature >> passed: 134, failed: 0, skipped: 121 and total: 255 with duration: 33.605 seconds.
Date: Friday, June 17, 2016 10:15:57
134 scenarios passed, 0 failed, 121 skipped
756 steps passed, 0 failed, 605 skipped, 0 undefined
Took 0m33.605s
```
All geo-condtion tests are skipped. See #1678 
@kzangeli @crbrox @fgalan

[FEATURE] subscription subject condition using ngsi v2

---

test/acceptance/behave/components/ngsiv2/entities/remove_entity/remove_entity_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\entities\remove_entity\remove_entity_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.781 seconds.
Date: Friday, July 15, 2016 15:36:29
1 scenario passed, 0 failed, 0 skipped
11 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m4.781s
```

[FEATURE] content type is not accepted in delete request (log traces)

---

doc/manuals/user/walkthrough_apiv2.md

In the example it is said that:
"For example, in this case, when Room1 `pressure` changes, the Room1 temperature value is notified"
But the temperature of the object is being used as a condition attribute.

Fix for subscription case in  API Walkthrough (v2)

---

doc/manuals/admin/management_api.md

It has been recently decided that the standard codification for log levels is in upper case. Thus, documentation should use upper case.
(Anyway, it is ok to supporr also lowercase in the implementation, as a "convenience" alternative flavour of the API).

FIX change log level to uppercase in log API doc

---

test/acceptance/behave/components/ngsiv2/attributes/get_attribute_data/get_attribute_data_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\attributes\get_attribute_data\get_attribute_data_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 5.043 seconds.
Date: Tuesday, July 26, 2016 10:34:26
1 scenario passed, 0 failed, 0 skipped
11 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m5.043s
```

[FIX] regression test in get attribute data - trace in log test suite

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute.feature
test/acceptance/behave/components/ngsiv2/attributes/remove_a_single_attribute/remove_a_single_attribute_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\attributes\remove_a_single_attribute\remove_a_single_attribute.feature >> passed: 124, failed: 0, skipped: 7 and total: 131 with duration: 41.426 seconds.
- components\ngsiv2\attributes\remove_a_single_attribute\remove_a_single_attribute_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 4.866 seconds.
Date: Tuesday, July 26, 2016 11:19:57
125 scenarios passed, 0 failed, 7 skipped
787 steps passed, 0 failed, 56 skipped, 0 undefined
Took 0m46.292s
```

[FIX] regression test in delete attribute data test suite

---

test/acceptance/behave/README.md
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_queries_parameters.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity/retrieve_entity_traces_in_log.feature

```
SUMMARY:
- components\ngsiv2\entities\retrieve_entity\retrieve_entity.feature >> passed: 209, failed: 0, skipped: 1 and total: 210 with duration: 91.738 seconds.
- components\ngsiv2\entities\retrieve_entity\retrieve_entity_queries_parameters.feature >> passed: 19, failed: 0, skipped: 1 and total: 20 with duration: 6.461 seconds.
- components\ngsiv2\entities\retrieve_entity\retrieve_entity_traces_in_log.feature >> passed: 1, failed: 0, skipped: 0 and total: 1 with duration: 5.102 seconds.
Date: Thursday, July 28, 2016 10:00:52
3 features passed, 0 failed, 0 skipped
229 scenarios passed, 0 failed, 2 skipped
1719 steps passed, 0 failed, 16 …
```

[FIX] tests review in retrieve entity test suites

---

test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature

```
SUMMARY:
- components\ngsiv2\subscriptions\create_a_new_subscription\create_a_new_subscription_subject_condition.feature >> passed: 207, failed: 0, skipped: 48 and total: 255 with duration: 29.215 seconds.
Date: Friday, July 29, 2016 16:53:23
207 scenarios passed, 0 failed, 48 skipped
1121 steps passed, 0 failed, 240 skipped, 0 undefined
Took 0m29.215s
```

[FIX] tests review create a new subscription with geo-expression

---

src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/1678_geosubscriptions/geosubscriptions_errors.test

Fixes #2406 
Note this PR doesn't include entry to CNR, as this is actually a fix in a just included functionality (geo-subscriptions)

FIX avoid partial geo-expression at subscription creation/update

---

src/lib/ngsi/Metadata.cpp
src/lib/parse/CompoundValueNode.cpp

Simply commented the call to `delete compoundValueP`in Metadata::release().
All tests in 1156_* run OK,
This is very temporary, a real fix is needed ASAP.

Temporary: not deleting compounds in Metadata::release - to avoid crashes

---

src/lib/parse/forbiddenChars.cpp
test/functionalTest/cases/1887_hash_in_url_gives_strange_results/hash_in_url_gives_strange_results.test

Functest for the Issue #1887 (part about house_# as EntityId or attrName).
No source code has been changed (except for a few empty lines for readability). It seems to be working.
Note that for the test cases with text/plain, the broker returns JSON.
This is something I believe we have discussed in the past and we've said "Good enough, after all, JSON is plain text ..."
Could be better, but it might be good enough.
Still unable to reproduce the strange error response that is described in issue #1887.

Functest for hash in URI as entityId or attribute name

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/cli.md
doc/manuals/admin/logs.md
doc/manuals/admin/management_api.md
src/app/contextBroker/contextBroker.cpp
src/lib/logMsg/logMsg.cpp
src/lib/parseArgs/paBuiltin.cpp
src/lib/serviceRoutinesV2/logLevelTreat.cpp
test/functionalTest/cases/0000_cli/bool_option_with_value.test
test/functionalTest/cases/0000_cli/command_line_options.test
test/functionalTest/cases/0000_cli/tracelevel_without_logLevel_as_DEBUG.test
test/functionalTest/cases/2419_log_level/log_level.test

Fixed issue #2419, by changing the broker slightly.
The broker now accepts FATAL *and* NONE as different log levels.
All intents to justify for FATAL/NONE have been removed.

Fixed 2419

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoQueryTypes.cpp

Hardwired solution for #2073 (only in release/1.2.0 branch)

Hotfix: remove attribute detail in get types operations (only NGSIv2 API)

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

We suggest the `attrName` example value should be `address` instead of `temperature` because the payload is a JSON with `PostalAddress` format: 
```
{
"address": "Ronda de la Comunicacion s/n",
"zipCode": 28050,
"city": "Madrid",
"country": "Spain"
}
```

Changed attrName example value  in order to be consistent with the payload.

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoGetSubscriptions.cpp

The pattern `getFielfF(...).String()` (or `.Number()`, etc.) should be avoided, in favour of `getStringFieldF()` (or similar ones for other data types). This PR fixes that in a particular "severe" case, but an overall review of all them (around ~100 ocurrences of `getFieldF()` in the code) should be done. However, not in this PR.

FIX missing mq field in csubs documents makes Orion to crash

---

CHANGES_NEXT_RELEASE
docker/Dockerfile
src/lib/mongoBackend/mongoGetSubscriptions.cpp

This PR contains two commits:
* The same fix than in PR https://github.com/telefonicaid/fiware-orion/pull/2525
* Some fixes needed to enable next Orion 1.2.3 building at dockerhub (note that 1.2.2 got broken in dockerhub).
Reviews required:
* @dmoranj (docker stuff)
* Somebody in the CB dev team

FIX crash on missing csub expr q + dockerfile fixes for release/1.2.0

---

test/acceptance/behave/components/common_steps/general_steps.py
test/acceptance/behave/components/ngsiv2/entities/create_entity/create_entity_geospatial_properties_of_entities.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_headers.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_queries_parameters_part_3.feature
test/acceptance/behave/components/ngsiv2/entities/list_entities/list_entities_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes.feature
test/acceptance/behave/components/ngsiv2/entities/retrieve_entity_attributes/retrieve_entity_attributes_queries_parameters.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_description.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_expires.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_headers.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_attrs.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_notification_http.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_status.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_condition.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_subject_entities.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_throttling.feature
test/acceptance/behave/components/ngsiv2/subscriptions/create_a_new_subscription/create_a_new_subscription_traces_in_log.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type.feature
test/acceptance/behave/components/ngsiv2/types/retrieve_an_entity_type/retrieve_an_entity_type_traces_in_log.feature
test/acceptance/behave/requirements.txt

The `requests` python library in 2.7 version, the response headers were returned all in lowercase (error in library), but iin 2.11.1 version they are returned correctly (as they are expected).

[RENAME] response headers

---

doc/apiary/README.md
doc/apiary/v2/fiware-ngsiv2-reference.apib

This PR includes:
* Fixes metadata parameter (was breakin the render of the document)
* A cheatsheet about local use of apiary client
* A note about using `'` to force strings in filters

FIX minor bugs in the NGSIv2 latest .apib spec

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

This causes a compile error in Debian 8.6 with gcc 4.9.2

FIX unitialized variable

---

rpm/SPECS/contextBroker.spec

I have fix this locally to generate 1.4.1 RPM.

FIX wrong changelog date in spec

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_10_31.apib

How to review this PR:
Looking to diff tab is not useful in this case, as the fiware-ngsiv2-rc-2016_10_31.apib  is enterely new. Thus, the best way to review this PR and provide feedback is to checkout task/prepare_ngsiv2_rc2016.10 branch them do the following comparison (meld or tkdiff are recommended):
- Compare fiware-ngsiv2-rc-2016_10_31.apib with fiware-ngsiv2-rc-2016_05_31.apib to check the new things that will be added to stable since last time.
- Compare fiware-ngsiv2-rc-2016_10_31.apib with fiware-ngsiv2-reference.apib to check the things in latests that are not going to be included in RC-2016.10 (thus deferred to a next RC).

ADD NGSIv2 stable spec RC-2016.10

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_model.md
doc/manuals/admin/install.md
doc/manuals/admin/upgrading_crossing_1-5-0.md
mkdocs.yml
scripts/managedb/change_attr_id_separator.py
src/lib/common/globals.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/dbFieldEncoding.h
test/functionalTest/cases/2453_attrs_with_double_underscore/attrs_with_double_underscore.test

Fixes #2453 
The regresion for metadata id (pe. compound_convop_attribute_json.test or compound_convop_attribute_by_valueid_json.test) ensures that the old functionality still works in a backward compatible mode.

FIX support attributes with double underscore as part of the name

---

src/lib/ngsi/EntityId.cpp
src/lib/rest/rest.cpp
test/functionalTest/cases/hotfix/hotfix_for_1_4_0__entity_types.test

Hotfix for bug found in 1.4.0. APIv1 queries sometimes (depending on RAM) have idTypePattern set to TRUE
AND: rolled back the fix for 'Accept header ending in comma'

type wrongly interpreted as a pattern in NGSIv1 queryContext + rollback the "Accept header less strict" fix

---

src/app/contextBroker/contextBroker.cpp

Upper limit has been removed, lower limit set to 1 (to avoid confusion with 0 changing to 1020).
Default value is set to 10240 connections.

New limits for -maxConnections

---

src/lib/serviceRoutinesV2/postBatchUpdate.cpp
test/functionalTest/cases/2720_op_update_crash/op_update_crash.test

A little missing part in the fix for #2720

FIX status code OK -> Bad Request when op update uses empty entities vector

---

doc/manuals/user/v1_v2_coexistence.md

Some improvements in that section in order to make it more precise.
It would be safe to wait to merge after a review of the `strictNgsiv1Ids` functionality has been done, as we have discussed recently.

FIX improve 'Checking ID fields' section in the documentation

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/database_admin.md
src/lib/apiTypesV2/Entities.cpp
src/lib/mongoBackend/MongoGlobal.cpp

Fixes #2752 
Manually tested (unfortunatelly this requires a particular DB to raise the problem, not easy to automate in functional tests):
```
fermin@neodeb:~/src/fiware-orion/test/functionalTest$ curl -vvvv -s -S 'localhost:1026/v1/contextEntities?offset=54882' 
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 1026 (#0)
> GET /v1/contextEntities?offset=54882 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:1026
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: Keep-Alive
< Content-Length: 416
< Content-Type: application/json
< Fiware-Correlator: 05eeb236-bc51-11e6-bab4-000c29173617
< Date: Wed, 07 Dec 2016 07:44:46 GMT
< 
{
"contextResponses" : [
{
"contextElement" : {
"type" : "",
"isPattern" : "true",
"id" : ".*"
},
"statusCode" : {
"code" …
```

FIX proper 500 Internal Server Error response with descriptive text when "sort fail" at DB occur

---

doc/manuals/admin/cli.md
doc/manuals/admin/diagnosis.md
doc/manuals/admin/perf_tuning.md

Documentation items regarding #2724 :
* The section regarding thread model has been re-written. The part related with file descriptors has been moved to its own section.
* Some coments related with poll() and epoll() in the section about MHD tunning
* (Pending) Comments regarding the relationship between -maxConnections and -reqPoolSize (a question has been done in the MDH maliling list). Probably the figure currently there is incorrect.
Documentation items regarding #2166:
* Comment regarding CLOSE_WAIT are ok, as they are part of libcurl cache strategy

FIX improving performance tuning documentation based on the recent modifications to MHD usage

---

test/functionalTest/cases/0000_deprecated_checkings/get_entity_dates_with_options.test
test/functionalTest/cases/0000_json_parse/jsonParseContextEntitiesByEntityId.test
test/functionalTest/cases/0000_json_parse/jsonParseContextEntityAttributes.test
test/functionalTest/cases/0000_json_parse/jsonParseEntityByIdAttributeByName.test
test/functionalTest/cases/0000_log_operation/log_rest.test
test/functionalTest/cases/0000_ngsi9_convenience/post_context_entity_types.test
test/functionalTest/cases/0000_ngsi9_convenience/post_context_entity_types_attribute.test
test/functionalTest/cases/0000_ngsi9_convenience/post_context_entity_types_attribute_container.test
test/functionalTest/cases/0000_ngsi9_registration_and_discover/registration_ok.test
test/functionalTest/cases/0117_convop_using_standard_ops/postContextEntitiesByEntityId.test
test/functionalTest/cases/0117_convop_using_standard_ops/postContextEntitiesByEntityIdAndType.test
test/functionalTest/cases/0117_convop_using_standard_ops/postContextEntityAttributes.test
test/functionalTest/cases/0117_convop_using_standard_ops/postContextEntityTypeAttribute.test
test/functionalTest/cases/0117_convop_using_standard_ops/postContextEntityTypes.test
test/functionalTest/cases/0876_entity_dates/get_entity_dates.test
test/functionalTest/harnessFunctions.sh

Note there aren't actual changes in .test (only in the way in which REG_ID is grabbed in some cases)

Prepare SUB_ID, REG_ID, etc. grab code in .test to work even when NGSIv1 responses are one-liners instaead of multi-line pretty-print

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoSubCache.cpp
src/lib/mongoBackend/mongoUpdateSubscription.cpp

Fixes https://github.com/telefonicaid/fiware-orion/issues/2796
Tested:
* 100% unit test regression ok
* 100% ft regression ok
* Manual test:
* Create a subscription
* Remove `metatada` field in DB
* `GET /v2/subscriptions` and check that no log output is generated

FIX wrongly overlogging metadata abscense in csub docs as Runtime Error

---

src/lib/logMsg/logMsg.cpp

Another bug found by LLVM.  strncat is particularly
tricky to use.  This commit attempts to fix the errors
found by LLVM.  Careful inspection is needed, this has
not been tested.

Fix strncat usage in src/lib/logMsg/logMsg.cpp

---

src/lib/parseArgs/paBuiltin.cpp
src/lib/parseArgs/paBuiltin.h

Yet another bug found by LLVM.  paClearAt is clearly
used as an integer, and declared as an integer in the
options list, but syntactically declared as a bool.
This commit simply changed the type from bool to int

Change paClearAt type in src/lib/parseArgs

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Yet another bug found with LLVM.
This appears to be a bug, but since I don't know the
program logic, the extra semicolon just *might* be
a very dubious feature.

Remove a semicolon from the end of an if statement

---

src/lib/jsonParseV2/utilsParse.h

Without this patch compilation fails with LLVM under Mac OS X with the
following and other related errors:
In file included from fiware-orion/src/lib/jsonParseV2/utilsParse.cpp:27:
fiware-orion/src/lib/jsonParseV2/utilsParse.h:41:15: error:
implicit instantiation of undefined template
'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
std::string error;

Add #include <string> to src/lib/jsonParseV2/utilsParse.h

---

src/lib/rest/rest.cpp

In some newer versions of microhttpd.h, MHD_USE_EPOLL is
an enum instead of being a #define.  This commit changes
the #if guarding its use

Change the recognition of MHD_USE_EPOLL support

---

src/lib/rest/rest.cpp

Slight modification of the PR so kindly offered by @pekkanikander 
Adding a line of explanation and changing the constant of MHD version to coincide 'exactly' with the comment: 0x00095102 => 0x00095100 (as comment says MHD 0.9.51 ...).
As I am not 100% sure that the change 0x00095102 => 0x00095100 might have some negative impact in mac ... Pekka, could you test in your machine and let me know if you have any problem with this change, please? And if so, propose a fix that works for you too ...

Slight change in MHD EPOLL detection

---

CHANGES_NEXT_RELEASE
CMakeLists.txt
doc/manuals/admin/build_source.md
doc/manuals/admin/cli.md
doc/manuals/admin/database_model.md
doc/manuals/user/security.md
docker/Dockerfile
scripts/accumulator-server.py
src/app/contextBroker/contextBroker.cpp
src/lib/common/globals.h
src/lib/logMsg/logMsg.h
src/lib/ngsiNotify/Notifier.cpp
src/lib/ngsiNotify/senderThread.cpp
src/lib/rest/httpRequestSend.cpp
src/lib/rest/rest.cpp
test/functionalTest/cases/0000_cli/bool_option_with_value.test
test/functionalTest/cases/0000_cli/command_line_options.test
test/functionalTest/cases/0000_cli/tracelevel_without_logLevel_as_DEBUG.test
test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications.test
test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test
test/functionalTest/harnessFunctions.sh
test/unittests/main_UnitTest.cpp

This PR started as a bugfix for https://github.com/telefonicaid/fiware-orion/issues/2844. However, at the end it could be a definitive implementation for native HTTPS notifications (issue https://github.com/telefonicaid/fiware-orion/issues/706).
The PR is largely based on the PR #717 (original attempt to implement #706) and @mariolg contributions to acumulator-server.py

FIX using libcurl to send notifications to HTTPS endpoints

---

doc/apiary/v2/fiware-ngsiv2-rc-2016_05_31.apib
doc/apiary/v2/fiware-ngsiv2-rc-2016_10_31.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

The *Subscription* / *Subscriptions By Id* / *Retrieve subscription* section of the apiary documentation contains a small bug making invalid JSON the response body provided as example.

Fix invalid json body in the Retrieve subscription section

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/parseArgs/paParse.cpp
src/lib/parseArgs/parseArgs.h
test/functionalTest/cases/0000_cli/tracelevel_without_logLevel_as_DEBUG.test

Created a new function `paCleanup()` to free allocated variables once the CLI parsing has finished.
Fixes issue #2928

Fixed issue 2926

---

src/lib/common/macroSubstitute.cpp

Although macroSubstitude() could be replaced soon by another kind of implementation, let's have the curresnt one as error-free as we can. Thus, this PR should be merged into master.

memory-leaks fixed in macroSubstitute.cpp

---

doc/manuals/admin/build_source.md

After installing all dependencies documented in the [Build from sources guide](https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/admin/build_source.md)
```
$ make valgrind
....
[100%] Built target contextBroker
make[2]: Leaving directory '/root/src/fiware-orion/BUILD_DEBUG'
Install the project...
-- Install configuration: "DEBUG"
-- Up-to-date: //usr/bin/contextBroker
make[1]: Leaving directory '/root/src/fiware-orion/BUILD_DEBUG'
For detailed info: tail -f /tmp/valgrindTestSuiteLog
test/valgrind/valgrindTestSuite.sh
Fri Jul  7 08:50:20 UTC 2017
Test 001/927: 0000_bad_requests/erroneous_input .............................................
........................................................ 
test/valgrind/valgrindTestSuite.sh: line 683: bc: command not found
....
```

Add bc dependency to the documentation on how to run the valgrind suite

---

doc/manuals/admin/build_source.md

This pull request pretends to improve the documentation about how to run orion tests. Mainly functional and valgrind tests.
It tries to fix this by moving documentation about valgrind tests after documentation about functional tests. This seems an improvements as the valgrind tests are usually run after passing the functional tests. Moreover, installing the `accumulator-server.py` script is required for running the functional tests, but it's also required for running the valgrind tests. By moving the valgrind documentation after the functional test, we ensure the user installed the accumulator script.

Improve documentation about how to pass orion tests

---

doc/manuals/admin/install.md
doc/manuals/admin/perf_tuning.md
test/functionalTest/cases/0676_servicepath_context_types/servicepath_sametype.test
test/functionalTest/cases/1367_time_measures/time_measure_stats.test

Orion supports MongoDB 3.4 without any change. It has been checked with the functional test regression (with a small adjust).

Declare MongoDB 3.4 support

---

README.md

Corrected "ent-to-end" with "end-to-end"

:pencil2: Correct a small typo

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoCreateSubscription.cpp

Fixes #2974 
Regression work in my local Debian machine. Jenkins regression (more complete, due to it does two phases, with and without cache) is on the way right now.

FIX missing lastsuccess and lastfailure

---

doc/manuals/user/walkthrough_apiv1.md

Example references Room 2, but in the example code it refers to Room1

Change Room1 -> Room2 (walkthrough_apiv1.md)

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Now that we are close to release a new RC (by the end of November) of NGSIv2 stable, it is a good time to do a little fixing in authors and editors affiliations.
@kzangeli @mrutid @jmcanterafonseca

Fix afiliations in NGSIv2 spec

---

src/lib/serviceRoutines/postSubscribeContext.cpp

This PR solves this problem found in .test in last night regression:
```
-----  Erroneous simple NGSI10 subscription with service path of two items  -----
(0675_servicePath_in_ngsi10_subscriptions/erroneous_ngsi10_subscription_with_two_service_paths.test) output not as expected
VALIDATION ERROR: input line:
HTTP/1.1 400 Bad Request
does not match ref line:
HTTP/1.1 200 OK
```
This problem seems to be cause by this particular line change in recent PR: https://github.com/telefonicaid/fiware-orion/pull/3034/files#diff-d1f63b595203e4a4cba617e43167a5ccR74
I don't understand how this has survived to the `make test` done in that PR (https://github.com/telefonicaid/fiware-orion/pull/3034#issuecomment-344567601). Which exact command did yo execute @arigliano ?

FIX broken 0675 test

---

CHANGES_NEXT_RELEASE
doc/manuals/user/README.md
doc/manuals/user/cors.md
src/lib/rest/HttpHeaders.h
src/lib/rest/rest.cpp
src/lib/rest/rest.h
src/lib/rest/restReply.cpp
src/lib/serviceRoutinesV2/optionsAllNotDelete.cpp
src/lib/serviceRoutinesV2/optionsGetDeleteOnly.cpp
src/lib/serviceRoutinesV2/optionsGetDeletePatchOnly.cpp
src/lib/serviceRoutinesV2/optionsGetOnly.cpp
src/lib/serviceRoutinesV2/optionsGetPostOnly.cpp
src/lib/serviceRoutinesV2/optionsGetPutDeleteOnly.cpp
src/lib/serviceRoutinesV2/optionsGetPutOnly.cpp
src/lib/serviceRoutinesV2/optionsPostOnly.cpp
test/functionalTest/cases/0501_cors/allowed_headers.test
test/functionalTest/cases/0501_cors/allowed_methods.test
test/functionalTest/cases/0501_cors/any_origin.test
test/functionalTest/cases/0501_cors/cors_bad_verbs.test
test/functionalTest/cases/0501_cors/exposed_headers.test
test/functionalTest/cases/0501_cors/get_any_origin.test
test/functionalTest/cases/0501_cors/get_specific_origin.test
test/functionalTest/cases/0501_cors/max_age.test
test/functionalTest/cases/0501_cors/max_age_default.test
test/functionalTest/cases/0501_cors/specific_origin.test

Access-Control-Expose-Headers is now sent in the response, allowing the client to access certain response headers. 
With this PR, I took the liberty to add some improvements to our logic with respect to the CORS specification: We are no longer adding any CORS headers to the response if the client fails to add Origin to the request or the Origin value does not match the one allowed by Orion.

ISSUE: 3030. CORS Expose Headers.

---

doc/manuals/devel/README.md

We have recently released three Orion versions, but I think they have no impact on the developers documentation, so I think the version number could be moved forward.
However, I'd like to have a second opition, so I cast this PR to get @kzangeli 's feedback :)
The detail of changes corresponding to these versions, in the case it helps is:
https://github.com/telefonicaid/fiware-orion/releases/tag/1.10.0
https://github.com/telefonicaid/fiware-orion/releases/tag/1.9.0
https://github.com/telefonicaid/fiware-orion/releases/tag/1.8.0

UPDATE reference Orion version in developers manual

---

rpm/SPECS/contextBroker.spec

I have realize of the following error in rpm build output:
```
bogus date in %changelog: Mon Jun 04 2013 Fermín Galán <fermin@tid.es> 0.3.0-1 (FIWARE-2.3.3-1)
```
Not sure the cause, but it seems that June 4th, 2013 was Tuesday, not Monday. Let's see if this PR solves :)

FIX changelog date

---

src/lib/apiTypesV2/Registration.cpp
src/lib/apiTypesV2/Registration.h
src/lib/jsonParseV2/parseRegistration.cpp
src/lib/mongoBackend/mongoRegistrationGet.cpp
src/lib/serviceRoutinesV2/postRegistration.cpp
test/functionalTest/cases/3004_v2_reg_create/v2_reg_create_errors.test

Adjusting legacyForwardingMode error message, as discussed previosuly on another PR.
At the same time, I've taken the opportunity to unhardwire a couple of values from render logic (in fact the hardwire stills, but at mongoBackend level, which is better).

FIX forwardingMode = false using Not Implemented error messages

---

doc/apiary/v2/fiware-ngsiv2-rc-2018_04_30.apib
doc/apiary/v2/fiware-ngsiv2-reference.apib

(Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3047)
Not rely to much in the diff shown by github. You need to compare with other docs in order to see the changes (using meld, tkdiff, etc.). In particular:
* Compare fiware-ngsiv2-rc-2018_04_30.apib with fiware-ngsiv2-rc-2017_11_30.apib in order to see the changes and check all them are taken into account in the changelog section of fiware-ngsiv2-rc-2018_04_30.apib
* Compare fiware-ngsiv2-rc-2018_04_30.apib with fiware-ngsiv2-reference.apib in order to see what is included in latest but not in stable.
@kzangeli @jmcanterafonseca

 New version of the NGSIv2 stable apib: RC-2018.04

---

doc/apiary/v2/fiware-ngsiv2-rc-2018_04_30.apib

This is a very minor documentation fix, but will help third-party developers down the line. Currently the titles for the endpoint names within the Apiary definition are inconsistent: for example list/retrieve are not used consistently. Without standard naming conventions Developers using `swagger-code-gen `can generate a simple NGSI proxy library, but this will be stuck  with inconsistent function names, making the generated library difficult to  use.
This PR amends the following: 
* Use list + Plural  for  GET calls that retrieve multiple entities
* Use get + Singular for GET calls that retrieve single entities
* Use create + Singular for POST calls that create single entities
* Use verb + Registration for all registration endpoints 
The reason for suggesting this standardization here is …

Standardize Endpoint titles within the Apiary Definition.

---

doc/apiary/v2/fiware-ngsiv2-reference.apib

Related to #3172 - Apply the following changes direct to the  **Reference** Apiary file
* Use list + Plural for GET calls that retrieve multiple entities
* Use get + Singular for GET calls that retrieve single entities
* Use create + Singular for POST calls that create single entities
* Use verb + Registration for all registration endpoints

Title Case the titles of the Reference Apiary Definition.

---

test/functionalTest/harnessFunctions.sh

Maybe this error only happens with modern versions of the mongo shell. I have faced it just after upgrading my mongo package, when all test start to fail due to `dbInit` caused:
```
2018-06-11T15:40:08.988+0200 I NETWORK  [thread1] getaddrinfo("ftest") failed: Name or service not known
2018-06-11T15:40:08.989+0200 E QUERY    [thread1] Error: couldn't initialize connection to host ftest, address is invalid :
connect@src/mongo/shell/mongo.js:240:13
```
I guess that it will not hurt to people using old versions of the mongo shell but it would be a good idea to check with some other system before merging this. Any feedback?

FIX mongo URL construction in harnessFunctions.sh

---

doc/manuals/deprecated.md
doc/manuals/devel/cookbook.md
doc/manuals/user/update_action_types.md
doc/manuals/user/walkthrough_apiv2.md

This was done in Orion 1.14.0 but I have found some issues in the documentation that this PR tries to solve.

FIX documentation regaring lowercase actionTypes for NGSIv2

---

doc/manuals/devel/cookbook.md

I recently needed to debug a .test under gdb. Based on the experience, I have wrote this "knowledgue pill", in the hope it may be usesul for other developers in the Context Broker community.

ADD receipt about debugging .test cases to devel doc

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/metadata.md
doc/manuals/user/ngsiv2_implementation_notes.md
doc/manuals/user/v1_v2_coexistence.md

FIX using "builtin" term instead of "system/builtin" for special attributes and metadata in NGSIv2 spec

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp
test/functionalTest/cases/2176_not_print_spurious_decimals/one_to_nine_decimals.test
test/functionalTest/cases/2383_round_number_to_nine_digits/round_number_to_nine_digits.test

This is a fix for #2603. However, this is considered a quick fix (note the `#if/#else` blocks), given there is ongoing discussion yet (see https://github.com/apinf/fiware-orion/pull/32).

FIX quick fix for the large integer wrong rendering in responses problem

---

ci/README.md
ci/rpm7/build-dep.sh
ci/rpm7/build.sh

This PR is based on the work done in https://github.com/telefonicaid/fiware-orion/pull/3192. It fix the build.sh CI script retval for the compliance tests. In addition, it includes some minor fixing and enhance README.md.
The results are:
It is ok test compliance file to fail, as compliance is broken in master branch (it will be fixes soon, the PR to achieve that already exists: https://github.com/telefonicaid/fiware-orion/pull/3230).
It is not ok that functional test to fail, but looking to the log, it seems to be a glitch and I don't pay too much importance. We'll fix in a separate PR if the problem stills.
Please @caa06d9c have a look and review.

Fix CI retval for compliance job (and some additional polishing on the CI work)

---

doc/apiary/v2/fiware-ngsiv2-reference.apib
doc/manuals/user/ngsiv2_implementation_notes.md

This PR modified the registrations part in order to delegate the forwarding aspects to external specification. At the end (given the existence of a separate "NGSI Context Source Forwarding Specification") I understand it is the proper way of dealing with this.

NGSIv2 fwd details

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Entity.cpp
src/lib/common/globals.h
src/lib/ngsi/ContextAttributeVector.cpp
test/functionalTest/cases/3000_allow_creation_transient_entities/create_transient_entity.test
test/functionalTest/cases/3000_allow_creation_transient_entities/filter_by_date_expires.test
test/functionalTest/cases/3000_allow_creation_transient_entities/filtering_in_out_date_expires.test
test/functionalTest/cases/3000_allow_creation_transient_entities/filtering_in_out_date_expires_in_notifications.test

Finally it was decided to have `dateExpires` as NGSIv2 builtin attribute (see https://github.com/telefonicaid/fiware-orion/pull/3220). This involves some changes in the implementation.
@arigliano as author of the original implementation it would be great if you could review this PR and provide feedback/aproval. The changes are small, only in the rendering part (which check if dateExpires is in the `attrs` filter, omitting it in negative case). Thanks!

ADD dateExpires as builtin attribute

---

doc/apiary/v2/fiware-ngsiv2-rc-2018_07_31.apib

(Similar to PR https://github.com/telefonicaid/fiware-orion/pull/3149)
Not rely to much in the diff shown by github. You need to compare with other docs in order to see the changes (using meld, tkdiff, etc.). In particular:
* Compare fiware-ngsiv2-rc-2018_07_31.apib with fiware-ngsiv2-rc-2018_04_30.apib in order to see the changes and check all them are taken into account in the changelog section of fiware-ngsiv2-rc-2018_04_30.apib
* Compare fiware-ngsiv2-rc-2018_04_31.apib with fiware-ngsiv2-reference.apib in order to see what is included in latest but not in stable.

New version of the NGSIv2 stable apib: RC-2018.07

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Subscription.cpp

Fixes https://github.com/telefonicaid/fiware-orion/issues/3256

FIX GET /v2/subscriptions and GET /v2/subscriptions/{id} crashes for permanent subscriptions created before version 1.13.0

---

doc/manuals/user/walkthrough_apiv1.md
doc/manuals/user/walkthrough_apiv2.md

* Fix typos and broken link in walkthrough_apiv1.md.
* Fix typos in walkthrough_apiv2.md.

Fix typos in doc

---

doc/manuals/user/pagination.md

* Restoring the "Ordering results" section in pagination.md. but, deleting a description regarding to NGSIv1. (related PR #3279)
* Fix typo

Restoring the "Ordering results" section in pagination.md

---

doc/apiary/v2/fiware-ngsiv2-2.0-2018_09_15.apib

Github shows this PR as a file renaming. Actually, it is the addition of a new file and deletion of an old one (fiware-reference.apib, not needed anymore as the specification work has ended and stable and latest doc coverge).

ADD final NGSIv2 .apib

---

makefile

It seems the current syntax works for lcov 1.11 but not lcov 1.13 (see details in https://stackoverflow.com/questions/52512768/lcov-remove-option-is-not-removing-coverage-data-as-expected/52515497#52515497)

lcov command line changes in makefile

---

src/lib/common/tag.h
src/lib/ngsi/Metadata.cpp
src/lib/serviceRoutinesV2/entryPointsTreat.cpp
src/lib/serviceRoutinesV2/semStateTreat.cpp

Related with #1298 
This PR ensures that old JSON_ macros are using only in the NGSIv1 renderint part. In fact, it seems that only JSON_STR is used at the end, the rest is not used and has been removed.

REFACTOR related with #1298

---

test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_deeper.test
test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_equals_subs.test
test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_lt_le_gt_ge_subs.test
test/functionalTest/cases/1156_mqfilters_and_compounds/mqfilters_and_compounds_patternmatch_subs.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_deeper.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_equals_subs.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_lt_le_gt_ge_subs.test
test/functionalTest/cases/1156_qfilters_and_compounds/qfilters_and_compounds_patternmatch_subs.test
test/functionalTest/cases/2339_json_native_types_in_v1/json_native_types_in_v1.test

I don't remember why we have REGEX([0|1]) in the .test but it seems (at least in my local, i.e. Debian 8) it is no longer needed.
Let's see the Travis opinion in this matter :) If it pass the test at Travis I guess we can merge the change.

FIX removed unneded REGEX([0|1]*) in .test

---

doc/manuals/contribution_guidelines.md
doc/manuals/devel/cookbook.md
doc/manuals/devel/mongoBackend.md
doc/manuals/devel/sourceCode.md

Related with #1298 
Basically, remove references to ContextElement and ContextElementVector (now removed) and include information about Json*Helper classes.
CC: @fisuda , as I understand that the Japanese version of devel manual should be updated after merging this PR.

Fix devel manual after changes implemented as part of #1298

---

src/lib/jsonParse/jsonParse.cpp
src/lib/jsonParseV2/parseAttributeValue.cpp
src/lib/jsonParseV2/parseContextAttributeCompoundValue.cpp
src/lib/jsonParseV2/parseContextAttributeCompoundValue.h
src/lib/jsonParseV2/parseMetadataCompoundValue.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/Metadata.cpp
src/lib/parse/CompoundValueNode.cpp
src/lib/parse/CompoundValueNode.h
src/lib/parse/compoundValue.cpp
src/lib/parse/compoundValue.h
test/functionalTest/cases/2457_json_tags_with_same_name/json_tags_with_same_name.test
test/unittests/parse/CompoundValueNode_test.cpp
test/unittests/parse/compoundValue_test.cpp

CompoundValuesNode class is simplified removing a bunch of extra fields not actually used (maybe there were useful when this class was developed, but now it is mature and there is no need for them).
The simplification has allowed to address easyly a couple of pending FIXME P7 issues:
```
// FIXME P7: next line is counterintuitive. If the object is a vector, why [...]
// FIXME P7: why don't have a case for Object (valueType = orion::ValueTypeObject) [...]
```

Simplification of CompoundValueNode class

---

doc/manuals/user/README.md

CC: @fisuda just in case the modification in this PR needs some sync in the Japanese translation

FIX user manual ToC in markdown

---

test/functionalTest/cases/3189_oneshot_subscription/3189_oneshot_subscription.test

This is a follow up of PR https://github.com/telefonicaid/fiware-orion/pull/3361
Travis CI only does a pass (without noCache) and the problem passed unnoticed. However, in a second-phase CI (jenkins based, which runs with `--noCache` activated in testHarness.sh) we find a test failing.
lastSuccess and timeSent information is created/updated when CB runs without cache or when runs with cache and the refresch time has passed. Thus, the solution is to add always lastSucess and timeSent in the expected output and introduce a wait period (1.5 times the cache interval, configured to the minimum possible value of 1 second with `-subCacheIval 1) so we ensure that even when CB runs with cache we will get that output in that step. This is the same technique used for instance in …

FIX ftest under nocache run

---

test/functionalTest/cases/0001_federation/federation_location_ngsiv1.test
test/functionalTest/cases/0001_federation/federation_location_ngsiv2.test

From https://github.com/telefonicaid/fiware-orion/pull/3380:
>(Curiously, branch bugfixing/3162_fix_but_potential_leak also includes a federation_problem.test.DISABLED test, but it is not related with forwarded queries. The .test is valuable related with federation features and I plan to reuse it, but not in this PR)
This PR included that .test (as federation_location_ngsiv1.test) and also a variant of it for NGSIv2. Note that in the NGSIv1 the coordinates are propagated as strings (due to the string-fication done in all NGSIv1 output).
Maybe it is a good idea if @caa06d9c could have a look to this, as if I remember correctly he was involved in setting this kind of federation scenarios in the past.

ADD two federation .test cases focused on location attribute

---

docker/Dockerfile
docker/README.md
docker/docker-compose.yml

It seems we misses updating this when Orion 2.1.0 was released.
@fisuda please take this into account to upgrade also the Japanese transaltion, pls.

Change to mongo 3.6 in docker-compose examples

---

README.md
doc/manuals.jp/devel/README.md
doc/manuals/devel/README.md

This PR change the links for introductory presentations for version 2.2.0. In addition, I have updated the reference version in devel manual.
@fisuda please have a look as I have touched one of the documents in the Japanese translation and provide LGTM if it is ok.

Prepare introductory presentations for Orion 2.2.0

---

doc/apiary/v2/fiware-ngsiv2-2.0.1-wip.apib

This PR is based on the feedback provided by @juliozinga in PR https://github.com/telefonicaid/fiware-orion/pull/3435 (thanks!). Although the diff in github shows a completely new file, actually the change with regards to the current .apib is minimal. It is shown below, for convenience:
```
fermin@neodeb:~/src/fiware-orion/doc/apiary/v2$ diff -u fiware-ngsiv2-2.0-2018_09_15.apib fiware-ngsiv2-2.0.1-wip.apib 
--- fiware-ngsiv2-2.0-2018_09_15.apib	2018-10-02 10:00:32.405584590 +0200
+++ fiware-ngsiv2-2.0.1-wip.apib	2019-04-12 09:59:34.183083883 +0200
@@ -39,6 +39,10 @@
+Changes since v2.0:
+
+* Typo fixing
+
Changes since RC-2018.07:
* None
@@ -434,7 +438,7 @@
Operations that retrieve lists of entities permit the `orderBy` URI parameter to specify the
-attributes or properties to be be used …
```

ADD fiware-ngsiv2-2.0.1-wip.apib file

---

ci/rpm7/build-dep.sh
ci/rpm7/makefile
doc/manuals/user/walkthrough_apiv2.md
scripts/accumulator-server.py
test/functionalTest/README.md
test/functionalTest/cases/2015_notification_templates/notification_templates_cache_refresh.test
test/functionalTest/cases/2015_notification_templates/notification_templates_many_notifications.test

We have recently found a bug in default Flask version installed by default in CentOS7 which impact in the NGSIv2 query forwarding functionality (Flask is being used by the accumulator-server.py script using in functional tests). This PR upgrades Flask version to 1.0.2, which doesnt' have the bug, using virtualenv.
@caa06d9c could you have a look and provide feedback and/or LGTM, pls? Given this PR touches the ci stuff you authored, I think you are the most appropiate reviewer :)

FIX upgrade Flask to 1.0.2 in ci dockerfile

---

test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test

Current .test works ok with normal run of test harness (i.e. just `testHarness.sh`), which is the one done by travis for instance.
However, one of our jenkins instances does two passes, one with just `testHarness.sh` and another adding CB_NO_CACHE=ON CB_THREADPOOL=OFF. The latter (CB_THREADPOOL=OFF) makes this .test to fail.
I don't like the fix too much (it's a kind of hack) so any other suggestion fixing the problem is welcome.

FIX direct_https_notifications_no_accept_selfsigned.test to cover both CB_THREADPOOL posibilities

---

test/functionalTest/cases/3068_ngsi_v2_based_forwarding/fwd_ngsv1_ngsv2_interoperability.test

This PR adds the interoperability case described in https://github.com/telefonicaid/fiware-orion/issues/3068#issuecomment-479933791:
> * Add a .test for NGSIv1-NGSv2 interoperability with the following steps:
>    1. Register E1-A1 in NGSIv1-based CPr
>    2. Register E1-A2 in NGSIv2-based CPr
>    3. Query GET /v2/entities/E1 and get E-(A1,A2) seamlessly
>    4. Query POST /v1/queryContext (for E1) and get E-(A1,A2) seamlessly

Add NGSIv1-NGSv2 forwarding interoperability case

---

src/lib/rest/ConnectionInfo.h

Solves the folllowing errors reported by valgrind check:
```
6 test cases show valgrind errors:
1033: fwd_v2_query_with_contextElement_providingApplicationList shows 21 valgrind errors
1044: fwd_v2_ngsiv2_query_double_forward shows 7 valgrind errors
1054: fwd_v2_ngsiv2_query_one_forward_query shows 7 valgrind errors
1055: fwd_v2_ngsiv2_query_shadowed_attribute shows 7 valgrind errors
1069: forwards_with_providers shows 49 valgrind errors
1070: fwd_ngsv1_ngsv2_interoperability shows 7 valgrind errors
```

FIX error reported by valgrind

---

README.md
doc/manuals.jp/quick_start_guide.md
doc/manuals/quick_start_guide.md

This PR replaces `fiware.github.io/context.Orion` => `fiware-ges.github.io/orion` since the location of spec has moved.

Fixing broken links, whitespace & etc.

---

doc/manuals/admin/cli.md

That option propotes from experimental to production a long time ago but it seems we forgot to update documentation :)

FIX typo in doc

---

CHANGES_NEXT_RELEASE
src/lib/jsonParse/jsonParse.cpp
src/lib/logMsg/logMsg.cpp
src/lib/metricsMgr/MetricsManager.cpp
src/lib/parseArgs/paParse.cpp
src/lib/parseArgs/paUsage.cpp

This PR address the comments done in issue https://github.com/telefonicaid/fiware-orion/issues/3578.
@Enkelmann could you do a pass with your code inspector in the PRs branch to know if the issues detected has been fixed?
@kzangeli it would be great if you could have a look to the fixes in the parseArgs and logMsg. I have tried to fix, but not sure if is right or it could be improved.

FIX NULL control in some strdup and calloc cases

---

doc/manuals/admin/cli.md

Based in:
```
/* ****************************************************************************
*
* Default timeout - 5000 milliseconds
*/
#define DEFAULT_TIMEOUT     5000
```
Surprisingly this important default wasn't mentioned in documentation.
@fisuda it would be great if you could also incorporate to the Japanase translation. Thanks!

Default httpTimeout in documentation

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR updates Japanese documentation of skipInitialNotification in ngsiv2_implementation_notes.md.

(JP) FIX improve documentation #3600

---

CMakeLists.txt
src/app/contextBroker/CMakeLists.txt
test/unittests/CMakeLists.txt

This is a draft of modifications to enable the building of CB in Debian 9.x (test done in Debian 9.11 in particular, after an upgrade from Debian 8) without harming other builds.
Originally I tried to set the old gcc/g++ version in Debian 8 (gcc /g++ 4.9), following the procedures in https://unix.stackexchange.com/questions/334888/how-install-g-4-9-on-debian-stretch and https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version, compiling both mongo driver and CB with it. Compilation step worked, but CB linking failed due to some obscure error related with boost.
Thus, I tried a different strategy: use the official Debian 9 gcc/g++ versión (gcc/g++ 6.0), after some slights modifications in the CMakeLists.txt files included in this PR. Again, I have linking problems …

Modifying CMakeList.txt to make build in Debian 9 to work

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoConnectionPool.cpp
src/lib/mongoBackend/mongoConnectionPool.h
test/unittests/testInit.cpp

Two improvements:
* We have mongInit -> mongoStart -> mongoConnectionPoolInit chain. This has been simplified to mongInit -> mongoConnectionPoolInit. Driver initialization now indluded in mongoConnectionPoolInit
* Factorice common code in mongoConnect for the standalone and rplset cases
This is kind of preparation for a more profound change in the context of #3132

Mongo connection refactor to make it simpler

---

src/lib/mongoBackend/mongoConnectionPool.cpp
src/lib/mongoBackend/mongoConnectionPool.h

After the simplification donde in PR https://github.com/telefonicaid/fiware-orion/pull/3619 a couple of functions are now internal to mongoConnectionPool.cpp, so they can be removed from the interface provided by mongoConnnectionPool.h. This PR does so.

FIX simplify mongobackend logic

---

CMakeLists.txt

This way the build system will be more resilient to the evolution of distributions.

FIX CMakeLists.txt compiler flags bases in gcc veresion instead of distro version

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/raspberry_pi.jp.md
docker/raspberry_pi.md

This PR adds a documentation how to build Orion binary for Ubuntu 18.04 LTS. By this, Orion can be directly run on Ubuntu for the x86_64 or aarch64 architecture. And the PR also includes fixing typos in build_source.md and raspberry_pi.md.
I have built and tested Orion with devices installed Ubuntu 18.04 LTS of each architecture. The build logs and test logs are here (https://github.com/fisuda/report/tree/master/orion/20200303_orion_ubuntu18.04).
In the case of the aarch64, One function test has failed as shown:
- 1697_more_than_one_bad_input
It seems that the issue is dependent on the timing. So, it passed by changing the value of `-logSummary` option.
Thank you.

Add documentation how to build Orion binary for Ubuntu 18.04 LTS

---

CHANGES_NEXT_RELEASE
README.md
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h
src/lib/common/defaultValues.h
src/lib/common/string.cpp

Hotfix 2.4.1 (in release/2.4.0). The same fix will be ported to master in a separate PR.
Regression unit_test:
```
...
[----------] Global test environment tear-down
[==========] 864 tests from 128 test cases ran. (48004 ms total)
[  PASSED  ] 864 tests.
YOU HAVE 16 DISABLED TESTS
------------------------------- unit_test ended ---------------------------------
```
Regression functional_test:
```
...
1144/1145: 3608_killer_request_apiv1/killer_request_apiv1_deeply_nested_attr.test .......................................  02 seconds
1145/1145: 3608_killer_request_apiv1/killer_request_apiv1_parsing_cases_bis.test ........................................  03 seconds
Total test time: 4524.06 seconds
1 test cases OK in the second attempt:
o …
```

FIX gmtime() -> gmtime_r() (release/2.4.0)

---

CHANGES_NEXT_RELEASE
src/lib/common/string.cpp

A backport of 6e4299ba2fd1458b1e3cd8f0d7b0374fb544af03 in PR https://github.com/telefonicaid/fiware-orion/pull/3698 (for branch release/2.4.0) into master.
Note this time we cannot use a cherry-pick, as the base of code to apply the change has changed from release/2.4.0 to current master.

 FIX gmtime() -> gmtime_r() (master)

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Before this PR I get valgrind fails in 151 tests (only first ones are shown):
```
151 test cases show valgrind errors:
029: ipv4_ipv6_both shows 10 valgrind errors
071: compound_subscription_json shows 10 valgrind errors
102: subscriptions_onchange shows 47 valgrind errors
111: subscription_sequence_onchange_expiration shows 5 valgrind errors
113: subscription_sequence_onchange shows 47 valgrind errors
114: subscription_sequence_wildcards_onchange_append-simpler shows 5 valgrind errors
116: subscription_sequence_wildcards_onchange_update shows 36 valgrind errors
154: deleteSubscriptionConvOp shows 5 valgrind errors
196: custom_metadata_onchange shows 68 valgrind errors
...
```
The error patter is as this one:
```
==67844== 12 errors in context 4 of 10:
==67844== Conditional jump or move …
```

FIX avoid valgrind errors in LM_T using same variable twice

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

This PR continues #3680, fixing the pending errors:
```
4 test cases show valgrind errors:
889: special_metadata_in_notifications_ngsiv1 shows 7 valgrind errors
890: special_metadata_in_notifications shows 7 valgrind errors
1102: notify_only_attributes_that_change_empty_cond_empty_notify shows 21 valgrind errors
1108: notify_only_attributes_that_change_with_cond_empty_notify shows 21 valgrind errors
``` 
Honestly, I'm not sure why this works, but anyway seems to be a improvements: if the notification is blocked due to throttling, there is no need of doing the `aList` preparation.

FIX some valgrind errors

---

rpm/SPECS/contextBroker.spec
scripts/accumulator-server.py
scripts/managedb/garbage-collector.py
scripts/managedb/latest-updates.py
scripts/monit_log_processing.py
test/check_rpm/check_rpm.sh
test/functionalTest/fixContentLengths.py
test/functionalTest/testDiff.py
test/functionalTest/testJson.py

This has arisen in the context of PR https://github.com/telefonicaid/fiware-orion/pull/3622. These are changes needed for rpm build in CentOS 8, which at the same time are compatible with CentOS 7 (as far as we have checked).

FIX make some changes to be more compatible with CentOS 8 RPM build procedure

---

CHANGES_NEXT_RELEASE
src/lib/mongoDriver/mongoConnectionPool.cpp

(This PR is one of the stages of the bigger PR #3622)
Final fixes and CNR entries.

FIX CNR and final fixes

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md

This PR updates the procedure to directly run Orion on Ubuntu (amd64 and aarch64). It would be great if you could review this PR.
Currently, the latest LTS (long term support) version of Ubuntu is 20.04. Therefore, I updated the build and test procedures with new mongo driver on Ubuntu 20.04 insted of 18.04. 
The build logs and test logs are the followings:
- https://github.com/fisuda/report/tree/master/orion/20210321_ubuntu20.04_amd64
- https://github.com/fisuda/report/tree/master/orion/20210321_ubuntu20.04_aarch64
One function test has failed as shown:
- 0706_direct_https_notifications
Related PR: https://github.com/telefonicaid/fiware-orion/pull/3622, https://github.com/telefonicaid/fiware-orion/pull/3632

Update procedure for Ubuntu 20.04 LTS (amd64 and aarch64)

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md

The `0706_direct_https_notifications` test for CentOS 8 fails on Ubuntu 20.04 because Orion built on Centos 8 and Orion built on Ubuntu 20.04 have different dependent libraries.  This PR updates function test procedure for Ubuntu 20.04 to avoid test failing.
The result of test is following:
https://github.com/fisuda/report/tree/master/orion/20210325_ubuntu20.04_0706_direct_https_notifications
It is needed to change three lines as shown:
```
$ git diff direct_https_notifications_no_accept_selfsigned.test
diff --git a/test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test b/test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test
index 812d8f36f..c6e1008d1 100644
--- …
```

Update function test procedure for Ubuntu

---

CHANGES_NEXT_RELEASE
src/lib/rest/rest.cpp
test/functionalTest/cases/3640_PATCH_update_with_wrong_servicepath/3640_PATCH_update_with_wrong_servicepath.test

Fix Issue #3640 for PATCH update operation when 'multiple ServicePath' or 'ServicePath with wildcard #' is used.

Fix for PATCH update operation when 'multiple SP' or 'SP with wildcard #' is used.

---

CHANGES_NEXT_RELEASE
doc/manuals.jp/admin/sanity_check.md
doc/manuals/admin/sanity_check.md
scripts/build/compileInfo.sh
src/lib/serviceRoutines/versionTreat.cpp
test/functionalTest/cases/0000_ipv6_support/ipv4_ipv6_both.test
test/functionalTest/cases/0000_version_operation/version_via_rest.test
test/functionalTest/cases/0501_cors/version_request.test
test/functionalTest/cases/1916_fiware_correlator/fiware_correlator.test
test/unittests/serviceRoutines/versionTreat_test.cpp

This PR adds  machine information in GET /version. It would be great if you could review this PR.
The examples are following:
- amd64
```
{
"orion" : {
"version" : "2.6.0-next",
"uptime" : "0 d, 0 h, 0 m, 4 s",
"git_hash" : "fffcc0ab1b75e3d067bc66d0f79943fce84a0e00",
"compile_time" : "Sat Mar 27 11:29:20 JST 2021",
"compiled_by" : "root",
"compiled_in" : "n5000",
"release_date" : "Sat Mar 27 11:29:20 JST 2021",
"machine" : "x86_64",
"doc" : "https://fiware-orion.rtfd.io/",
"libversions": {
"boost": "1_71",
"libcurl": "libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3",
"libmicrohttpd": "0.9.70",
"openssl": "1.1",
"rapidjson": "1.1.0",
"mongoc": "1.17.4",
"bson": "1.17.4"
}
}
}
```
- …

Add machine information in GET /version

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp

Before the PR:
```
INFO@12:49:49  contextBroker.cpp[1012]: start command line <contextBroker -fg -logForHumans -logLevel INFO>
INFO@12:49:49  contextBroker.cpp[1080]: Orion Context Broker is running
INFO@12:49:49  mongoConnectionPool.cpp[506]: Connected to mongodb://localhost/?connectTimeoutMS=10000 (dbName: orion, poolsize: 10)
INFO@12:49:49  contextBroker.cpp[1206]: Startup completed
```
After the PR:
```
INFO@2021-03-25T13:03:31.496Z  contextBroker.cpp[1012]: start command line <contextBroker -fg -logForHumans -logLevel INFO>
INFO@2021-03-25T13:03:31.496Z  contextBroker.cpp[1080]: Orion Context Broker is running
INFO@2021-03-25T13:03:31.518Z  mongoConnectionPool.cpp[506]: Connected to mongodb://localhost/?connectTimeoutMS=10000 (dbName: orion, poolsize: 10) …
```

FIX logForHumans including full time information

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/raspberry_pi.jp.md
docker/raspberry_pi.md

This PR updates documentation to support CentOS 8 aarch64 for Raspberry Pi. This is a way that Orion is run in a docker container on Raspberry Pi. It would be great if you could review this PR.
The test logs are the followings:
https://github.com/fisuda/report/tree/master/orion/20210325_centos8_aarch64
In the function test, one test has failed as shown:
- 1697_more_than_one_bad_input
This test may pass or fail. It seems that the issue is dependent on the timing.  This behavior is the same as before (https://github.com/telefonicaid/fiware-orion/pull/3630).
- more_than_one_bad_input.diff
```
VALIDATION ERROR: input file and reference file have different line count
```
- Expected (more_than_one_bad_input.regexpect)
```
3. grep SUMMARY in log-file (4 transactions, 1 bad input) …
```

Support CentOS 8 aarch64 for Raspberry Pi

---

doc/manuals/admin/perf_tuning.md

Add ) to close the parentheses to fix the typo error on perf_tuning.md file

Fix typo on perf_tuning.md

---

src/lib/apiTypesV2/HttpInfo.cpp
src/lib/apiTypesV2/HttpInfo.h
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/dbConstants.h
test/unittests/mongoBackend/mongoRegisterContext_test.cpp

This PR removes:
* Unneeded constructor in httpInfo
* Old casub lefovers (functionality removed in CB 2.6.0 time ago but it seems we missed some things ;)

FIX remove old stuff

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3347_createEntity_with_wrong_GeoJSON/createEntity_with_wrong_GeoJSON.test

New PR issue #3347 to fix the statusCode of createEntity (Post v2/entities) operation when wrongly formed GeoJSON sent.
(old PR #3733 )

Fix statusCode for createEntity (Post v2/entities op) with wrong GeoJSON

---

doc/manuals.jp/user/ngsiv2_implementation_notes.md

This PR fixes typo in doc/manuals.jp/user/ngsiv2_implementation_notes.md.

(JP) FIX typo (#3918)

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md

This PR adds documentation for building mosquitto 2.0.11 on Ubuntu 20.04.
It would be great if you could review this PR. Please see the following build log:
- https://github.com/fisuda/report/tree/master/orion/20210904_mosquitto_ubuntu20.04

Add documentation for building mosquitto on Ubuntu

---

rpm/SPECS/contextBroker.spec

The former URL is no longer working

FIX broken URL in .spec file

---

test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications.test
test/functionalTest/cases/0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test

See https://github.com/telefonicaid/fiware-orion/issues/3924#issuecomment-915900422

FIX temporarly disable HTTPS notification tests in valgrind pass

---

rpm/SPECS/contextBroker.spec

cmake is installed from source and therefore not recognized as an installed package. Needs to be removed for the build to work.

Update contextBroker.spec to fix rpm build

---

CHANGES_NEXT_RELEASE
doc/manuals/user/README.md
doc/manuals/user/ngsiv2_implementation_notes.md
doc/manuals/user/update_operators.md
doc/manuals/user/walkthrough_apiv2.md
mkdocs.yml
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/compoundValueBson.h
src/lib/mongoBackend/dbConstants.h
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
test/functionalTest/cases/0876_attribute_dates/attrs_dates_overridden_by_user.test
test/functionalTest/cases/3814_attribute_update_operators/addtoset_operator.test
test/functionalTest/cases/3814_attribute_update_operators/append_attribute_with_operator.test
test/functionalTest/cases/3814_attribute_update_operators/cover_all_update_flavours_with_operators.test
test/functionalTest/cases/3814_attribute_update_operators/creating_entity_with_operators.test
test/functionalTest/cases/3814_attribute_update_operators/creating_or_appending_operators.test
test/functionalTest/cases/3814_attribute_update_operators/inc_operator.test
test/functionalTest/cases/3814_attribute_update_operators/max_operator.test
test/functionalTest/cases/3814_attribute_update_operators/min_operator.test
test/functionalTest/cases/3814_attribute_update_operators/mul_operator.test
test/functionalTest/cases/3814_attribute_update_operators/pull_operator.test
test/functionalTest/cases/3814_attribute_update_operators/pullall_operator.test
test/functionalTest/cases/3814_attribute_update_operators/push_operator.test
test/functionalTest/cases/3814_attribute_update_operators/replace_entity_with_operators.test
test/functionalTest/cases/3814_attribute_update_operators/several_operators_same_update.test

Issue #3814
- MongoDB errors pass-through explanation
- Only works if operator is the first key, others keys (children > 0) are ignored. Random child if more than one.
- What happen in create or replace operations?
- Notification limitation (by the moment...)

Attribute operators (first part: without notifications)

---

doc/manuals/admin/database_admin.md

We got requests from users about the backup of MongoDB, since stopping the broker for backup interferes with the availability requirements. While stopping the broker for is required for sharded MongoDB installations, its not a necessity for replica-sets.

Concretize MongoDB-backup documentation

---

test/functionalTest/README.md

Added MQTT dependencies install step to functional tests readme 
Before installing the dependencies, trying to run the accumulator gives an output error:
```
Traceback (most recent call last):
File "/usr/bin/accumulator-server.py", line 61, in <module>
import paho.mqtt.client as mqtt
ImportError: No module named paho.mqtt.client
```

Update ftest readme python dependencies

---

CHANGES_NEXT_RELEASE
doc/manuals.jp/admin/logs.md
doc/manuals/admin/logs.md
src/lib/ngsiNotify/doNotify.cpp
src/lib/rest/httpRequestSend.cpp
src/lib/rest/httpRequestSend.h
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutines/postUpdateContext.cpp

Issue https://github.com/telefonicaid/fiware-orion/issues/4013
CC: @Anjali-NEC just in case you'd be interested in how the issue has been solved

FIX add subId/regId in "response NOT OK" WARN log traces

---

CHANGES_NEXT_RELEASE
doc/manuals/user/update_operators.md
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/3814_attribute_update_operators/set_and_unset_same_time.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator_all_types.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator_as_regular_update.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator_empty.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator_non_existing_attr.test
test/functionalTest/cases/3814_attribute_update_operators/set_operator_non_object.test
test/functionalTest/cases/3814_attribute_update_operators/several_operators_same_update.test
test/functionalTest/cases/3814_attribute_update_operators/unset_operator.test
test/functionalTest/cases/3814_attribute_update_operators/unset_operator_ignored_cases.test

somehow continues #3814 with new operator `$set`
* `{A: {value: {$set: {X: "foo"}}}}`
* `{A: {value: {$set: {X: 1}}}}`
* `{A: {value: {$set: {X: true}}}}`
* `{A: {value: {$set: {X: null}}}}`
* `{A: {value: {$set: {X: {object}}}}}`
* `{A: {value: {$set: {X: [array]}}}}`
* `{A: {value: {$set: "foo"}}}`
* `{A: {value: {$set: 1}}}`
* `{A: {value: {$set: true}}}`
* `{A: {value: {$set: null}}}`
* ~`{A: {value: {$set: <object>}}}`~ not really, this is not a regular update
* `{A: {value: {$set: <array>}}}`

ADD  $set update operator

---

.github/ISSUE_TEMPLATE/config.yml

Clarify the relationship between Stack Overflow and the GitHub Issues repo with some formatted boilerplate text.
-  It is only volunteers who monitor the [![Support badge](https://img.shields.io/badge/tag-fiware-orange.svg?logo=stackoverflow)](https://stackoverflow.com/questions/tagged/fiware)
-  It is  for **development questions only** <br>see `https://stackoverflow.com/help/how-to-ask`
- Stack Overflow is a (third-party) crowd-sourced question and answer website for professional and enthusiast programmers.
-  It is not affliated with this  software directly
- It does not answer **customer service related questions** <br>see `https://meta.stackoverflow.com/questions/255745/why-cant-i-ask-customer-service-related-questions`

Amend text related to StackOverflow

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/compoundValueBson.cpp
src/lib/mongoBackend/compoundValueBson.h
test/functionalTest/cases/0744_push_several_items_to_array/push_several_items_to_array.test

A fix for https://github.com/telefonicaid/fiware-orion/issues/744#issuecomment-996752938
Note this PR doesn't include documentation changes. Under my understanding the usage of `$each` (or any other modifier) is already covered by this statement in documentation (https://fiware-orion.readthedocs.io/en/master/user/update_operators/index.html#how-orion-deals-with-operators):
>  Thus, the execution semantics are the ones described in [MongoDB documentation](https://docs.mongodb.com/manual/reference/operator/update/) for the equivalent operands.

FIX $each usage with $push operator to add several items to array

---

test/functionalTest/cases/4041_cprs_https/ngsiv2_query_one_forward_query_https.test
test/functionalTest/cases/4041_cprs_https/ngsiv2_update_one_forward_https.test

New test cases arisen from issue #4041 
Tests are based in existing ones. The following diff shows the differents:
Query test:
```diff
--- cases/0787_cprs_full_functional_v2/ngsiv2_query_one_forward_query.test	2021-12-16 12:39:08.588628212 +0100
+++ cases/4041_cprs_https/ngsiv2_query_one_forward_query_https.test	2022-01-19 12:09:58.330223096 +0100
@@ -1,4 +1,4 @@
-# Copyright 2016 Telefonica Investigacion y Desarrollo, S.A.U
+# Copyright 2022 Telefonica Investigacion y Desarrollo, S.A.U
#
#
@@ -21,19 +21,24 @@
--NAME--
-One Forward Query To Context Provider, query made in NGSIv2
+One Forward Query To Context Provider (using HTTPS), query made in NGSIv2
--SHELL-INIT--
dbInit CB
dbInit CP1
-brokerStart CB
-brokerStart CP1
+brokerStart CB 0 IPV4 -insecureNotif
+
+# Run CP1 using HTTPS …
```

ADD CPr HTTPS test cases

---

.github/build-and-push-rpm.sh

CC: @wistefan 
I think this will be problem we have seen with names like contextBroker-3.5.0-release.x86_64.rpm. Let's check when 3.6.0 gets released ;)

FIX avoid "-release" in autogenerated release RPMs

---

ci/rpm8/build-dep.sh
docker/Dockerfile

Due to Centos8 EOL, building the Dockerfile was failing. This PR add a change in the repository base URL in order to keep working it. It changes the URL from `http://mirrorlist.centos.org/?release=$ ... fra=$infra` to `http://vault.centos.org/?release=$relea ... fra=$infra`

FIX Centos 8 repo list 

---

CHANGES_NEXT_RELEASE
README.md
doc/manuals/user/ngsiv2_implementation_notes.md
rpm/SPECS/contextBroker.spec
src/app/contextBroker/version.h
src/lib/common/defaultValues.h
src/lib/common/errorMessages.h
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/location.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/Metadata.h
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_general.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geobox.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geoline.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geopoint.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geopolygon.test
test/functionalTest/cases/1920_geojson/errors_geojson.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_more_than_one.test
test/functionalTest/cases/4032_extra_locs/extra_locs.test

This PR includes:
* First commit (aba0d19db50129810ccbfcff9a0d57b5d36243b5) with a port of PR https://github.com/telefonicaid/fiware-orion/pull/4051 to release/3.5.0 branch. Note the as a kind of checksum, the diff counter (616 additions and 54 deletions) is the same in this commit than in the PR.
* Second commit (~ad9947ab0~ d5a18d5272c0ce1f085e6c2fd68b47553a91b3a3) mimics PR https://github.com/telefonicaid/fiware-orion/pull/4002 and does the step version change from 3.5.0 to 3.5.1
A tag 3.5.1 will be created upon merging of this PR

ADD ignoreType (for extra locs) metadata feature (3.5 branch) + Bump 3.5.1

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Note orion::BSONObj hasField() signature is:
```
bool hasField(const std::string& field) const;
```
Thus I understand that although compiler doesn't complaint about it, hasField() on a char* is always evaluated to `false`.
What I wonder is how this has worked without problem until now... need to be analysed with a little of care
[ ] CNR ?

[WIP] FIX hasField calls wrongly using char* instead of std::string

---

.github/build-and-push-rpm.sh

Added a sed step to CI file stripping the version number in the filename (`X.Y.Z_next`) in case of uploading a nightly build.
This would fix uploading different version names depending of the release version to [here](https://nexus.lab.fiware.org/service/rest/repository/browse/el/8/x86_64/nightly/)

FIX different versions on RPM nightly repo

---

doc/manuals.jp/user/forbidden_characters.md

This PR updates Japanese documentation about URL decode in header values in custom notification.
Thanks!

(JP) Update doc about custom notification (#4072)

---

src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h

Solves error detected at valgrind pass (about unitialized value):
```
1 test cases show valgrind errors:
001: PUT_v1_contextEntities_E1_attributes_A1 shows 1 valgrind errors
```

FIX valgrind error about unitialized value

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/1494_subscription_alteration_types/sub_alteration_type_entity_delete2.test

The .test included in the first commit of this PR shows that the implementation done in https://github.com/telefonicaid/fiware-orion/pull/4084 has a flaw regarding entityDelete notifications.
Two comments:
* We need the an actual type when calling addTriggeredSubscription() in the delete logic (eP->type with "" causes this problem. Maybe a findAndModify() with removal semantics should be used? Maybe we already has this information in notifyCerP?
* The changes done in addTriggeredSubscription_noCache logic to skip type in some case should be rolled-back.

Fix entityDelete

---

test/functionalTest/cases/1492_limit_zero/limit_zero_simple_cases.test

limit zero errors are not currently covered in NGSIv2. The .test added in this PR is a NGSIv2 equivalent of case 3 in https://github.com/telefonicaid/fiware-orion/blob/master/test/functionalTest/cases/0000_bad_requests/pagination_error_in_uri_params.test
I have realized of this while working on PR #4104. Once this PR gets merged into master, PR #4104 will be upgrade and limit_zero_simple_cases.test changed to valid `[]` responses.

ADD cases/1492_limit_zero/limit_zero_simple_cases.test

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/mongoBackend/location.cpp
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_geo_json.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_feature_errors.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_feature_support.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_featurecollection_support.test

ADD GeoJSON Feature type support

---

CHANGES_NEXT_RELEASE
doc/manuals/user/ngsiv2_implementation_notes.md
src/lib/mongoBackend/location.cpp
src/lib/mongoBackend/location.h
src/lib/ngsi/ContextAttribute.cpp
test/functionalTest/cases/4114_geojson_feature_support/geojson_feature_support.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_featurecollection_support.test

FIX Feature and FeatureCollection support to implement geometry normalization

---

.github/build-and-push-rpm.sh
.github/workflows/functional.yml
.github/workflows/publishrpm.yml
.github/workflows/unit.yml

Time ago we moved from CentOS 8 to Debian, but it seems some tokens in workflow directory weren't changed.

FIX github workflow image

---

src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/mongoBackend/location.cpp
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geobox.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geoline.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/errors_geopolygon.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_feature_errors.test
test/functionalTest/cases/4114_geojson_feature_support/geojson_feature_errors_ignoretype.test

The check for Feature and FeatureCollection cannot be done at paring stage, due to it depends on the existence of ignoreType metadata in the entity. This PR fixes that.
In addition, we have done some homogenization in `descriptions` in error responses, including the ""error parsing location attribute: " prefix in all the cases

FIX ingoreType for Feature and FeatureCollection

---

doc/manuals/orion-api.md

This PR is intended to add a section with URL parameters (such as `entityId` and `attrName`) to each API route that have them.

Add URL parameters to API doc

---

test/functionalTest/cases/3001_mqtt/mqtt_subscription_multibroker.test

This PR should solve the annoying glitch with mqtt_subscription_multibroker.test that sometimes we see

FIX mqtt_subscription_multibroker.test glitch due to notification reception order

---

mkdocs.yml

This PR adds orion-api.md file to the Read the docs documentation

Include `orion-api.md` into Read the docs documentation

---

docker/Dockerfile.alpine

Alpine 3.16.0 has been released.

FIX upgrade Alpine version from 3.15.0 to 3.16.0 in Dockerfile.alpine

---

CHANGES_NEXT_RELEASE
doc/manuals/deprecated.md
doc/manuals/orion-api.md

FIX mark GET /v2 operation as deprecated

---

doc/manuals/admin/database_model.md
doc/manuals/orion-api.md

Reordering according [this plan](https://github.com/telefonicaid/fiware-orion/pull/4141#issuecomment-1222017142)
Note diff is +1,253 -1,254 deletions (the different is due to a repeated entry in ToC, now fixed), which somehow shows that the PR is just moving content.

FIX reordering section in orion-api.md

---

README.md
doc/manuals/orion-api.md
scripts/apib_renders/contextbroker-build-docgen.sh
scripts/apib_renders/ngsiv2-upload-stable-cookbook.sh
scripts/apib_renders/ngsiv2-upload-stable-spec.sh

Fix preamble wording and links to old NGSIv2 spec

FIX preamble and NGSIv2 spec links

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/mongoQueryTypes.cpp
test/functionalTest/cases/4216_get_types_miss_attr_types/get_types_miss_attr_types.test

Issue #4216 
CC: @ArqamFarooqui110719

FIX GET /v2/types and GET /v2/types/{type} wrong attribute types result

---

src/lib/common/globals.h
src/lib/mongoBackend/TriggeredSubscription.cpp
src/lib/mongoBackend/TriggeredSubscription.h
src/lib/mongoBackend/mongoSubCache.cpp
test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_trigger_after_update.test

Fixes a crash situation (checked by the .test file included in this PR) discovered by @danielvillalbamota 
No need of CHANGES_NEXT_RELEASE entry given that is a fix in a functionality introduced post-3.7.0.
Some minor cleanup in TriggeredSubscriptions and globals.h spotted while working on this.

FIX fail in csub cache logic that may make CB to crash in some cases

---

ci/deb/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/Dockerfile
docker/Dockerfile.alpine

use HTTPS for downloading *libmicrohttpd* and *Mosquitto*.
both web servers (i.e. `gnu.org` and `mosquitto.org`) are not configured to redirect to HTTPS.

use HTTPS for downloads

---

doc/manuals/orion-api.md
test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_errors.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_replacements_inside.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_http_json_replacements_inside_multi.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_constants.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_errors.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_replacements_inside.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_replacements_inside_multi.test
test/functionalTest/cases/2560_custom_notification_json/custom_notification_mqtt_json_replacements_intermediate.test

Additional tests for #2560 along with documentation improvements.
No CNR entry needed. This is already covered by current entry:
```
- Add: json field in httpCustom and mqttCustom subscriptions to implement JSON-based payloads in notifications (#2560)
```

ADD custom notification json field additional tests

---

src/lib/apiTypesV2/Entity.cpp
src/lib/apiTypesV2/Entity.h
src/lib/apiTypesV2/EntityVector.cpp
src/lib/ngsi/ContextElementResponse.cpp
src/lib/ngsi/ContextElementResponse.h
src/lib/ngsi/ContextElementResponseVector.cpp
src/lib/ngsi/ContextElementResponseVector.h
src/lib/ngsi10/QueryContextResponse.cpp
src/lib/ngsi10/UpdateContextResponse.cpp
src/lib/serviceRoutines/getAllEntitiesWithTypeAndId.cpp
src/lib/serviceRoutines/getIndividualContextEntity.cpp
test/unittests/apiTypesV2/Entity_test.cpp
test/unittests/ngsi/ContextElementResponseVector_test.cpp
test/unittests/ngsi/ContextElementResponse_test.cpp

Implement some toJsonV1() wrapper to avoid `emptyV` dirty thing.
(NGSIv1 is deprecate but this code was hurting my eyes :)

FIX toJsonV1 wrappers to simplify usage

---

doc/roadmap.md

By the moment just striking the entries. In the next mayor review of the roadmap all the striked ones will be moved to "Features already completed" section.

Strike complete items in 

---

src/lib/mongoBackend/MongoCommonUpdate.cpp

Attempt to fix some leaks detected in https://github.com/telefonicaid/fiware-orion/actions/runs/3603373377/jobs/6237874123
```
4 tests leaked memory:
1417: 4159_custom_notif_extra_macros/custom_notif_extra_macros_http_json.test (lost 592 bytes, see custom_notif_extra_macros_http_json.valgrind.out)
1418: 4159_custom_notif_extra_macros/custom_notif_extra_macros_http_json_attr_override.test (lost 592 bytes, see custom_notif_extra_macros_http_json_attr_override.valgrind.out)
1421: 4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_json.test (lost 592 bytes, see custom_notif_extra_macros_mqtt_json.valgrind.out)
1422: 4159_custom_notif_extra_macros/custom_notif_extra_macros_mqtt_json_attr_override.test (lost 592 bytes, see custom_notif_extra_macros_mqtt_json_attr_override.valgrind.out …
```

FIX memory leaks in nocache csub logic

---

src/lib/jsonParseV2/parseSubscription.cpp

Detected in https://github.com/telefonicaid/fiware-orion/actions/runs/3706314217/jobs/6281370472
```
2 tests leaked memory:
915: 2560_custom_notification_json/custom_notification_http_json_errors.test (lost 112 bytes, see custom_notification_http_json_errors.valgrind.out)
924: 2560_custom_notification_json/custom_notification_mqtt_json_errors.test (lost 112 bytes, see custom_notification_mqtt_json_errors.valgrind.out)
```

FIX memory leak in parseSubscription logic

---

doc/manuals.jp/devel/httpHeaders.md
doc/manuals.jp/user/cors.md
doc/manuals/devel/httpHeaders.md

This PR adds Japanese documentation about "Authorization" in the list of Cors allowed headers. It would be great if you could review this PR. Thanks.

(JP) ADD doc about "Authorization" in the list of Cors allowed headers (#4249)

---

doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md

openssl version slightly changed after Debian 11.6 upgrade (PR https://github.com/telefonicaid/fiware-orion/pull/4258)

FIX openssl library version in documentation

---

docker/Dockerfile
docker/Dockerfile.alpine

After upgrading to mongoc 1.23.1 in PR https://github.com/telefonicaid/fiware-orion/pull/4259 we get this error when building Dockerfile:
```
2023-01-11T10:03:52Z [91mAdding -fPIC to compilation of mongoc_static components
2023-01-11T10:03:52Z [0m[91mCMake Error at src/libmongoc/CMakeLists.txt:868 (message):
2023-01-11T10:03:52Z MONGOC_TEST_USE_CRYPT_SHARED is enabled, but we were unable to find a
2023-01-11T10:03:52Z Python 3 interpreter to use mongodl.py. Install a Python 3 or set
2023-01-11T10:03:52Z MONGOC_TEST_USE_CRYPT_SHARED to FALSE
```
This PR should fix it.

FIX Dockerfile to make them work after mongoc-1.23.1 upgrade

---

doc/manuals/orion-api.md

This PR corrects typo about `/v2/types` in `doc/manuals/orion-api.md`. It would be great if you could review the PR. Thanks.

Fix typo about /v2/types

---

test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_constant_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_constant_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_full_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_full_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_partial_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_with_filtering.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_with_filtering_in_compounds.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_without_any_source_attribute.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_without_some_source_attributes.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_change_attr_type.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_empty.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_constant_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_constant_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_constant_id.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_constant_type.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_full_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_full_replacement_id.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_full_replacement_type.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_partial_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_partial_replacement_id.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_partial_replacement_type.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_with_filtering.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_with_filtering_in_compounds.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_missing_macros.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mix_mapping_and_adding.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_more_than_one_macro_ocurrence.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_special_macros.test

Continuation of PR https://github.com/telefonicaid/fiware-orion/pull/4302. It seems the sleep delay in some test was not enought, due to the fails detected when that PR landed to master.

FIX sleep time in MQTT ftest

---

test/functionalTest/cases/3727_avoid_triggering_notification_if_metadata_changes_but_not_the_attribute_value_itself/notifyOnMetadataChange_false_in_condition-no_value.test

This test is based with the ones included by @chetan-NEC in PR https://github.com/telefonicaid/fiware-orion/pull/4300. It covers the current behaviour of CB (as in master) so we can ensure the modifications in PR #4300 doesn't break backward compatibility.
It comes from: https://github.com/telefonicaid/fiware-orion/pull/4300#discussion_r1154138624

ADD complementary case 3727 test

---

doc/manuals.jp/orion-api.md

This PR update Japanese documentation about entityDelete. It would great if you could review the PR. Thanks.

(JP) Update documentation about entityDelete

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
src/lib/mongoBackend/MongoGlobal.h
src/lib/mongoBackend/mongoGetSubscriptions.cpp
src/lib/mongoBackend/mongoRegistrationGet.cpp
src/lib/mongoDriver/connectionOperations.cpp
src/lib/mongoDriver/connectionOperations.h
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/geoquery_circle_geopoint_count.test
test/functionalTest/cases/1038_ngsiv2_geo_location_entities/geoquery_polygon_geopoint_count.test

The first commit in this PR raises the problem, in the form of .test.
As can be seen, the test/functionalTest/cases/1038_ngsiv2_geo_location_entities/geoquery_circle_geopoint_count.test test is not working. A `$geoNear, $near, and $nearSphere are not allowed in this contex` is raised in the collectionRangedQuery() function, in particular when mongoc_collection_count_documents is called
Curiosly, other geo-queries works with problem with count. Note the test/functionalTest/cases/1038_ngsiv2_geo_location_entities/geoquery_polygon_geopoint_count.test test is working.
Related: https://stackoverflow.com/questions/76409607/geonear-near-and-nearsphere-are-not-allowed-in-this-context-error-with-mong
Pending:

FIX count with geo near is not working

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/location.cpp

Backport of PR https://github.com/telefonicaid/fiware-orion/pull/4371
(Previous attempt PR https://github.com/telefonicaid/fiware-orion/pull/4372 was wrongly using master as base branch)

FIX logDeprecate not working correctly (release/3.10.0)

---

doc/manuals.jp/orion-api.md

This PR adds servicePath builtin attr to Japanese orion-api.md. It would be great if you could review the PR. Thanks.

(JP) ADD servicePath builtin attr to orion-api.md (#4389)

---

CHANGES_NEXT_RELEASE
src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttributeVector.cpp

this PR fixes #4387 and fixes typos of `unknown operator` messages.

Improve log trace

---

doc/manuals.jp/orion-api.md
doc/manuals/orion-api.md

FIX improve ordering results documetation in orion-api.md

---

CHANGES_NEXT_RELEASE
CMakeLists.txt
ci/deb/build-dep.sh
doc/manuals.jp/admin/build_source.md
doc/manuals/admin/build_source.md
docker/Dockerfile
docker/Dockerfile.alpine

This PR is to build de ci image so we can regression if Orion will work with the new version of the driver in Debian 11. We will manually launch the CI image build in dockerhub, then re-launch tests in ~master~ this branch (code is the same as in master) branch.

FIX change mongo driver to 1.24.3 in build-dep.sh (ci image)

---

docker/Dockerfile
docker/Dockerfile.alpine

This typo was introduced in PR https://github.com/telefonicaid/fiware-orion/pull/4415

FIX comment in Dockerfiles

---

docker/raspberry_pi.jp.md
docker/raspberry_pi.md

This PR adds documentation about how to use Orion in Docker on Raspberry Pi OS. 
Currently, The official distribution of Raspberry Pi is Raspberry Pi OS Bookworm 12 (stable). Therefore, this PR switches the distribution from Ubuntu to Raspberry Pi OS for using Orion in Docker on Raspberry Pi.
It would be great if you could review the PR.
Thanks.

ADD documentation about how to use Orion in Docker on Raspberry Pi OS

---

docker/Dockerfile
docker/Dockerfile.alpine
docker/README.jp.md
docker/README.md

This PR adds the `IMAGE_NAME` argument to Dockerfile. For example, Orion with Ubuntu 22.04 as a base image can be build as shown:
```
docker build -t orion-ubuntu22.04 --build-arg IMAGE_NAME=ubuntu --build-arg IMAGE_TAG=22.04 --build-arg CLEAN_DEV_TOOLS=0
```
The build logs:
- [build_on_ubuntu_22_04_x86_64.log](https://github.com/fisuda/report/blob/master/orion/20230910_ubuntu22.04_in_docker/build_on_ubuntu_22_04_x86_64.log)
- [build_on_ubuntu_22_04_arrch64.log](https://github.com/fisuda/report/blob/master/orion/20230910_ubuntu22.04_in_docker/build_on_ubuntu_22_04_arrch64.log)
Result:
- Orion on Ubuntu 22.04 (x86_64)
```
$ curl http://localhost:1026/version
{
"orion" : {
"version" : "3.10.0-next",
"uptime" : "0 d, 0 h, 0 m, 13 s",
"git_hash" : "7b6275bb053701af043ed05536ce8facc46f0efc", …
```

ADD IMAGE_NAME arg to Dockerfile

---

CMakeLists.txt
scripts/build/osDistro.sh

This PR adds Alpine 3.16.x as the distribution with old SSL version. It would be great if you could review this PR.
How to build:
```
docker build -t orion.alpine -f Dockerfile.alpine --build-arg GITHUB_ACCOUNT=fisuda --build-arg GIT_NAME=fisuda --build-arg GIT_REV_ORION=hardening/use_old_ssl_version --progress plain . |& tee /tmp/build.log
```
The full log is here: [20230911_PR_#4425_alpine_3_16_x/build.log](https://github.com/fisuda/report/blob/master/orion/20230911_PR_%234425_alpine_3_16_x/build.log)
- ./scripts/build/osDistro.sh
```
$ docker run -it --rm -v /home/fisuda/fiware-orion:/work alpine:3.16.0 sh
/ # /work/scripts/build/osDistro.sh
Alpine_3.16.0/ #
```
Thanks.

ADD Alpine 3.16.x as distribution with old SSL version

---

doc/manuals.jp/orion-api.md

This PR fixes tyopos in doc/manuals.jp/orion-api.md. It would be great if you could review this PR. Thanks.

(JP) FIX typos (#4432)

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/jsonRequestTreat.cpp
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/jsonParseV2/parseContextAttribute.h
src/lib/jsonParseV2/parseEntity.cpp
src/lib/jsonParseV2/parseEntityObject.cpp
src/lib/jsonParseV2/parseSubscription.cpp
test/functionalTest/cases/4435_ngsi_patching_special_attr_types/ngsi_patching_special_attr_types.test

FIX DateTime and geo:json support in custom notifications using ngsi patching

---

doc/manuals.jp/user/walkthrough_apiv2.md
test/functionalTest/README.jp.md

This PR adds Japanese documentation about Flask dependency. It would be great if you could review the PR.
Thanks.

(JP) ADD documentation about Flask dependency (#4437)

---

doc/manuals/orion-api.md

Orion documentation lacks a geofencing subscription example, and it is not pretty straightforward from documentation, since it is almost based on queries, not on subscriptions. 
Maybe extending this table field here could help:
https://github.com/telefonicaid/fiware-orion/blob/442541c990f8f50165207cfc88c7bb8afae28300/doc/manuals/orion-api.md?plain=1#L3654
@fgalan what do you think?

[Doc] Add geofencing subscription example

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/logs.md
src/lib/common/logTracing.cpp
src/lib/common/logTracing.h
src/lib/ngsiNotify/doNotify.cpp
test/functionalTest/cases/0000_deprecated_checkings/log_deprecate_warning.test
test/functionalTest/cases/3001_mqtt_alarms/mqtt_alarms_none.test
test/functionalTest/cases/3001_mqtt_alarms/mqtt_alarms_raise_and_release.test
test/functionalTest/cases/3001_mqtt_alarms/mqtt_alarms_raise_repeat_and_release.test
test/functionalTest/cases/3694_logs_improvements/log_notifications.test
test/functionalTest/cases/4449_notification_payload_in_logs/notification_payload_in_logs.test

Issue #4449 
- NGSIv2
- Simplified NGSIv2
- Custom text-based
- Empty payload

ADD notification payload in INFO log traces

---

CHANGES_NEXT_RELEASE
doc/manuals/admin/diagnosis.md
doc/manuals/orion-api.md
doc/manuals/user/known_limitations.md
src/lib/jsonParseV2/parseNotification.cpp
src/lib/jsonParseV2/parseRegistration.cpp
src/lib/mongoBackend/mongoSubscribeContext.cpp
src/lib/mongoBackend/mongoUpdateContext.cpp
src/lib/mongoBackend/mongoUpdateContextSubscription.cpp
src/lib/rest/OrionError.cpp
src/lib/rest/OrionError.h
src/lib/rest/RestService.cpp
src/lib/rest/rest.cpp
src/lib/serviceRoutines/postQueryContext.cpp
src/lib/serviceRoutinesV2/getEntities.cpp
src/lib/serviceRoutinesV2/getEntityAttribute.cpp
src/lib/serviceRoutinesV2/putEntityAttribute.cpp
src/lib/serviceRoutinesV2/serviceRoutinesCommon.cpp
test/unittests/mongoBackend/mongoCreateSubscription_test.cpp
test/unittests/mongoBackend/mongoGetSubscriptions_test.cpp
test/unittests/rest/OrionError_test.cpp

Change OrionError fields to use proper names aligned with NGSIv2 terminology. In particular:
* reasonPhrase -> error
* details -> description

FIX OrionError field names refactor

---

doc/requirements.txt

Recent upgrade in jinga2 dependency (PR https://github.com/telefonicaid/fiware-orion/pull/4470) breaks mkdocs. This upgrade supposedly solves the problem (see https://github.com/mkdocs/mkdocs/issues/2799#issuecomment-1079764329)

FIX mkdocs version from 1.2.3 to 1.2.4

---

src/lib/mongoBackend/MongoCommonUpdate.cpp
src/lib/mongoBackend/MongoGlobal.cpp
test/functionalTest/cases/3190_notify_only_attributes_that_change/notify_only_attributes_that_change_with_alteration_type_on_entity_delete.test

Follow up of PR https://github.com/telefonicaid/fiware-orion/pull/4471
The onlyChangedAttrs: true + condition.alterationTypes: entityDelete case was not working properly.

FIX onlyChagnedAttrs true with alterationType for entityDelete case

---

README.md
src/lib/apiTypesV2/Subscription.h

This PR will be closed without merge after use.
Similar to PR https://github.com/telefonicaid/fiware-orion/pull/4370

Valgrind regression for 3.11.0 + fixes

---

scripts/entities_consistency/entities_consistency.py
scripts/entities_consistency/test_entities_consistency.py
scripts/entities_consistency/validation_data.js

Improves the existing entities_consistency_script.py:
* New argument `--include-entities-date` to include entity last modification timestamp in traces
* Right support for `Feature` and `FeatureCollection` in geo:json attributes (previously to this fix, they were detected as false positive in Rule16)
* Correctly processing of `null` geo:json as no-location attribute (previous to this fix, this was causing false positives in Rules16)
* Detect empty entities collections (probably are databases to remove)
* Improve statistics reporting (failing entities, percentage, etc.).

FIX improve entities consisency script

---

src/lib/alarmMgr/AlarmManager.cpp
src/lib/alarmMgr/AlarmManager.h
src/lib/common/sem.cpp
src/lib/common/sem.h
src/lib/metricsMgr/MetricsManager.cpp
src/lib/metricsMgr/MetricsManager.h
src/lib/mqtt/MqttConnectionManager.cpp
src/lib/mqtt/MqttConnectionManager.h
test/unittests/common/commonSem_test.cpp

Simplifications:
* Use LM_X isntead of LM_E if semaphore initialization fails. Semaphore initialization takes place in Orion startup and it's so severe that Orion should refuse to start in that case
* Simplification of the return values in the init methos for existing managers.
This is mainly a minor hardening fix, so I think it doesn't worth to be mentioned in CNR file.

FIX simplify init methods in managers

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp
src/lib/mongoDriver/mongoConnectionPool.cpp
test/functionalTest/cases/3658_env_vars/env_vars.test

This pull request resolves the configuration conflict identified in issue [#4496](https://github.com/telefonicaid/fiware-orion/issues/4496), where using the -dbURI parameter along with the default dbTimeout value caused startup failures in Orion.
**Key Changes**
- Modified the composeMongoUri function to handle a default dbTimeout value of -1, enabling it to work seamlessly with the -dbURI parameter.
- Implemented a condition to set dbTimeout to 10000 if it is at its default value of -1. This maintains the standard behavior when -dbURI is not being used, thus ensuring backward compatibility.
- Adjusted the error validation logic in composeMongoUri to prevent false triggering of configuration conflicts when dbTimeout is in its default state.
These changes improve the usability of the Orion …

FIX -dbTimeout conflict with -dbURI (#4496)

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp

Solves the problem reported at https://github.com/telefonicaid/fiware-orion/issues/4496#issuecomment-1916898626
Probably there are more times apart from `PaULong` to take into account. The new error trace in the `else` branch would help to detect them in the future.
Some traces:
```
$ ORION_MONGO_URI=mongodb://localhost:27017 ORION_MONGO_TIMEOUT=0 contextBroker -fg -logLevel INFO -logForHumans
INFO@2024-02-06T08:37:58.151Z  contextBroker.cpp[1110]: start command line <contextBroker -fg -logLevel INFO -logForHumans>
INFO@2024-02-06T08:37:58.151Z  contextBroker.cpp[972]: env var ORION_MONGO_URI (-dbURI): mongodb://localhost:27017
INFO@2024-02-06T08:37:58.151Z  contextBroker.cpp[984]: env var ORION_MONGO_TIMEOUT (-dbTimeout): 0
INFO@2024-02-06T08:37:58.151Z  contextBroker.cpp[1184]: Orion …
```

FIX wrong INFO startup log showing ORION_MONGO_TIMEOUT, ORION_IN_REQ_PAYLOAD_MAX_SIZE and ORION_OUT_REQ_MSG_MAX_SIZE env var values

---

test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_full_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_full_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_partial_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_with_filtering.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_with_filtering_in_compounds.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_without_any_source_attribute.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_adding_without_some_source_attributes.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_mapping_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_mapping_with_filtering.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_full_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_full_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_partial_replacement_attribute_compound.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_with_filtering.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_with_filtering_in_compounds.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_without_any_source_attribute.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_adding_without_some_source_attributes.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_partial_replacement_attribute_simple.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_mapping_with_filtering.test

This change in keys ordering has no functional impact in ftest.
We are doing it in preparation of PR https://github.com/telefonicaid/fiware-orion/pull/4511, where the cjexl implementation does a key sorting.

FIX sort keys in JSON used in test

---

doc/manuals/user/walkthrough_apiv2.md

This PR improves the syntax highlightling of your API walkthrough documentation page. Without this change, the individual snippets are recognized as arbitrary language, rendering it hard or impossible to read. The following screenshot shows an extreme case where a shell command is highlighted as CSS with important bits blacked out.

Consistent syntax highlighting in API walkthrough

---

src/lib/alarmMgr/CMakeLists.txt
src/lib/apiTypesV2/CMakeLists.txt
src/lib/cache/CMakeLists.txt
src/lib/common/CMakeLists.txt
src/lib/convenience/CMakeLists.txt
src/lib/jsonParse/CMakeLists.txt
src/lib/jsonParseV2/CMakeLists.txt
src/lib/logMsg/CMakeLists.txt
src/lib/logSummary/CMakeLists.txt
src/lib/metricsMgr/CMakeLists.txt
src/lib/mongoBackend/CMakeLists.txt
src/lib/mongoDriver/CMakeLists.txt
src/lib/mqtt/CMakeLists.txt
src/lib/ngsi/CMakeLists.txt
src/lib/ngsi10/CMakeLists.txt
src/lib/ngsi9/CMakeLists.txt
src/lib/ngsiNotify/CMakeLists.txt
src/lib/orionTypes/CMakeLists.txt
src/lib/parse/CMakeLists.txt
src/lib/rest/CMakeLists.txt
src/lib/serviceRoutines/CMakeLists.txt
src/lib/serviceRoutinesV2/CMakeLists.txt

Fixed this annoying warning at building time:
```
CMake Deprecation Warning at src/lib/cache/CMakeLists.txt:21 (CMAKE_MINIMUM_REQUIRED):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Note that in the root CMakeList.txt we already have
```
cmake_minimum_required(VERSION 3.0)
```
so this PR is aligning that in the rest of CMakeList.txt files.

FIX CMAKE_MINIMUM_REQUIRED

---

CHANGES_NEXT_RELEASE
src/lib/common/globals.h
src/lib/rest/ConnectionInfo.cpp
src/lib/serviceRoutines/versionTreat.cpp
test/functionalTest/cases/0000_version_operation/version_via_rest.test
test/functionalTest/cases/0501_cors/version_request.test
test/functionalTest/cases/1916_fiware_correlator/fiware_correlator.test
test/unittests/serviceRoutines/versionTreat_test.cpp

The new flag allows to simplify the output of GET /version in some tests.
This is motivated by the work done in PR https://github.com/telefonicaid/fiware-orion/pull/4511, to allow having a same set of tests no matter if basic-expr or jexl-expr flavours.

ADD libVersions option for GET /version

---

CHANGES_NEXT_RELEASE
CMakeLists.txt

Example compilation in file, before the change in CMakeList.txt:
> cd /home/fermin/src/fiware-orion/BUILD_DEBUG/src/lib/rest && /usr/bin/c++ -DDEBUG -DDEBUG_fermin -DLINUX -DLM_ON -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0 -I/home/fermin/src/fiware-orion/src/lib -Wall -Wno-unknown-pragmas -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -Werror -Wno-deprecated-declarations -fno-var-tracking-assignments -Wno-format-truncation -Wno-stringop-truncation -DLINUX -g   -fPIC -DDEBUG_SER  -fstack-protector -MD -MT src/lib/rest/CMakeFiles/rest.dir/rest.cpp.o -MF CMakeFiles/rest.dir/rest.cpp.o.d -o CMakeFiles/rest.dir/rest.cpp.o -c /home/fermin/src/fiware-orion/src/lib/rest/rest.cpp
> /usr/bin/ar qc librest.a CMakeFiles/rest.dir/rest.cpp.o CMakeFiles/rest.dir/restReply.cpp.o …

FIX compile using C++14

---

doc/manuals.jp/orion-api.md
doc/manuals/orion-api.md

This PR adds Japanese documentation about new transformations. It would be great if you could review this PR. 
Thanks.

(JP) ADD documentation about new transformations (#4561)

---

doc/manuals.jp/admin/logs.md
doc/manuals.jp/deprecated.md

This PR removes documentation about NGSIv1 lasting API ops. It would be great if you could review the PR.
Thanks.

(JP) REMOVE documentation about NGSIv1 lasting API ops (#4563)

---

test/functionalTest/cases/0000_large_requests/notification_different_sizes.test

Test was modified in PR https://github.com/telefonicaid/fiware-orion/pull/4569 but the calculation was incorrect for the d.d.d case. This PR should fix it.

FIX notification_different_sizes.test

---

test/functionalTest/cases/0000_statistics_operation/statistics_with_counters.test

Recently DISABLED in 4.0.0, actually it can be recovered just removing NGSIv1 operations.

FIX enable statistics_with_counters.test

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/common/JsonHelper.cpp
src/lib/common/JsonHelper.h
src/lib/common/errorMessages.h
src/lib/common/limits.h
src/lib/expressions/ExprContext.cpp
src/lib/jsonParseV2/parseSubscription.cpp
src/lib/ngsi/ContextAttribute.cpp
src/lib/ngsi/ContextAttribute.h
src/lib/ngsi/Metadata.h
src/lib/ngsiNotify/Notifier.cpp
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_http_ngsi_errors.test
test/functionalTest/cases/4085_custom_notifications_ngsi_payload/custom_notification_mqtt_ngsi_errors.test
test/functionalTest/cases/4556_eval_priority_in_expressions/eval_priority_crud_and_errors.test
test/functionalTest/cases/4556_eval_priority_in_expressions/eval_priority_in_expressions.test

ADD evalPriority feature

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about evalPriority feature. It would be great if you could review the PR.
Thanks.

(JP) ADD doc about evalPriority feature (#4590)

---

doc/manuals.jp/orion-api.md

This PR adds Japanese documentation about new transformations. It would be great if you could review the PR.
Thanks.

(JP) ADD doc about new transformations (#4595)

---

CHANGES_NEXT_RELEASE
doc/manuals/orion-api.md
src/lib/jsonParseV2/parseContextAttribute.cpp
test/functionalTest/cases/4585_datetime_with_min_max_operators/datetime_with_min_max_operators.test
test/functionalTest/cases/4585_datetime_with_min_max_operators/datetime_with_min_max_operators_create.test
test/functionalTest/cases/4585_datetime_with_min_max_operators/datetime_with_min_max_operators_errors.test

Issue https://github.com/telefonicaid/fiware-orion/issues/4585

FIX DateTime with min and max operators

---

doc/manuals.jp/orion-api.md

This PR adds Japanase documentation about metadata in JEXL context. It would be great if you could review the PR.
Thanks.

(JP) ADD doc about metadata in JEXL context (#4600)

---

test/functionalTest/cases/0501_cors/registration_cors.test
test/functionalTest/cases/1492_limit_zero/limit_zero_regs.test
test/functionalTest/cases/3004_v2_reg_create/v2_reg_create.test
test/functionalTest/cases/3004_v2_reg_create/v2_reg_create_errors.test
test/functionalTest/cases/3005_GET_registrations/get_registrations.test
test/functionalTest/cases/3005_GET_registrations/get_registrations_with_pagination.test
test/functionalTest/cases/3006_delete_registrations/delete_reg_using_v2_created_using_v2.test
test/functionalTest/cases/3008_get_registration/get_reg_using_v2_created_using_v2.test
test/functionalTest/cases/3176_entity_without_attributes_not_listed/entity_without_attributes_not_listed.test
test/functionalTest/cases/3282_compound_not_render_in_not_matching_registration/compound_not_render_in_not_matching_registration.test
test/functionalTest/cases/3363_fwd_query_on_fail/fwd_query_on_fail.test

This PR does a .test simplification, removing legacyForwarding: true (a deprecated feature) in test that don't need it. They are probably old test developed in the times when NGSIv2 forwarding was not fully working.
After this PR the only tree .test that use legacyForwarding: true are he following ones:
* 0000_deprecated_checkings/log_deprecate_warning.test: which checks deprecated features logging as this one
* 3162_context_providers_legacy_non_primitive/blanked_out_attr.test: not sure of the usage of legacyForwarding: true in this case, but this .test seems to be the regression of a particular fixed bug, so I prefer not touching it.
* 3944_legacy_forwarding_rendering/legacy_forwarding_rendering.test: which checks the CRUD of the legacyForwarding field
In addition, note that none of …

FIX remove legacyForwarding true in test that does not need it

---

doc/manuals.jp/admin/build_source.md

This PR adds Japanese documentation about coverage framework. It would be great if you could review the PR.
Thanks.

(JP) Add documentation about coverage framework (#4607)

---

makefile

Little continuation fix of PR https://github.com/telefonicaid/fiware-orion/pull/4607

FIX CLEAN_COVDERAGE_REPORT macro in makefile

---

CHANGES_NEXT_RELEASE
src/lib/apiTypesV2/Subscription.cpp
src/lib/apiTypesV2/Subscription.h
src/lib/cache/subCache.cpp
src/lib/mongoBackend/MongoCommonUpdate.cpp
test/functionalTest/cases/4605_alterationtype_entityupdate_with_notifyonmetadatachange/alterationtype_entityupdate_with_notifyonmetadatachange.test

Fix: metadata modifications are not considered as change (with regards to subscription alterationTypes) if notifyOnMetadataChange is false 

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseContextAttribute.cpp
src/lib/jsonParseV2/parseMetadata.cpp
test/functionalTest/cases/1039_ngsiv2_date_support/basic_dates_support.test
test/functionalTest/cases/2654_iso8601_as_alias_for_DateTime/basic_dates_support_for_iso8601.test
test/functionalTest/cases/3000_allow_creation_transient_entities/failing_create_transient_entity_with_invalid_date.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_attr.test
test/functionalTest/cases/3533_null_in_datetime_and_geo/null_in_datetime_md.test
test/functionalTest/cases/4585_datetime_with_min_max_operators/datetime_with_min_max_operators_errors.test
test/functionalTest/cases/4616_improve_log_invalid_date/improve_log_invalid_date.test

FIX improve attribute and metadata invalid format dates for DateTime types in logs

---

scripts/utils/delete_subscriptions.py

Delete subscriptions in bulk this python script (Issue #4578 )

Delete subscriptions in bulk using python script

---

CHANGES_NEXT_RELEASE
src/app/contextBroker/contextBroker.cpp

Issue #4668
Tested:
```
$ ORION_CONN_MEMORY=20 ORION_MQTT_MAX_AGE=0 ORION_REQ_TIMEOUT=20 contextBroker -fg -logLevel INFO
time=2025-04-24T07:01:16.000Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[1109]:main | msg=start command line <contextBroker -fg -logLevel INFO>
time=2025-04-24T07:01:16.000Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[973]:logEnvVars | msg=env var ORION_REQ_TIMEOUT (-reqTimeout): 20
time=2025-04-24T07:01:16.000Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[969]:logEnvVars | msg=env var ORION_CONN_MEMORY (-connectionMemory): 20
time=2025-04-24T07:01:16.000Z | lvl=INFO | corr=N/A | trans=N/A | …
```

FIX env vars values with unsigned int or long types where not correctly printed at startup time in INFO log level

---

docker/README.jp.md
docker/README.md
docker/docker-compose.yml
docker/raspberry_pi.jp.md
docker/raspberry_pi.md

As explained in MongoDB documentation (https://www.mongodb.com/docs/manual/core/journaling/)
> NOTE
> Starting in MongoDB 6.1, journaling is always enabled. As a result, MongoDB removes the `storage.journal.enabled` option and the corresponding `--journal` and `--nojournal` command-line options.

REMOVE deprecated mongo CLI in compose files

---

src/app/contextBroker/contextBroker.cpp

Related with issue https://github.com/telefonicaid/fiware-orion/issues/4668, somehow continuation of PR https://github.com/telefonicaid/fiware-orion/pull/4670

FIX right type for variable

---

CHANGES_NEXT_RELEASE
src/lib/serviceRoutines/postNotifyContext.cpp
test/functionalTest/cases/0000_statistics_operation/statistics_with_counters.test

Issue #4261 
Check
```
(p3) fermin@bodoque:~/src/fiware-orion/test/valgrind$ contextBroker --version | head -n 1
4.2.0-next (git version: 319cd1a6b32c8d939eb41d0a8c3399cd1bded1f2) flavours: jexl-expr
(p3) fermin@bodoque:~/src/fiware-orion/test/valgrind$ ./valgrindTestSuite.sh statistics_with_counters.test
lun 12 may 2025 17:31:16 CEST
Run tests 0 to 0
./valgrindTestSuite.sh: línea 243: cd: test/valgrind: No existe el fichero o el directorio
Test 001/1: 0000_statistics_operation/statistics_with_counters ...................................................................................... OK (20.13 seconds)
Total test time: 20.32 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```
(Note the commit above is the same in this PR)

FIX memory leak in POST /v2/op/notify operation

---

CHANGES_NEXT_RELEASE
src/lib/jsonParseV2/parseNotification.cpp
src/lib/mongoBackend/mongoNotifyContext.cpp
src/lib/ngsi10/NotifyContextRequest.cpp
src/lib/ngsi10/NotifyContextResponse.cpp
src/lib/ngsi10/NotifyContextResponse.h
src/lib/rest/restReply.cpp
src/lib/serviceRoutines/postNotifyContext.cpp
test/functionalTest/cases/4681_notify_op/notify_op.test
test/functionalTest/simplyTestHarness.sh
test/unittests/ngsi10/NotifyContextRequest_test.cpp
test/unittests/testData/ngsi10.notifyContextResponse.badIsPattern.valid.json

The first commit in this PR (81a4eeb5dff7ae95d66ab76c676630fa7f985319) shows how this **must not** work.
It is not very important (as this operations is not very used and, even in this case, the response use to be ignored) but we should fix to adhere to our API (https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#notify-post-v2opnotify).
Bonus-track: simplyTestHarness.sh script a a wrapper of testHarness.sh with the env var configurations, useful to debug

POST /v2/op/notify must not response in NGSIv1 format

---

README.md
launch.json
scripts/check_files_compliance.py

Repository should be IDE-neutral (thus I'm not creating this file directly in `.vscode/launch.json` path :) but I think it can be an useful help to people using VSCode to develop Orion code.

ADD example lanuch.json file for VSCode

---

docker/Dockerfile.alpine

bash doesn't exist in Alpine. Use ash

FIX shell interpreter in Dockerfile.alpine

---

src/lib/mongoBackend/MongoGlobal.cpp

It doesn't happen in 4.2.0, so no entry in CNR is done in this PR.
Probably introduced in PR https://github.com/telefonicaid/fiware-orion/pull/4603 or in the follow up fixes related with https://github.com/telefonicaid/fiware-orion/issues/4681.

FIX avoid Runtime Error overloging when no geofilter is actually used
